### ISSUE TITLE
What does PIXEL_MEANS do?

### ISSUE THREAD

**Issue by CodeJjang** [jwyang/faster-rcnn.pytorch#101]
```
# Pixel mean values (BGR order) as a (1, 1, 3) array
# We use the same pixel mean for all networks even though it's not exactly what
# they were trained with
__C.PIXEL_MEANS = np.array([[[102.9801, 115.9465, 122.7717]]])
```
What is the purpose of pixel means?  
Do I need to change it if I'm using a cusotm dataset?  
If yes, then how exactly do I calculate this value?

**Comment by jwyang** [comment]
@CodeJjang this is aimed to adapt to the pre-trained caffe models, which you typically do not need to change.

**Comment by CodeJjang** [comment]
Thanks
