### ISSUE TITLE
ROI Pooling in C

### ISSUE THREAD

**Issue by karanchahal** [jwyang/faster-rcnn.pytorch#106]
Hey, I was just going through your code. Amazing job btw !

I wated to ask you , why is the ROI pooling layer implemented in C ? , Are the python functions not fast enough at iterating loops ? 

Some insight would be very helpful 

Thanks !

**Comment by jwyang** [comment]
Hi, @karanchahal , thanks,

Yes, you are right, implementing with c will be much faster than in python. Also, since all the implantations involves low-level cuda code, C is necessary.

**Comment by karanchahal** [comment]
I see that you have used crop pooling for transforming ROI's . Are there any plans to use a R-FCN layer instead of the traditional ROI Pooling ? I read in the paper, that it is faster. Any thoughts on this ?

Paper link : https://arxiv.org/abs/1605.06409

**Comment by jwyang** [comment]
Hi, @karanchahal thus far we have no plan to integrate it into our implementation but welcome to contribute it!
