### ISSUE TITLE
error in test_net.py

### ISSUE THREAD

**Issue by RichardMrLu** [jwyang/faster-rcnn.pytorch#11]
python test_net.py --dataset pascal_voc --net vgg16 --checksession 1 --checkepoch 19 --checkpoint 1251 --cuda

Traceback (most recent call last):
  File "test_net.py", line 225, in <module>
    rois, cls_prob, bbox_pred, rpn_loss, rcnn_loss = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/raid/home/wangw/.pyenv/versions/2.7.13/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/raid/wangw/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn_cascade.py", line 97, in forward
    bbox_pred_select = torch.gather(bbox_pred_view, 1, rois_label.long().view(rois_label.size(0), 1, 1).expand(rois_label.size(0), 1, 4))
AttributeError: 'NoneType' object has no attribute 'long'

type(rois_label) is Nonetype, so it crashed, how to solve this problem? Thanks for your answer.

**Comment by jwyang** [comment]
@RichardMrLu , this might be caused by a modification to faster_rcnn_cascade.py. I will figure out soon and let you know.

**Comment by RichardMrLu** [comment]
Thanks a lot

**Comment by jwyang** [comment]
it is a bit weird, since self.training should be false during test. In this case, it will not go to line 97 in faster_rcnn_cascade.py. Could you please tell me what the value of self.training is?

**Comment by RichardMrLu** [comment]
if self.training:
            roi_data = self.RCNN_proposal_target(rois, gt_boxes, num_boxes)
            rois, rois_label, rois_target, rois_inside_ws, rois_outside_ws = roi_data

            rois_label = Variable(rois_label.view(-1))
            rois_target = Variable(rois_target.view(-1, rois_target.size(2)))
            rois_inside_ws = Variable(rois_inside_ws.view(-1, rois_inside_ws.size(2)))
            rois_outside_ws = Variable(rois_outside_ws.view(-1, rois_outside_ws.size(2)))
        else:
            rois_label = None
            rois_target = None
            rois_inside_ws = None
            rois_outside_ws = None
            rpn_loss_cls = 0
            rpn_loss_bbox = 0

**Comment by jwyang** [comment]
yes, if self.training=False, it should not go to line 97, and thus the error should no emerge.

**Comment by jwyang** [comment]
I tried on my side, it works fine.

**Comment by RichardMrLu** [comment]
I have try it:
 if not self.class_agnostic:
            print('here')
            # select the corresponding columns according to roi labels
            bbox_pred_view = bbox_pred.view(bbox_pred.size(0), int(bbox_pred.size(1) / 4), 4)
            bbox_pred_select = torch.gather(bbox_pred_view, 1, rois_label.long().view(rois_label.size(0), 1, 1).expand(rois_label.size(0), 1, 4))
            bbox_pred = bbox_pred_select.squeeze(1)
finally it print 'here', so it go to line 97..

**Comment by jwyang** [comment]
I see, could you please update the faster_rcnn_cascade.py. I had already solved this. you are using an earlier version, I guess.

**Comment by RichardMrLu** [comment]
..OK, How to updata this py file to you?

**Comment by jwyang** [comment]
just run: git check out lib/model/faster_rcnn/faster_rcnn_cascade.py. By this, you should see:

if self.training and not self.class_agnostic:

instead of 

if not self.class_agnostic:

**Comment by RichardMrLu** [comment]
I got it,some files had updata, I check it and changed some. Thanks for you help.
on VOC2007:
AP for aeroplane = 0.7225
AP for bicycle = 0.7836
AP for bird = 0.6605
AP for boat = 0.5748
AP for bottle = 0.5270
AP for bus = 0.7791
AP for car = 0.8471
AP for cat = 0.8304
AP for chair = 0.4836
AP for cow = 0.7670
AP for diningtable = 0.6578
AP for dog = 0.7842
AP for horse = 0.8287
AP for motorbike = 0.7632
AP for person = 0.7690
AP for pottedplant = 0.4388
AP for sheep = 0.7052
AP for sofa = 0.6336
AP for train = 0.7565
AP for tvmonitor = 0.7043
Mean AP = 0.7008
~~~~~~~~
Results:
0.723
0.784
0.660
0.575
0.527
0.779
0.847
0.830
0.484
0.767
0.658
0.784
0.829
0.763
0.769
0.439
0.705
0.634
0.756
0.704
0.701

**Comment by jwyang** [comment]
that's great!

Which roi pooling method did you use? 

Also, from my experiments, 6~8 epochs might be enough actually. Continuing to train the model typically does not get extra improvements.

**Comment by RichardMrLu** [comment]
19 epochs, in cfg files vgg16.yml: POOLING_MODE: pool

**Comment by jwyang** [comment]
sounds good. pool is expected get mAP around this number. You can refer to the table in the readme, and have a try to evaluate epoch=7. You might be able to get a slightly higher mAP.

**Comment by RichardMrLu** [comment]
OK,Thanks for your work, I will try it.

**Comment by jwyang** [comment]
sounds good, let me know if you have any further problems.

**Comment by RichardMrLu** [comment]
Your help is much appreciated.
