### ISSUE TITLE
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by Bala93** [jwyang/faster-rcnn.pytorch#113]
Python 2.7 Anaconda
Cuda-8.0

**Comment by Bala93** [comment]
The nvcc path in make.sh file was wrong. Resolved.

**Comment by Markovcom** [comment]
@Bala93 ,hello i meet with the same problem,can you help me?

**Comment by li10141110** [comment]
@Bala93 @Markovcom, hi i met same problem,can you tell me your solution?

**Comment by Markovcom** [comment]
@li10141110 please see this,https://github.com/jwyang/faster-rcnn.pytorch/issues/114#issuecomment-378286240

**Comment by relh** [comment]
For me, I don't have root access. I can't make such symlinks to the system. So I just symlinked to the problem dir and it works now. Not recommending this, just for those in a similar situation to me with whom no environmental variable setting has helped.

`ln -s ~/cuda/include/* ~/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/`

**Comment by relh** [comment]
For me, I don't have root access. I can't make such symlinks to the system. So I just symlinked to the problem dir and it works now. Not recommending this, just for those in a similar situation to me with whom no environmental variable setting has helped.

`ln -s ~/cuda/include/* ~/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/`

**Comment by ZiyuBao** [comment]
@Bala93 How did you resolve it, please? Same problem
