### ISSUE TITLE
sh make.sh

### ISSUE THREAD

**Issue by Markovcom** [jwyang/faster-rcnn.pytorch#114]
x86_64-conda_cos6-linux-gnu-gcc -pthread -fno-strict-aliasing -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/zhoulinmao/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/zhoulinmao/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/zhoulinmao/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/zhoulinmao/anaconda2/include/python2.7 -c /home/code/zhoulinmao/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop_cuda.c -o ./home/code/zhoulinmao/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop_cuda.o
x86_64-conda_cos6-linux-gnu-gcc -pthread -shared -Wl,-O2,--sort-common,--as-needed,-z,relro,-z,now -Wl,-rpath,/home/zhoulinmao/anaconda2/lib -L/home/zhoulinmao/anaconda2/lib -Wl,--no-as-needed ./_roi_crop.o ./home/code/zhoulinmao/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.o ./home/code/zhoulinmao/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop_cuda.o /home/code/zhoulinmao/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop_cuda_kernel.cu.o -L/home/zhoulinmao/anaconda2/lib -lpython2.7 -o ./_roi_crop.so
x86_64-conda_cos6-linux-gnu-gcc: error: /home/code/zhoulinmao/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop_cuda_kernel.cu.o: No such file or directory
Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/home/zhoulinmao/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 167, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/zhoulinmao/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 103, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/zhoulinmao/anaconda2/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/zhoulinmao/anaconda2/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/zhoulinmao/anaconda2/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/zhoulinmao/anaconda2/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1

**Comment by jwyang** [comment]
Hi, @Markovcom , you might want to check which arch your GPU is, and modify sh make.sh on line https://github.com/jwyang/faster-rcnn.pytorch/blob/1dbb0728abc3e6cca574e3a2a8d31f9bf6ea45b8/lib/make.sh#L8 to

**Comment by Markovcom** [comment]
@jwyang thanks,it works well

**Comment by relh** [comment]
For me, I don't have root access. I can't make such symlinks to the system. So I just symlinked to the problem dir and it works now. Not recommending this, just for those in a similar situation to me with whom no environmental variable setting has helped.

`ln -s ~/cuda/include/* ~/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/`

**Comment by codewithsk** [comment]
I'm getting the same error despite setting the right gencode. I tried both:

`CUDA_ARCH="-gencode arch=compute_60,code=sm_60 \
           -gencode arch=compute_35,code=sm_35 \
           -gencode arch=compute_37,code=sm_37 \
           -gencode arch=compute_50,code=sm_50 \
           -gencode arch=compute_52,code=sm_52 \
           -gencode arch=compute_61,code=sm_61 "`

and 

`CUDA_ARCH="-gencode arch=compute_60,code=sm_60"`

**Comment by DreadPiratePsyopus** [comment]
@codewithsk  Did you manage to solve this issue?

**Comment by codewithsk** [comment]
Yeah! Turns out my CUDA path was set wrong.

**Comment by ZiyuBao** [comment]
What if I do not have a CUDA-enabled GPU? What do I have to change in make.sh?
