### ISSUE TITLE
Just Train Network for Person Detection

### ISSUE THREAD

**Issue by ahkarami** [jwyang/faster-rcnn.pytorch#118]
Dear @jwyang,
Thank you for your work. I have a general question. In the VOC and COCO datasets there are some classes (e.g., 20 or 80 classes (person, car, horse, etc.) for object detection). If one train the network just for one class (e.g., just the person class) will the accuracy (mAP) of person detection increase?
Have you ever try this?

**Comment by jwyang** [comment]
@ahkarami That's a good point! I did not try that, but looks reasonable that the performance would improve.

**Comment by jwyang** [comment]
@ahkarami I am closing this issue for now, let me know if you encounter some issues when you train on a single category.

**Comment by ahkarami** [comment]
@jwyang,
Thank you for your reply. Maybe the below link is also be interesting:
[RefineDet just train for person detection](https://github.com/sfzhang15/RefineDet/issues/42)
