### ISSUE TITLE
How to complied with python3.6

### ISSUE THREAD

**Issue by zhiyugege** [jwyang/faster-rcnn.pytorch#120]
Hi
The Default python version is python2.7 how to compllied with python3
Thanks!

**Comment by jwyang** [comment]
Hi, @zhiyugege ,You can actually directly compile with anaconda python 3

**Comment by dongfengxijian** [comment]
@jwyang How to do it? I am a tiro.  Should I change the file make.sh?

**Comment by dongfengxijian** [comment]
@zhiyugege Have you complied it successfully?
