### ISSUE TITLE
CPU version of ROI Crop

### ISSUE THREAD

**Issue by gullalc** [jwyang/faster-rcnn.pytorch#128]
CPU version of ROI Align and NMS was updated a few days back.
Any idea, when will the CPU version of ROI crop be added?

**Comment by jwyang** [comment]
Hi, @gullalc It might take some time, :), please stay being tuned.

**Comment by gullalc** [comment]
Sure.

**Comment by jwyang** [comment]
I am closing this issue for now, will let you know if we have implemented cpu version ROI crop.

**Comment by gullalc** [comment]
Thanks.
Really need the CPU version to deploy the model on a system which has no GPU.
