### ISSUE TITLE
Some questions about compilation

### ISSUE THREAD

**Issue by zhoulukuan** [jwyang/faster-rcnn.pytorch#130]
I am a beginner at pytorch. I have compiled successfully but I don't know why I need to do so.
I used to think the realted work of pytorch is through pure python. Do I have to compile cuda code if I want to use GPU? What should I do if I want to learn about the code of this part and change it for my own project? Could you offer me some help？

**Comment by CodeJjang** [comment]
Some functions were written in low level for efficiency, for example, parts of the ROI pooling, NMS function, etc. Therefore, you have to compile it.  

The code lays in this project (usually ends with .c and .h, which are C source files and header files), and you can change and re-compile it as you wish.

**Comment by jwyang** [comment]
Hi, @zhoulukuan , I think @CodeJjang explained what you ask about. I am closing this for now.
