### ISSUE TITLE
Getting Assertion Error

### ISSUE THREAD

**Issue by ashutoshIITK** [jwyang/faster-rcnn.pytorch#132]
`Appending horizontally-flipped training examples...
wrote gt roidb to /data/shivamash/faster-rcnn.pytorch/data/cache/voc_2007_trainval_gt_roidb.pkl
Traceback (most recent call last):
  File "train_plane.py", line 206, in <module>
    imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdb_name)
  File "/data/shivamash/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 116, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/data/shivamash/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 113, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/data/shivamash/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 97, in get_training_roidb
    imdb.append_flipped_images()
  File "/data/shivamash/faster-rcnn.pytorch/lib/datasets/imdb.py", line 123, in append_flipped_images
    assert (boxes[:, 2] >= boxes[:, 0]).all()
AssertionError
`
I am training on a different dataset. I have prepared them in PASCAL_VOC format. Can you suggest why I am getting this error?
Thanks.

**Comment by jwyang** [comment]
Hi, @ashutoshIITK, assert (boxes[:, 2] >= boxes[:, 0]).all() failed since at least one of your provided bounding boxes have wrong numbers such that x_right < x_left, please check your coordinates of the bounding boxes in your data.

**Comment by CodeJjang** [comment]
@ashutoshIITK This happened to me as well, check that your dataset bounding boxes do not have negative points or out of image height / width points. My dataset was tagged with a program which apparently allowed those values.

**Comment by ashutoshIITK** [comment]
Yes, my dataset bounding boxes had negative points and also x_max<x_min. 
I have fixed them. Thank you very much for your help.

**Comment by jwyang** [comment]
Since the issue has been solved, closing it for now.

**Comment by AtriSaxena** [comment]
I am also getting same error. I check the file. In below xml file i am getting error. I think data is right. What other possible solution you can suggest. 
`<annotation>
<folder>open_images_volume</folder>
<filename>000a9c6e22a06877.jpg</filename>
<path>/mnt/open_images_volume/000a9c6e22a06877.jpg</path>
<source>
<database>Unknown</database>
</source>
<size>
<width>1024</width>
<height>765</height>
<depth>3</depth>
</size>
<segmented>0</segmented>
<object>
<name>Giraffe</name>
<pose>Unspecified</pose>
<truncated>0</truncated>
<difficult>0</difficult>
<bndbox>
<xmin>290</xmin>
<ymin>53</ymin>
<xmax>650</xmax>
<ymax>748</ymax>
</bndbox>
</object>
</annotation>`
