### ISSUE TITLE
What is the tool that used to convert caffe pre-train model to pytorch

### ISSUE THREAD

**Issue by Microos** [jwyang/faster-rcnn.pytorch#133]
What is the tool that you used to convert caffe pre-train model to pytorch?

**Comment by jwyang** [comment]
Hi, @Microos , you can use this: https://github.com/marvis/pytorch-caffe-darknet-convert

**Comment by Microos** [comment]
@jwyang Thanks. I currently can't find a converter that works with `pytorch 0.2.0`, your info would be a great help 😃
