### ISSUE TITLE
A Bug in minibatch.py

### ISSUE THREAD

**Issue by libuyu** [jwyang/faster-rcnn.pytorch#134]
Line 43 in minibatch.py is 
"gt_inds = np.where(roidb[0]['gt_classes'] != 0 & np.all(roidb[0]['gt_overlaps'].toarray() > -1.0, axis=1))[0]".
There is a problem caused by the priority of operators. The operator "&" will be first implemented and then the "!=". This is not what we want.
It can be fixed by adding a pair of parentheses like this: 
gt_inds = np.where((roidb[0]['gt_classes'] != 0) & np.all(roidb[0]['gt_overlaps'].toarray() > -1.0, axis=1))[0]

**Comment by jwyang** [comment]
@libuyu thanks for pointing this! I will go ahead to fix this.

**Comment by jwyang** [comment]
@libuyu thanks again for pointing out this bug, have fixed it and close this issue.
