### ISSUE TITLE
Problem met when try to train my personal dataset

### ISSUE THREAD

**Issue by KevinYijunQian** [jwyang/faster-rcnn.pytorch#135]
I have already made  annotation, label and replaced the content in VOCDevkit2007. However, i can't find the place to change the index of net for example, numoutput of the net. 

 'USE_GPU_NMS': True}
Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
voc_2007_trainval gt roidb loaded from /home/zhiqi.cheng/faster-rcnn.pytorch/data/cache/voc_2007_trainval_gt_roidb.pkl
done
Preparing training data...
done
before filtering, there are 100 images...
after filtering, there are 100 images...
100 roidb entries
Loading pretrained weights from data/pretrained_model/resnet101_caffe.pth
Traceback (most recent call last):
  File "trainval_net.py", line 257, in <module>
    fasterRCNN.create_architecture()
  File "/home/zhiqi.cheng/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 135, in create_architecture
    self._init_modules()
  File "/home/zhiqi.cheng/faster-rcnn.pytorch/lib/model/faster_rcnn/resnet.py", line 235, in _init_modules
    resnet.load_state_dict({k:v for k,v in state_dict.items() if k in resnet.state_dict()})
  File "/home/zhiqi.cheng/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 487, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named layer1.0.conv1.weight, whose dimensions in the model are torch.Size([64, 8, 1, 1]) and whose dimensions in the checkpoint are torch.Size([64, 64, 1, 1]).

**Comment by wade12138** [comment]
Did this problem solved? I also want to train on my personal dataset, but i have no idea how to make it. Can you please explain more about how to change the dataset? thanks a lot.

**Comment by jwyang** [comment]
@KevinYijunQian did you download the pretrained caffe net from this [link](https://www.dropbox.com/s/iev3tkbz5wyyuz9/resnet101_caffe.pth?dl=0)? There might be some mismatching between the state_dict and resnet you defined.
