### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by ZhangJiajun1995** [jwyang/faster-rcnn.pytorch#137]
before filtering, there are 1244 images...
after filtering, there are 1244 images...
1244 roidb entries
./weights/vgg16/pascal_voc
Loading pretrained weights from data/pretrained_model/vgg16_caffe.pth
/home/test/Zhangjiajun/skin/faster-rcnn/faster-rcnn.pytorch/lib/model/rpn/rpn.py:68: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  rpn_cls_prob_reshape = F.softmax(rpn_cls_score_reshape)
/home/test/Zhangjiajun/skin/faster-rcnn/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py:98: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  cls_prob = F.softmax(cls_score)
Traceback (most recent call last):
  File "trainval_net.py", line 340, in <module>
    loss.backward()
  File "/home/test/anaconda3/envs/gj/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/test/anaconda3/envs/gj/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
  File "/home/test/Zhangjiajun/skin/faster-rcnn/faster-rcnn.pytorch/lib/model/roi_align/functions/roi_align.py", line 39, in backward
    assert(self.feature_size is not None and grad_output.is_cuda)
AssertionError

When training on my data, I meet the problem. I find the grad_output.is_cuda is False, how to modify?
Thank you!

**Comment by shuikehuo** [comment]
you can use python trainval_net.py --cuda.

**Comment by jwyang** [comment]
great! closing this issue. :)

**Comment by 1csu** [comment]
@ZhangJiajun1995 ,if I use pycharm to perform the code,what should I do?

**Comment by smileSJin** [comment]
good answer   thanks
