### ISSUE TITLE
Pretrained Coco Weights

### ISSUE THREAD

**Issue by artuncF** [jwyang/faster-rcnn.pytorch#138]
Can you share pretrained weights(trained on coco dataset)? I would like to perform finetuning using pretrained coco dataset weights and my own dataset. Converting other models(caffe etc.) seems like not entirely performable and there are other converting issues. So I will be glad if you share pretrained pytorch model on coco dataset.@jwyang

**Comment by gulcinbaykal** [comment]
Actually, I have the same request. I also want to finetune pretrained coco or pascal voc weights with my own dataset. Thanks in advance !

**Comment by jwyang** [comment]
you guys already got the pretrained model on coco, right?

**Comment by artuncF** [comment]
No we didn't. We trained the model with coco from scratch.

**Comment by jwyang** [comment]
@artuncF sounds good. Actully, you can download them from the links in readme.

**Comment by jwyang** [comment]
let me know if you have any further issues, I am closing this issue now.

**Comment by sshaar** [comment]
So the links for the pertained model on COCO is the one given in the README file?
