### ISSUE TITLE
About roi_pooling

### ISSUE THREAD

**Issue by g5996706** [jwyang/faster-rcnn.pytorch#14]
Thank you for providing a pytorch version.
I have a question,if I just want to use the roi_pooling and roi_align.
How can I copy them to my code?

**Comment by g5996706** [comment]
And I found that it seem no file (lib/model/roi_pooling/src/roi_pooling.cu.o)

**Comment by jwyang** [comment]
you can copy the whole folder in lib/model/roi_pool and lib/model/roi_align to your project. Then, use the same command to as used in lib/model/faster_rcnn/faster_rcnn_cascade.
