### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by ZhangJiajun1995** [jwyang/faster-rcnn.pytorch#140]
Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
/home/test/Zhangjiajun/skin/faster-rcnn-jw/faster-rcnn.pytorch/data/VOCdevkit2007/VOC2007/JPEGImages/000005.jpg
/home/test/Zhangjiajun/skin/faster-rcnn-jw/faster-rcnn.pytorch/data/VOCdevkit2007/VOC2007/JPEGImages/000007.jpg
[500, 500, 500]
voc_2007_trainval gt roidb loaded from /home/test/Zhangjiajun/skin/faster-rcnn-jw/faster-rcnn.pytorch/data/cache/voc_2007_trainval_gt_roidb.pkl
{'boxes': array([[ 90,   5, 224, 144]], dtype=uint16), 'gt_classes': array([15], dtype=int32), 'gt_ishard': array([0], dtype=int32), 'gt_overlaps': <1x21 sparse matrix of type '<class 'numpy.float32'>'
        with 1 stored elements in Compressed Sparse Row format>, 'flipped': False, 'seg_areas': array([18900.], dtype=float32)}
[[ 90   5 224 144]]
{'boxes': array([[ 16, 152, 614, 587]], dtype=uint16), 'gt_classes': array([15], dtype=int32), 'gt_ishard': array([0], dtype=int32), 'gt_overlaps': <1x21 sparse matrix of type '<class 'numpy.float32'>'
        with 1 stored elements in Compressed Sparse Row format>, 'flipped': False, 'seg_areas': array([261164.], dtype=float32)}
[[ 16 152 614 587]]
Traceback (most recent call last):
  File "trainval_net.py", line 211, in <module>
    imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdb_name)
  File "/home/test/Zhangjiajun/skin/faster-rcnn-jw/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 116, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/test/Zhangjiajun/skin/faster-rcnn-jw/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 116, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/test/Zhangjiajun/skin/faster-rcnn-jw/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 113, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/test/Zhangjiajun/skin/faster-rcnn-jw/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 97, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/test/Zhangjiajun/skin/faster-rcnn-jw/faster-rcnn.pytorch/lib/datasets/imdb.py", line 133, in append_flipped_images
    assert (boxes[:, 2] >= boxes[:, 0]).all()
AssertionError

I train the model on VOC2007 dataset, then i meet the problem. The widths  of  image is right, but the data of boundbox is different from that in .xml. I don't clear the detail of loading data,so I don't know what lead to the problem. But I prepare my data according to the form of VOC2007, it succeed to load data but another assertionerror in issue#137.
Thanks in advance.

**Comment by jwyang** [comment]
Hi, @ZhangJiajun1995, I think it is because the issues occurs on your bounding boxes. please make sure boxes[:, 2] >= boxes[:, 0] for all your training data.
