### ISSUE TITLE
Did anyone uses the tensorboard successfully ?

### ISSUE THREAD

**Issue by guyan277** [jwyang/faster-rcnn.pytorch#143]
When I set use_tfboard  True in args, this error comes out and only with the situation using tensor board. @jwyang do you have any clue how to solve it ?

Called with args:
Namespace(batch_size=1, checkepoch=1, checkpoint=0, checkpoint_interval=10000, checksession=1, class_agnostic=False, cuda=True, dataset='pascal_voc_2012', disp_interval=100, large_scale=False, lr=0.001, lr_decay_gamma=0.1, lr_decay_step=5, mGPUs=False, max_epochs=20, net='vgg16', num_workers=0, optimizer='sgd', resume=False, save_dir='/home/guyan/tmp/frrcnn/models', session=1, start_epoch=1, use_tfboard=True)
Segmentation fault (core dumped)

**Comment by Karthik-Suresh93** [comment]
Yes, I too get the same error. Were you able to resolve it?

**Comment by jwyang** [comment]
I will figure out that soon

**Comment by srp753** [comment]
I am facing a similar issue. @guyan277 were you able to resolve it?

**Comment by guyan277** [comment]
@srp753  please use tensorboardX

**Comment by KurtSunxx** [comment]
how can i find the path that contains the tensorboard files?

**Comment by frgfm** [comment]
@KurtSunxx The folder's location is defined right there: https://github.com/jwyang/faster-rcnn.pytorch/blob/pytorch-1.0/trainval_net.py#L294-L296

Feel free to change it
