### ISSUE TITLE
PyTorch 0.4.0 Compatibility Issue

### ISSUE THREAD

**Issue by zhefan** [jwyang/faster-rcnn.pytorch#144]
The current codebase has issues with PyTorch 0.4 release. Any plan for updating the repo regarding the new API of PyTorch? @jwyang 

Most issues can be solved by simply converting cuda tensor to numpy. However, I have some trouble correcting this line: https://github.com/jwyang/faster-rcnn.pytorch/blob/8e029c56f7227a30a5b8efa90a8b235f9ee14479/lib/model/rpn/proposal_target_layer_cascade.py#L133

**Comment by LiuHao-THU** [comment]
have you solved this problem??? 

i also met this after i change the 1/num_example to 1/num_example.item() or .float()

**Comment by LiuHao-THU** [comment]
okay, i have try to solve this problem. 
![image](https://user-images.githubusercontent.com/30975916/39515436-acff2fec-4e2c-11e8-918e-a56f62527991.png)
and this is the reason~
x = torch.randn(5, 4)
x.index(1)
pytorch would print the same problem. the solution is we have to wrap the tensor format to a tuple format by add '[]' to the offset
another problem is is_device, u just comment the line, that would be okay...
another thing I do not understand is pytorch provide a better API to load data, why we use the blob to load the data. which makes things looks so complicated!

another solution is use index_select(0, offset.view(-1).long())

however, I am not sure if the results is right.

finally, pytorch version changes a lot which makes me feel frustrated to adapt the newest version!!!

**Comment by zhefan** [comment]
Not yet. Consider PyTorch 1.0 is coming, I would stick with 0.3 for now.

**Comment by Dataphz** [comment]
I also encounter this problem about this code in pytorch 0.4.0,  try to change the code  index(offset.view(-1)) to the index((offset.view(-1),)),  and get right.
I think the **index function** is update in pytorch 0.4.0 but din't update in document.

**Comment by jwyang** [comment]
now the master supports pytorch-0.4.0 and tensorboard. feel free to use them.

**Comment by zhefan** [comment]
Thanks, much appreciated.
