### ISSUE TITLE
Roi Align pooling size mismatches the input size of layer 4

### ISSUE THREAD

**Issue by sunhs** [jwyang/faster-rcnn.pytorch#152]
https://github.com/jwyang/faster-rcnn.pytorch/blob/8e029c56f7227a30a5b8efa90a8b235f9ee14479/cfgs/res101.yml#L16

Thanks for your great work and I've got a problem here. In vanilla ResNet, the input size of layer 4 is `14x14x1024`. But the yml file listed above says `POOLING_SIZE=7`. Does that mean you feed an input of size `7x7x1024` to layer 4, and still enable the first bottleneck to downsample the input?

As is found in [Eniac-Xie's implementation](https://github.com/Eniac-Xie/faster-rcnn-resnet/blob/master/models/pascal_voc/ResNet101_BN_SCALE_Merged/faster_rcnn_end2end/train.prototxt), he has `pooled_w=14` and `pooled_h=14` in the roi pooling layer. I wonder whether that matters.

If I made any mistake, please correct me.

**Comment by jwyang** [comment]
Hi, @sunhs , yes, you are right, we are using pooling size = 7. actually, smaller pooling size does not mean poorer performance. In our testing, it turned out work well.
