### ISSUE TITLE
error: ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by chj1933** [jwyang/faster-rcnn.pytorch#157]
/home/chenghj/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c:87:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int idx = 0; idx < output_size; ++idx)
     ^
/home/chenghj/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c:87:5: note: use option -std=c99 or -std=gnu99 to compile your code
/home/chenghj/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c: In function ‘ROIAlignBackwardCpu’:
/home/chenghj/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c:143:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
     #pragma omp parallel for 
 ^
/home/chenghj/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c:144:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int idx = 0; idx < output_size; ++idx)
     ^
Traceback (most recent call last):
  File "build.py", line 38, in <module>
    ffi.build()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 167, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 103, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/chenghj/.local/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/chenghj/.local/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/chenghj/.local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/chenghj/.local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by chj1933** [comment]
thanks @Tsingzao I have solved this by
int idx;
for (idx = 0; idx < output_size; ++idx)
but appear 
/home/chenghj/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c: In function ‘ROIAlignForwardCpu’:
/home/chenghj/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c:86:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
     #pragma omp parallel for 
 ^
/home/chenghj/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c:88:14: error: redeclaration of ‘idx’ with no linkage
     for (int idx = 0; idx < output_size; ++idx)
              ^
/home/chenghj/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c:87:9: note: previous declaration of ‘idx’ was here
     int idx;
         ^
/home/chenghj/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c:88:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int idx = 0; idx < output_size; ++idx)
     ^
/home/chenghj/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c:88:5: note: use option -std=c99 or -std=gnu99 to compile your code
/home/chenghj/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c: In function ‘ROIAlignBackwardCpu’:
/home/chenghj/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c:144:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
     #pragma omp parallel for 
 ^
/home/chenghj/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c:146:14: error: redeclaration of ‘idx’ with no linkage
     for (int idx = 0; idx < output_size; ++idx)
              ^
/home/chenghj/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c:145:9: note: previous declaration of ‘idx’ was here
     int idx;
         ^
/home/chenghj/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.c:146:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int idx = 0; idx < output_size; ++idx)
     ^
Traceback (most recent call last):
  File "build.py", line 38, in <module>
    ffi.build()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 167, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 103, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/chenghj/.local/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/chenghj/.local/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/chenghj/.local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/chenghj/.local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by Tsingzao** [comment]
Maybe a redundant 'int' in the for loop?

It should be 
```
int idx;
for (idx = 0; idx < output_size; ++idx)
```

instead of 
```
int idx;
for (int idx = 0; idx < output_size; ++idx)
```

**Comment by chj1933** [comment]
@Tsingzao got it ,thanks. Excuse me again , can you send me a resnet101_caffe.pth? I don't know why I can't download it. MY email is 1136076788@qq.com

**Comment by jwyang** [comment]
glad you guys solved this, closing this issue
