### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by xiaomengyc** [jwyang/faster-rcnn.pytorch#16]
Can you please share your trained models? Thank you!

**Comment by jwyang** [comment]
@xiaomengyc, I will upload the pre-trained model today. stay tuned

**Comment by xiaomengyc** [comment]
Thanks! 

By the way,  I also encountered the exactly same problem when compiling the ROI polling layer[here](https://github.com/jwyang/faster-rcnn.pytorch/issues/15), and I fixed it by changing the [line 3](https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/make.sh#L3) (`CUDA_PATH=/usr/local/cuda/`) in make.sh to `CUDA_PATH=/usr/local/cuda/` and adding the environment variables
`export PATH=/usr/local/cuda-8.0/bin:$PATH`
`export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:$LD_LIBRARY_PATH`

**Comment by jwyang** [comment]
great, thanks! @xiaomengyc. 

I added them into my bashrc, while @g5996706 might do not.

I will add them to make.sh, and remind in readme that these two should be exported.

thanks again!

BTW, I am retraining all the models with the most recent code. I already uploaded a trained resnet101 on pascal-voc (see the link in the table). Now I am training in other settings. All models on pascal voc will be available tonight. COCO might be two days later.

**Comment by xiaomengyc** [comment]
Thanks a lot!

**Comment by Cadene** [comment]
Thanks! Do you plan to train on visual genome as well? @jwyang

**Comment by jwyang** [comment]
@Cadene , yes, I will once I have enough GPUs, :).  It should be very soon after I finish the retraining on coco.

**Comment by claudiogreco** [comment]
What datasets are the models pretrained on? Could you upload a models pretrained on Visual Genome? Thank you!

**Comment by Cadene** [comment]
@jwyang I trained a VGG16 on Visual Genome for 20 epochs and got a mAP of 4.4%.

I could share it. However, I just want to know if someone achieved a better mAP :)

**Comment by jwyang** [comment]
@Cadene great, how many object categories did you try?

**Comment by Cadene** [comment]
@jwyang the maximum possible (2500 classes)

**Comment by jwyang** [comment]
@Cadene I guess that performance should be ok, I tried 1600 categories, and got around 10 mAP. Do you want to share your trained model, you can give me a link, I will add it to readme.

**Comment by Cadene** [comment]
@jwyang http://data.lip6.fr/cadene/faster-rcnn.pytorch/faster_rcnn_1_19_48611.pth

**Comment by jwyang** [comment]
@Cadene appreciate!

**Comment by jwyang** [comment]
@Cadene , could you also tell me the detailed hyper parameters for training the model, as shown in the tables?

**Comment by Cadene** [comment]
@jwyang So it was a VGG16 (not a Resnet101) trained on a Tesla P100 with the default hyper parameters:
- lr 0.001
- lr_decay 5
- batch_size 4
- max_epoch 20
- 12707MiB / 16276MiB

**Comment by jwyang** [comment]
@Cadene got it, thanks!

**Comment by jnhwkim** [comment]
@jwyang, the pre-trained model of @Cadene is a VGG16, not ResNet-101 as he pointed out. README should be updated correctly.

**Comment by coldmanck** [comment]
Hi @Cadene 
Could you please share the classes you used to train the model? So that we can try it out.

**Comment by coldmanck** [comment]
Hi @jwyang @Cadene 

I have tried out the faster rcnn pretrained on Visual Genome, however as there's missing information on the classes data the detector cannot find the correct label: my detection results are like these:

![img1_det](https://user-images.githubusercontent.com/7726203/41807324-0e7340a0-7700-11e8-92d0-4796c36941bc.jpg)
![img2_det](https://user-images.githubusercontent.com/7726203/41807328-1f787168-7700-11e8-9967-f849e7a75748.jpg)
![img3_det](https://user-images.githubusercontent.com/7726203/41807330-22cf139e-7700-11e8-928c-8c423d62c285.jpg)

The labels are incorrect due to incorrect order of my 2,501 classes. I tried the to firstly sort by the name of the classes but still wrong. Could you please give any advice?

**Comment by aronsar** [comment]
I would also like to know the answer to coldmanck's question. Thanks!

**Comment by coldmanck** [comment]
@aronsar 

Finally I trained the faster rcnn model on the VG dataset by myself. Just need to fix an order of classes then all are fine.

**Comment by aronsar** [comment]
@coldmanck 

Would it be possible for you to share your trained model and object vocabulary files?

Thank you!
-Aron

**Comment by coldmanck** [comment]
@aronsar 

I trained on 1600 classes of VG, following 1600-40-20 split by [bottom-up attention](https://github.com/peteanderson80/bottom-up-attention).

Classes label:
[objects_vocab.txt](https://github.com/jwyang/faster-rcnn.pytorch/files/2355431/objects_vocab.txt)

Trained model snapshot:
https://drive.google.com/file/d/1CS5ipXkxvjq5benNOLanQKNmVEaEtO6-/view?usp=sharing

**Comment by aronsar** [comment]
@coldmanck Thank you so much!

**Comment by AHUgaoyuan** [comment]
When I bash make.sh, there is such a mistake:
“ImportError: torch.utils.ffi requires the cffi package”
But when I installed cffi, there was another mistake：.“Could not install packages due to an EnvironmentError: [Errno 13] 权限不够:”
How do I solve this problem?

**Comment by Xinzhu-Fang** [comment]
@coldmanck Thank you for the model and object vocab file. 
The visual genome dataset looks overwhelming to me. bottom-up attention doesn't go into the details of preparing this dataset. Can someone expand on this?
If someone can provide res101 trained with 2500 classes or vgg16 rained with 1600 classes, I would appreciate that

**Comment by czydfj** [comment]
Thank u for your object vocab very much !
But the link to the pre-trained model is not available.  Could you please share a new link of the model?

**Comment by czydfj** [comment]
> @jwyang http://data.lip6.fr/cadene/faster-rcnn.pytorch/faster_rcnn_1_19_48611.pth

Thank u so much for your model!
But my 2500-classes vocab has different order with yours. Could you please share your 2500-classes vocab txt for your 'faster_rcnn_1_19_48611.pth'?

**Comment by czydfj** [comment]
> @aronsar
> 
> I trained on 1600 classes of VG, following 1600-40-20 split by [bottom-up attention](https://github.com/peteanderson80/bottom-up-attention).
> 
> Download my classes label: [objects_vocab.txt](https://github.com/jwyang/faster-rcnn.pytorch/files/2355431/objects_vocab.txt) and [Trained model snapshot](https://drive.google.com/file/d/1CS5ipXkxvjq5benNOLanQKNmVEaEtO6-/view?usp=sharing)
> 
> You may simply modify the lines in `demo.py` of `pascal_classes = ...` to
> 
> ```
> with open('data/genome/1600-400-20/objects_vocab.txt', 'r') as f:
>     data = f.readlines()
> pascal_classes = np.asarray(['__background__'])
> pascal_classes = np.append(pascal_classes, np.asarray(data))
> pascal_classes = [x.strip('\n') for x in pascal_classes]
> ```

Thank u for your object vocab very much !
But the link to the pre-trained model is not available. Could you please share a new link of the model?

**Comment by yestinl** [comment]
@aronsar @czydfj Did you get the new link of the resnet101 model train on VG?

**Comment by UQEKV** [comment]
I have this error. How can I fix it? thank you
Traceback (most recent call last):
  File "trainval_net.py", line 321, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 54, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/faster-rcnn.pytorch/lib/model/rpn/rpn.py", line 78, in forward
    im_info, cfg_key))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/faster-rcnn.pytorch/lib/model/rpn/proposal_layer.py", line 147, in forward
    keep_idx_i = nms(proposals_single, scores_single.squeeze(1), nms_thresh)
RuntimeError: Not compiled with GPU support

**Comment by FlyDre** [comment]
> I have this error. How can I fix it? thank you
> Traceback (most recent call last):
> File "trainval_net.py", line 321, in
> rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
> return self.module(*inputs[0], **kwargs[0])
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/content/drive/My Drive/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 54, in forward
> rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/content/drive/My Drive/faster-rcnn.pytorch/lib/model/rpn/rpn.py", line 78, in forward
> im_info, cfg_key))
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/content/drive/My Drive/faster-rcnn.pytorch/lib/model/rpn/proposal_layer.py", line 147, in forward
> keep_idx_i = nms(proposals_single, scores_single.squeeze(1), nms_thresh)
> RuntimeError: Not compiled with GPU support

hello, sir. Have you saved this problem? if you do , could you please talk about it. Appreciate!

**Comment by chenbl21** [comment]
我在编译的过程中输入sh make.sh 报错：/home/cbl/miniconda3/envs/py27/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: 致命错误：cuda.h：没有那个文件或目录
 #include "cuda.h"
                  ^
编译中断。
请问如何解决？

**Comment by YuanGao-cs** [comment]
高远已接收到您的邮件，谢谢~

**Comment by kalng62** [comment]
ImportError: cannot import name 'imread' from 'scipy.misc' (/usr/local/lib/python3.7/dist-packages/scipy/misc/__init__.py) 
I have run this in the colab and got the error code like this

**Comment by YuanGao-cs** [comment]
高远已接收到您的邮件，谢谢~
