### ISSUE TITLE
sh make.sh on CPU ?

### ISSUE THREAD

**Issue by Shaunlipy** [jwyang/faster-rcnn.pytorch#162]
Hi, I'm wondering how would I be able run: sh make.sh on CPU?

It says  rod_crop_cuda_kernel.cu.o, file was built for unsupported file format ( 0x7F 0x45 ...)

I'm using python 3.5.

Thanks

**Comment by jwyang** [comment]
hi, @Shaunlipy , now the roi_crop does not support cpu yet, you can mute the compile in make.sh.
