### ISSUE TITLE
Can roi-pooling layer be implemented by AffineTransformation function in PyTorch?

### ISSUE THREAD

**Issue by D-X-Y** [jwyang/faster-rcnn.pytorch#165]
Hi,

It seems that roi-pooling layer can be implemented by AffineTransformation function in PyTorch.
Will this kind of implementations be more efficient than the C++ version of roi-pooling layer?

Thanks

**Comment by jwyang** [comment]
@D-X-Y yes, basically it is the same, but this repo provides the multi-image support for roi-pooling, which might not be integrated in the official pytorch.
