### ISSUE TITLE
resnet101_caffe.pth

### ISSUE THREAD

**Issue by chj1933** [jwyang/faster-rcnn.pytorch#166]
Good Samaritan, Who can send me a resnet101_caffe.pth? I can't download it . thanks, everyone. my email is 1136076788@qq.com

**Comment by chenhongming** [comment]
resnet101_caffe.pth:
https://pan.baidu.com/s/1_wjiB-ZjjCtyaMkpxtyvfg

**Comment by joeyisdabao** [comment]
Who can send me a resnet101_caffe.pth? I can't download it . thanks, everyone. my email is 914283644@qq.com
