### ISSUE TITLE
pre-training model

### ISSUE THREAD

**Issue by chenhongming** [jwyang/faster-rcnn.pytorch#17]
I can not download the pre-training model, can you provide a new link? Thanks.

**Comment by jwyang** [comment]
@chenhongming I have updated the links for pre-trained model, have a try.

**Comment by chenhongming** [comment]
I still can not download the pre-train model, I do not know that it is my personal reason or the same with other people. Is it possible that the browser problem? Is there any other way?
Sorry to bother you.

**Comment by jwyang** [comment]
Hi, @chenhongming , is it because you are blocked by the GFW? What happened when you tried to download the pre-trained model?

**Comment by chenhongming** [comment]
<img width="568" alt="2018-01-17 10 22 34" src="https://user-images.githubusercontent.com/29920966/35022350-76c2da96-fb70-11e7-930f-329697d27d89.png">
This is the case.

**Comment by chenhongming** [comment]
hi@jwyang  I am likely to be blocked by the GFW.Is there any other way?Such as Baidu cloud disk or others.Thanks

**Comment by jwyang** [comment]
@chenhongming , sure, I will upload them to Baidu Yun and other places. Will let you know soon.

**Comment by jwyang** [comment]
@chenhongming , I have uploaded the two pretrained caffe models to my VT server, check whether you can download:

vgg16: https://filebox.ece.vt.edu/~jw2yang/faster-rcnn/pretrained-base-models/vgg16_caffe.pth

res101: https://filebox.ece.vt.edu/~jw2yang/faster-rcnn/pretrained-base-models/resnet101_caffe.pth

**Comment by chenhongming** [comment]
@jwyang Thank you very much for your help.Now I can download it.

**Comment by jwyang** [comment]
@chenhongming , great!
