### ISSUE TITLE
errors in demo.py

### ISSUE THREAD

**Issue by manyuyuya** [jwyang/faster-rcnn.pytorch#176]
load checkpoint /mnt/md0/ymy/faster-rcnn.pytorch/data/pretrained_model/vgg16/pascal_voc/faster_rcnn_1_12_416.pth
Traceback (most recent call last):
  File "demo.py", line 194, in <module>
    fasterRCNN.load_state_dict(checkpoint['model'])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for vgg16:
	Missing key(s) in state_dict: "RCNN_base.0.bias", "RCNN_base.2.bias", "RCNN_base.2.weight", "RCNN_base.5.bias", "RCNN_base.5.weight", "RCNN_base.7.bias", "RCNN_base.7.weight", "RCNN_base.10.bias", "RCNN_base.10.weight", "RCNN_base.12.bias", "RCNN_base.12.weight", "RCNN_base.14.bias", "RCNN_base.14.weight", "RCNN_base.17.bias", "RCNN_base.17.weight", "RCNN_base.19.bias", "RCNN_base.19.weight", "RCNN_base.21.bias", "RCNN_base.21.weight", "RCNN_base.24.bias", "RCNN_base.24.weight", "RCNN_base.26.bias", "RCNN_base.26.weight", "RCNN_base.28.bias", "RCNN_base.28.weight", "RCNN_top.0.bias", "RCNN_top.0.weight", "RCNN_top.3.bias", "RCNN_top.3.weight". 
	Unexpected key(s) in state_dict: "RCNN_base.1.weight", "RCNN_base.1.bias", "RCNN_base.1.running_mean", "RCNN_base.1.running_var", "RCNN_base.4.0.conv1.weight", "RCNN_base.4.0.bn1.weight", "RCNN_base.4.0.bn1.bias", "RCNN_base.4.0.bn1.running_mean", "RCNN_base.4.0.bn1.running_var".....
	While copying the parameter named "RCNN_rpn.RPN_Conv.weight", whose dimensions in the model are torch.Size([512, 512, 3, 3]) and whose dimensions in the checkpoint are torch.Size([512, 1024, 3, 3]).
	While copying the parameter named "RCNN_base.0.weight", whose dimensions in the model are torch.Size([64, 3, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 3, 7, 7]).
	While copying the parameter named "RCNN_cls_score.weight", whose dimensions in the model are torch.Size([21, 4096]) and whose dimensions in the checkpoint are torch.Size([21, 2048]).
	While copying the parameter named "RCNN_bbox_pred.weight", whose dimensions in the model are torch.Size([84, 4096]) and whose dimensions in the checkpoint are torch.Size([84, 2048]).

when I run the demo.py with the pretrained model(faster_rcnn_1_12_416.pth) I download, I meet an error above.At first I downlod the pretrained model suported in readme but I meet some errors about checkpoints.And then I download a new pretrainde model from https://www.dropbox.com/s/cn8gneumg4gjo9i/faster_rcnn_1_12_416.pth?dl=0 and meet the question above. How can I fix them?Thank you for help

**Comment by jwyang** [comment]
it seems that you are using vgg to load resent or vice versa. Please check whether you are specify the correct architecture.

**Comment by 1csu** [comment]
@manyuyuya 
I encounter similar problem as you described.Have you find the available solution?Please let me know soon.Thanks in advance!
