### ISSUE TITLE
Does RoI_crop support multi-image batch pooling?

### ISSUE THREAD

**Issue by smilewsw** [jwyang/faster-rcnn.pytorch#177]
If I set batch_size >1, will the roi_crop layer work correctly?  If yes, does it request the rois of each image in the batch have the same amount?

**Comment by jwyang** [comment]
yes, I think it works fine, at least could obtain good performance. though without much check for now. Also, it does not require the number of rois for each image to be identical.

**Comment by smilewsw** [comment]
There is a variable "roiPerImage" in the file roi_crop_cuda_kernel.cu, which seems to require the number of rois for each image to be identical. And in the file faster_rcnn.py, grid_xy has no information about the match between rois and images.

**Comment by jwyang** [comment]
@smilewsw yes, my bad, you are right that this merely support the same number of rois per image.
