### ISSUE TITLE
demo with pretrained caffe models

### ISSUE THREAD

**Issue by fguney** [jwyang/faster-rcnn.pytorch#18]
There are multiple issues running demo.py with provided caffe models.
Could you please check it?

**Comment by jwyang** [comment]
@fguney , thanks for reminding, I have updated demo file. Now it should work fine.

**Comment by fguney** [comment]
No it's not just the calling of the function:

- cascade in line 31:
`from model.faster_rcnn.faster_rcnn import _fasterRCNN`

- pretrained = False in lines 166 and 168:
`# initilize the network here.
  if args.net == 'vgg16':
    fasterRCNN = vgg16(pascal_classes, pretrained=True, class_agnostic=args.class_agnostic)
  elif args.net == 'res101':
    fasterRCNN = resnet(pascal_classes, 101, pretrained=True, class_agnostic=args.class_agnostic)`

- model loading in lines [179-183]
`fasterRCNN.create_architecture() 
 
  #print("load checkpoint %s" % (load_name))
  #checkpoint = torch.load(load_name)
  #fasterRCNN.load_state_dict(checkpoint['model'])
  #if 'pooling_mode' in checkpoint.keys():
  #  cfg.POOLING_MODE = checkpoint['pooling_mode']`

I think they should all be updated. Even after correcting these (I'm not sure if I did it right), I cannot get any detections on the example images.

**Comment by jwyang** [comment]
hi, @fguney I just checked those you mentioned. You are rights, 

1. I have removed line 31.

2. pretrianed=False is okay.

3. load checkpoint is needed, and you should have a pre-trained faster r-cnn model in hand. you can download one from: https://www.dropbox.com/s/cn8gneumg4gjo9i/faster_rcnn_1_12_416.pth?dl=0

**Comment by fguney** [comment]
Thanks! Maybe you should add point 3 in the ReadMe for other people having the same confusion.

**Comment by jwyang** [comment]
@fguney you are right, I will add them to readme. 

Yes, I will share all models soon! I am now retraining all models. You will find them available in this week.
