### ISSUE TITLE
pytorch 0.4.0     hangs after 1 epoch   when num_workers>1

### ISSUE THREAD

**Issue by leoshine** [jwyang/faster-rcnn.pytorch#181]
Training hangs without any error message after 1 epoch when dataloader has more than 1 workers.

It should be related to the deadlock of DataLoader.

But when switching back to pytorch 0.3.1, everything is fine.

**Comment by Pythonisfun** [comment]
can you share the code of putorch 0.4.0

**Comment by jwyang** [comment]
i did not confront this issue, will assume this has been solved and close this issue for now.
