### ISSUE TITLE
Difference in test performance between CPU and GPU

### ISSUE THREAD

**Issue by gullalc** [jwyang/faster-rcnn.pytorch#184]
I trained a model on GPU and tested on both CPU and GPU.
Turns out that while testing on CPU, it makes a lot of mistakes in recognition, which it did not on GPU. 

Looks like CPU version needs more testing. If anyone has any idea, kindly help.

**Comment by gullalc** [comment]
I think I was able to get similar results by making the following changes in nms_cpu.py
```
xx1 = np.maximum(x1[i], x1[order[1:]])
yy1 = np.maximum(y1[i], y1[order[1:]])
xx2 = np.maximum(x2[i], x2[order[1:]])
yy2 = np.maximum(y2[i], y2[order[1:]])
```
to 
```
xx1 = np.maximum(x1[i], x1[order[1:]])
yy1 = np.maximum(y1[i], y1[order[1:]])
xx2 = np.minimum(x2[i], x2[order[1:]])
yy2 = np.minimum(y2[i], y2[order[1:]])
```

Btw, haven't been working with CPU implementation lately. Maybe you can verify if the results are same or not.

**Comment by BAILOOL** [comment]
@gullalc, indeed, it has solved the problem. Thank you.
