### ISSUE TITLE
Compiling Error when sh make.sh

### ISSUE THREAD

**Issue by MH-Ng** [jwyang/faster-rcnn.pytorch#194]
Pardon me for possibly an easy question.
After I modified the arch in make.sh and tapped "sh make.sh", I faced a puzzled question. The information shows that I haven't the file or directory 
"faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop_cuda_kernel.cu.o" and 
"faster-rcnn.pytorch/lib/model/nms/src/nms_cuda_kernel.cu.o".

I'm wondering if there have any solution to settle it?

Thanks in advance!

**Comment by rui1996** [comment]
I have the same problem. How do you fix it?

**Comment by mekong0404** [comment]
I Have the same problem please help
