### ISSUE TITLE
undefined symbol: __cudaPopCall Configuration

### ISSUE THREAD

**Issue by Wanggcong** [jwyang/faster-rcnn.pytorch#195]
Hi, when I compiled the file make.sh, I got a error:

What I have done: 
cd faster-rcnn.pytorch/lib   and run    ./make.sh
I got some warning: unsued variable 'inBottomRight' [-Wunsued-variable real inBottomRight=0],...

What I met:
When I run python demo.py, I got:
ImportError: /home/xxx/faster-rcnn.pytorch/lib/model/nms/_ext/nms/_nms.so: undefined symbol: __cudaPopCallConfiguration

What I have tried:
1) changed  '/usr/local/cuda/bin' into '/usr/local/cuda-9.2/bin'
2) added /usr/local/cuda-9.2/bin to ~/.bashrc     and source ~/.bashrc 
3) nvidia-smi, driver version 396.26;

- cuda-9.2

- no cudnn (because I cannot log in the nvidia cudnn)

- pytorch 0.4 (when installing, I use the command : conda install pytorch torchvision cuda91 -c pytorch)

Any suggestion will be appreciated! Thanks.

**Comment by gp1313** [comment]
@Wanggcong I'm facing the same issue.

**Comment by relh** [comment]
Checkout #190

**Comment by Wanggcong** [comment]
@relh Thanks for you reply!

**Comment by mengpengfei** [comment]
I'm facing the same issue.i can only use cuda8
