### ISSUE TITLE
train with pytorch pretrained model

### ISSUE THREAD

**Issue by shanyuhu** [jwyang/faster-rcnn.pytorch#2]
Hi, @jwyang ,
what is your test MAP with pytorch pretrained model, on voc07 dataset? I can only get 63.2%.

**Comment by jwyang** [comment]
Hi, it should be >68%, did you use caffe pre-trained model?

**Comment by shanyuhu** [comment]
I think it's fine with caffe pretrained models. For pytorch pretrained ones, the image preprocessing is  RGB, and ((I/255)-mean)/std, correct?

**Comment by jwyang** [comment]
yes, exactly, that should be the reason, you should transpose the RGB channel, and then use the data transformer to adapt to pytorch pre-trained model.

**Comment by shanyuhu** [comment]
ok, thanks~

**Comment by jwyang** [comment]
you're welcome, let me know if there is any other issues.
