### ISSUE TITLE
Does it really work on coco? can anyone write a step to step actions to make it work please????

### ISSUE THREAD

**Issue by isalirezag** [jwyang/faster-rcnn.pytorch#202]
I am having a hard time to make it work for coco dataset...

I tried both coco 2014 and coco 2017. BUT it sounds like thre exist the same problem...

Can anyone explain how to do it?

I constantly receive error regarding not having `instances_valminusminival2017.json'`

 in `trainval.py` we have:
```elif args.dataset == "coco":
      args.imdb_name = "coco_2017_train+coco_2017_valminusminival"
      args.imdbval_name = "coco_2017_minival"
```
but when you download and make the coco dataset there is no coco_2017_valminusminival or coco_2017_train...

can anyone PLEASE explain how to make or build or download:
`coco_2017_valminusminival` and `coco_2017_minival`
or
`coco_2014_valminusminival` and `coco_2014_minival`

It would be a hugee help : 

I have seen more that 50 issues regarding this problem for coco

and please dont say it is explain in this link. because if it was clear we werent asking again :)

any help...

**Comment by isalirezag** [comment]
I still dont know how to create those files and if someone know i will appreciate it if they can provide a detailed explanation for it....

Anyways, i found that for coco2014 we can download them from here:
https://drive.google.com/drive/folders/0B1_fAEgxdnvJSmF3YUlZcHFqWTQ

**Comment by yuhua666** [comment]
Hello, I'm sorry to bother you. I'm trying to train aitod. It is a data set very similar to coco, but I can't make it work because the source code seems to be customized for coco 2014. It seems that the soft link method you provide can be effective. Can you teach me? Thank you very much.
