### ISSUE TITLE
error: /Qstd=c99: No such file or directory/KeyError: 'CUDA_PATH'

### ISSUE THREAD

**Issue by Xixiesc13** [jwyang/faster-rcnn.pytorch#204]
When I run sh make.sh, error appears as following:
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
building 'pycocotools._mask' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pycocotools
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -std=c99 -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -Ipycocotools -I/usr/include/python2.7 -c pycocotools/maskApi.c -o build/temp.linux-x86_64-2.7/pycocotools/maskApi.o /Qstd=c99
**x86_64-linux-gnu-gcc: error: /Qstd=c99: No such file or directory
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1**
Compiling nms kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 10, in <module>
    cuda_root = os.environ['CUDA_PATH']
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'CUDA_PATH'
Compiling roi pooling kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 10, in <module>
    cuda_root = os.environ['CUDA_PATH']
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'CUDA_PATH'
Compiling roi align kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 10, in <module>
    cuda_root = os.environ['CUDA_PATH']
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'CUDA_PATH'
Compiling roi crop kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 10, in <module>
    cuda_root = os.environ['CUDA_PATH']
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
**KeyError: 'CUDA_PATH'**

**Comment by Anears** [comment]
Hello :D
I was stuck with the same problem.
Could you tell me what you did if you did it?
Thank you!

**Comment by Anubhav7** [comment]
well you could solve the "**x86_64-linux-gnu-gcc: error: /Qstd=c99: No such file or directory**" error by using -std=c99 in place of /Qstd=c99 in setup.py.

/Qstd=c99 is the way this option is specified for msvc.

for linux you should use -std=c99.

But there still are a lot of error while compiling the "master". We should use "roioffset" in the meantime.
