### ISSUE TITLE
Compilation errors with latest commit

### ISSUE THREAD

**Issue by gullalc** [jwyang/faster-rcnn.pytorch#207]
I am not able to successfully compile the cuda dependences with sh make.sh in the latest commit.
1. There is no nms_cuda.cpp file src. After adding and making the required changes as in roi_pooling/roi_crop, I keep getting lots of errors regarding gcc and dlls.

2. This is the error I get while compiling nms_cuda.cpp:
```In file included from /usr/include/c++/5/atomic:38:0,
                 from /opt/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Retainable.h:3,
                 from /opt/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Allocator.h:6,
                 from /opt/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/ATen.h:5,
                 from /home/gullals/Desktop/faster-rcnn.pytorch/lib/model/nms/src/nms_cuda.cpp:3:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
```

3. This is the error I get while compiling all other modules (roi_pooling/roi_align/roi_crop):
```
roi_pooling.cpp:4:21: error: expected constructor, destructor, or type conversion before ‘(’ token
 extern"C" __declspec(dllexport) int roi_pooling_forward(int pooled_height, int pooled_width, float spatial_scale
```

**Comment by rxqy** [comment]
I just ran into the same problem....
I think one can just solve it by switching to an earlier branch.
I changed to roioffset, and it worked

**Comment by Anubhav7** [comment]
I can also confirm that roioffset branch is working just fine

**Comment by Anubhav7** [comment]
better use revert-189-windows .. it is also compiling fine and is ahead of roioffset

**Comment by gullalc** [comment]
I already have the earlier version of this repo which works fine on ubuntu. Looks like the current version will compile on windows. Thanks for your inputs.

**Comment by jwyang** [comment]
sorry about that, i made a mistake and now i have recovered the previous version to master. try again!

**Comment by gullalc** [comment]
Ok. Thanks. Any idea when it will be successfully ported to windows?

**Comment by jwyang** [comment]
@gullalc this is not in my plan, some others are working on this, please stay tuning.

**Comment by jwyang** [comment]
closing this issue for now.
