### ISSUE TITLE
gcc: error: /Qstd=c99: no such file or dictionary

### ISSUE THREAD

**Issue by foreverzzx** [jwyang/faster-rcnn.pytorch#208]
while running sh make.sh, an error occured

gcc -pthread -B /home/coherent/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/coherent/anaconda3/lib/python3.6/site-packages/numpy/core/include -Ipycocotools -I/home/coherent/anaconda3/include/python3.6m -c pycocotools/maskApi.c -o build/temp.linux-x86_64-3.6/pycocotools/maskApi.o /Qstd=c99
gcc: error: /Qstd=c99: no such file or dictionary
error: command 'gcc' failed with exit status 1
I don't know how to deal with it

**Comment by arpitkath** [comment]
I was also getting the same error.
Install the pycocotools through `pip3 install pycocotools` and delete the directory `lib/pycocotools `present in the repository.
Hope this helps.

**Comment by jwyang** [comment]
@foreverzzx there was a mistake when I merge the pull request, now it recovers and try to clone the code again and compile it
