### ISSUE TITLE
CUDA_PATH Error. Why is that?

### ISSUE THREAD

**Issue by EldorIbragimov** [jwyang/faster-rcnn.pytorch#210]
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 10, in <module>
    cuda_root = os.environ['CUDA_PATH']
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'CUDA_PATH'
Compiling roi pooling kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 10, in <module>
    cuda_root = os.environ['CUDA_PATH']
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'CUDA_PATH'
Compiling roi align kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 10, in <module>
    cuda_root = os.environ['CUDA_PATH']
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'CUDA_PATH'
Compiling roi crop kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 10, in <module>
    cuda_root = os.environ['CUDA_PATH']
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'CUDA_PATH'

**Comment by EldorIbragimov** [comment]
I successfully run this version: https://github.com/ruotianluo/pytorch-faster-rcnn. Can you help me please?

**Comment by 3ZA** [comment]
try `which nvcc` 
I get the following output `/usr/local/cuda/bin/nvcc`
then `export CUDA_PATH=/usr/local/cuda/`

**Comment by EldorIbragimov** [comment]
I tried this which nvcc and I got  /usr/local/cuda-9.0/bin/nvcc
then I changed CUDA_PATH to = /usr/local/cuda-9.0/
But error is still the same

**Comment by jwyang** [comment]
Hi, @EldorIbragimov , I have changed a line in make.sh, now you just need to specify your cuda path at line 6. Let me you if you still have problem.

**Comment by jwyang** [comment]
@EldorIbragimov also, update your code and try again

**Comment by EldorIbragimov** [comment]
Now I am using older version of your code with pytorch 0.3.0 and it is working fine
BTW, have you updated your code for pytorch 0.4 version?

**Comment by jwyang** [comment]
@EldorIbragimov not sure, i will work on it when having time, should be in this summer. closing this issue.
