### ISSUE TITLE
nms_cpu wrong code?

### ISSUE THREAD

**Issue by zhenheny** [jwyang/faster-rcnn.pytorch#212]
Hi @jwyang  and @jiasenlu 
Is there code snippet in nms_cpu incorrect? 
Should xx2 and yy2 be the minimum between the two boxes on this line (https://github.com/jwyang/faster-rcnn.pytorch/blob/7079dfbc4e734168e1a123cb1a5a60cdc39f52ed/lib/model/nms/nms_cpu.py#L23)

Thanks

**Comment by jwyang** [comment]
hi, @zhenheny , thanks for reminding, i have fixed it.
