### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by Syrup274** [jwyang/faster-rcnn.pytorch#216]
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
building 'pycocotools._mask' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pycocotools
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -std=c99 -fPIC -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/numpy/core/include -Ipycocotools -I/usr/include/python2.7 -c pycocotools/maskApi.c -o build/temp.linux-x86_64-2.7/pycocotools/maskApi.o /Qstd=c99
x86_64-linux-gnu-gcc: error: /Qstd=c99: No such file or directory
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Compiling nms kernels by nvcc...
/home/wangzhe/faster-rcnn.pytorch/lib/model/nms
Including CUDA code.
['/home/wangzhe/faster-rcnn.pytorch/lib/model/nms/src/nms_cuda_kernel.lib', '/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/bin/Lib/site-packages/torch/lib/ATen.lib', '/home/wangzhe/faster-rcnn.pytorch/lib/model/nms/A:/NVIDIA/GPU Computing Toolkit/CUDA/v9.1/lib/x64/cudart.lib', '/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/bin/Lib/site-packages/torch/lib/_C.lib']
generating /tmp/tmpXynfIC/_nms.c
setting the current directory to '/tmp/tmpXynfIC'
running build_ext
building '_nms' extension
creating home
creating home/wangzhe
creating home/wangzhe/faster-rcnn.pytorch
creating home/wangzhe/faster-rcnn.pytorch/lib
creating home/wangzhe/faster-rcnn.pytorch/lib/model
creating home/wangzhe/faster-rcnn.pytorch/lib/model/nms
creating home/wangzhe/faster-rcnn.pytorch/lib/model/nms/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -std=c99 -fPIC -DWITH_CUDA -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -IA:/NVIDIA/GPU Computing Toolkit/CUDA/v9.1/include -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/bin/Lib/site-packages/torch/lib/include -I/usr/include/python2.7 -c _nms.c -o ./_nms.o
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -std=c99 -fPIC -DWITH_CUDA -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -IA:/NVIDIA/GPU Computing Toolkit/CUDA/v9.1/include -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/bin/Lib/site-packages/torch/lib/include -I/usr/include/python2.7 -c /home/wangzhe/faster-rcnn.pytorch/lib/model/nms/src/nms_cuda.cpp -o ./home/wangzhe/faster-rcnn.pytorch/lib/model/nms/src/nms_cuda.o
x86_64-linux-gnu-gcc: error: /home/wangzhe/faster-rcnn.pytorch/lib/model/nms/src/nms_cuda.cpp: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
Traceback (most recent call last):
  File "build.py", line 49, in <module>
    ffi.build()
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 164, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 100, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Compiling roi pooling kernels by nvcc...
/home/wangzhe/faster-rcnn.pytorch/lib/model/roi_pooling
Including CUDA code.
['/home/wangzhe/faster-rcnn.pytorch/lib/model/roi_pooling/src/roi_pooling.lib', '/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/bin/Lib/site-packages/torch/lib/ATen.lib', '/home/wangzhe/faster-rcnn.pytorch/lib/model/roi_pooling/A:/NVIDIA/GPU Computing Toolkit/CUDA/v9.1/lib/x64/cudart.lib', '/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/bin/Lib/site-packages/torch/lib/_C.lib']
generating /tmp/tmpx6gjWM/_roi_pooling.c
setting the current directory to '/tmp/tmpx6gjWM'
running build_ext
building '_roi_pooling' extension
creating home
creating home/wangzhe
creating home/wangzhe/faster-rcnn.pytorch
creating home/wangzhe/faster-rcnn.pytorch/lib
creating home/wangzhe/faster-rcnn.pytorch/lib/model
creating home/wangzhe/faster-rcnn.pytorch/lib/model/roi_pooling
creating home/wangzhe/faster-rcnn.pytorch/lib/model/roi_pooling/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -std=c99 -fPIC -DWITH_CUDA -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -IA:/NVIDIA/GPU Computing Toolkit/CUDA/v9.1/include -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/bin/Lib/site-packages/torch/lib/include -I/usr/include/python2.7 -c _roi_pooling.c -o ./_roi_pooling.o
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -std=c99 -fPIC -DWITH_CUDA -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -IA:/NVIDIA/GPU Computing Toolkit/CUDA/v9.1/include -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/bin/Lib/site-packages/torch/lib/include -I/usr/include/python2.7 -c /home/wangzhe/faster-rcnn.pytorch/lib/model/roi_pooling/src/roi_pooling.cpp -o ./home/wangzhe/faster-rcnn.pytorch/lib/model/roi_pooling/src/roi_pooling.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-std=c99’ is valid for C/ObjC but not for C++
/home/wangzhe/faster-rcnn.pytorch/lib/model/roi_pooling/src/roi_pooling.cpp:4:21: **error: expected constructor, destructor, or type conversion before ‘(’ token
 extern"C" __declspec(dllexport) int roi_pooling_forward(int pooled_height, int** 
                     ^
Traceback (most recent call last):
  File "build.py", line 49, in <module>
    ffi.build()
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 164, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 100, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Compiling roi align kernels by nvcc...
/home/wangzhe/faster-rcnn.pytorch/lib/model/roi_align
Including CUDA code.
['/home/wangzhe/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align_kernel.lib', '/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/bin/Lib/site-packages/torch/lib/ATen.lib', 'A:/NVIDIA/GPU Computing Toolkit/CUDA/v9.1/lib/x64/cudart.lib', '/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/bin/Lib/site-packages/torch/lib/_C.lib']
generating /tmp/tmpwb_nIK/_roi_align.c
setting the current directory to '/tmp/tmpwb_nIK'
running build_ext
building '_roi_align' extension
creating home
creating home/wangzhe
creating home/wangzhe/faster-rcnn.pytorch
creating home/wangzhe/faster-rcnn.pytorch/lib
creating home/wangzhe/faster-rcnn.pytorch/lib/model
creating home/wangzhe/faster-rcnn.pytorch/lib/model/roi_align
creating home/wangzhe/faster-rcnn.pytorch/lib/model/roi_align/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -std=c99 -fPIC -DWITH_CUDA -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -IA:/NVIDIA/GPU Computing Toolkit/CUDA/v9.1/include -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/bin/Lib/site-packages/torch/lib/include -I/usr/include/python2.7 -c _roi_align.c -o ./_roi_align.o
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -std=c99 -fPIC -DWITH_CUDA -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -IA:/NVIDIA/GPU Computing Toolkit/CUDA/v9.1/include -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/bin/Lib/site-packages/torch/lib/include -I/usr/include/python2.7 -c /home/wangzhe/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.cpp -o ./home/wangzhe/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-std=c99’ is valid for C/ObjC but not for C++
/home/wangzhe/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.cpp:87:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
     #pragma omp parallel for 
 ^
/home/wangzhe/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.cpp:145:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
     #pragma omp parallel for 
 ^
/home/wangzhe/faster-rcnn.pytorch/lib/model/roi_align/src/roi_align.cpp:16:21: error: expected constructor, destructor, or type conversion before ‘(’ token
 extern"C" __declspec(dllexport) int roi_align_forward(int aligned_height, int a
                     ^
Traceback (most recent call last):
  File "build.py", line 48, in <module>
    ffi.build()
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 164, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 100, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Compiling roi crop kernels by nvcc...
/home/wangzhe/faster-rcnn.pytorch/lib/model/roi_crop
Including CUDA code.
['/home/wangzhe/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop_cuda_kernel.lib', '/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/bin/Lib/site-packages/torch/lib/ATen.lib', 'A:/NVIDIA/GPU Computing Toolkit/CUDA/v9.1/lib/x64/cudart.lib', '/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/bin/Lib/site-packages/torch/lib/_C.lib']
generating /tmp/tmplVlR9I/_roi_crop.c
setting the current directory to '/tmp/tmplVlR9I'
running build_ext
building '_roi_crop' extension
creating home
creating home/wangzhe
creating home/wangzhe/faster-rcnn.pytorch
creating home/wangzhe/faster-rcnn.pytorch/lib
creating home/wangzhe/faster-rcnn.pytorch/lib/model
creating home/wangzhe/faster-rcnn.pytorch/lib/model/roi_crop
creating home/wangzhe/faster-rcnn.pytorch/lib/model/roi_crop/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -std=c99 -fPIC -DWITH_CUDA -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -IA:/NVIDIA/GPU Computing Toolkit/CUDA/v9.1/include -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/bin/Lib/site-packages/torch/lib/include -I/usr/include/python2.7 -c _roi_crop.c -o ./_roi_crop.o
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -std=c99 -fPIC -DWITH_CUDA -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -IA:/NVIDIA/GPU Computing Toolkit/CUDA/v9.1/include -I/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/bin/Lib/site-packages/torch/lib/include -I/usr/include/python2.7 -c /home/wangzhe/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.cpp -o ./home/wangzhe/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-std=c99’ is valid for C/ObjC but not for C++
/home/wangzhe/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.cpp:7:21: error: expected constructor, destructor, or type conversion before ‘(’ token
 **extern"C" __declspec(dllexport) int BilinearSamplerBHWD_updateOutput(THFloatTen**
                     ^
Traceback (most recent call last):
  File "build.py", line 49, in <module>
    ffi.build()
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 164, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 100, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/wangzhe/faster-rcnn.pytorch/py2_torch0.2.0/local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by jwyang** [comment]
@Syrup274 you should check your gcc version. It seems that you gcc version does not satisfy

**Comment by jwyang** [comment]
@Syrup274 , you can update your local and try to compile again. it should work now

**Comment by Syrup274** [comment]
Sorry for my delayed reply and thank you for your advice. I checked my GCC version and ensure it up to data. 
Before you updating your code, I found only the roioffset branch works. But now the master branch also works. Thanks for your update.
