### ISSUE TITLE
Training the model for custom datatset

### ISSUE THREAD

**Issue by mahavird** [jwyang/faster-rcnn.pytorch#22]
Hi @jwyang,

Thanks for your simplified implementation of Faster R-CNN in pytorch.

I have a custom dataset which has 36 classes, I would like to train a Faster-R-CNN model (VGG/RES101) for that?

Where do I get started, what changes need to be made?

I will make sure I open source the work I do during this process.

Thanks!

**Comment by jwyang** [comment]
Hi, @mahavird 

The first thing you need to do is writing a customized data loader for your own dataset. 

You can refer to the data loader for pascal_voc and coco in  lib/datasets/pascal_voc.py and lib/datasets/coco.py.

**Comment by JavHaro** [comment]
Hi @jwyang,
As i mentioned in a previous post I would like to train a Faster-R-CNN model (vgg16) with my own dataset. I have followed [this tutorial](https://github.com/deboc/py-faster-rcnn/tree/master/help) based on the code of Ross Girshick but adapting to your implementation. Now I'm trying to adapt the network model to my dataset but i don't know what should i modify to do it? Do you have any idea that could guide me?
Thanks!!

PS: I know that is a closed issue but i think it could be useful to have all the doubts related to customs dataset training together.
