### ISSUE TITLE
train on own dataset

### ISSUE THREAD

**Issue by wjx2** [jwyang/faster-rcnn.pytorch#221]
Hi,
If I want to use your code to train on our dataset, where should I modify?

**Comment by Worulz** [comment]
@wjx2 

fastest option is to use the pascal voc pattern. I recommend downloading the dataset and checking the paths. Then place your data in the same format.

Another option, if you want to create a more elegant solution. you can find out how it finds the file paths if you execute and print code from lib/datasets/pascal_voc.py. if you'd like to make a new imdb dataset add a line in [train_net.py](https://github.com/jwyang/faster-rcnn.pytorch/blob/efa6b0873b922409d50ee690035db5450a0fa45c/trainval_net.py#L160) similar to how dataset name is collected and similarly add it to [lib/datasets/factory.py](https://github.com/jwyang/faster-rcnn.pytorch/blob/efa6b0873b922409d50ee690035db5450a0fa45c/lib/datasets/factory.py#L22) then follow the pascal_voc.py format and create a new script with your dataset name. the python print and input function will be your best friend.

**Comment by wjx2** [comment]
@Worulz I couldn't find the network, I mean that in caffe faste rcnn, I should modify num_class etc. But I couldn't find this project to modify.

**Comment by Worulz** [comment]
@wjx2 it's hard coded in this [line](https://github.com/jwyang/faster-rcnn.pytorch/blob/efa6b0873b922409d50ee690035db5450a0fa45c/lib/datasets/pascal_voc.py#L48). 

Additionally, when you use the demo.py to see predictions. Make sure to change the classes [here](https://github.com/jwyang/faster-rcnn.pytorch/blob/efa6b0873b922409d50ee690035db5450a0fa45c/demo.py#L167).

If possible I recommend making a csv or txt file to store your classes and call it from there.

**Comment by wjx2** [comment]
@Worulz Thank you .
I have modify the file you mentioned above. And should I modify the network to adapt my datasets?(such as my dataset is not 20 classes).Like the py-faster-rcnn, we also should change the num_out and num_classes in the network. And I can't find where the network shoul modify in this project.

**Comment by wjx2** [comment]
@Worulz Thank you!
