### ISSUE TITLE
nms_cpu.py wrong 

### ISSUE THREAD

**Issue by htian01** [jwyang/faster-rcnn.pytorch#225]
xx2 = np.maximum(x2[i], x2[order[1:]])
yy2 = np.maximum(y2[i], y2[order[1:]])

should be 
xx2 = np.minimum(x2[i], x2[order[1:]])
yy2 = np.minimum(y2[i], y2[order[1:]])

**Comment by hbwx24** [comment]
I also have this doubts.Is there anything  special here?why is there no problem with the final result ?

**Comment by hbwx24** [comment]
@WHCer  
Hello，can changing the code improve the result?Is there something different after the change?

**Comment by WHCer** [comment]
While seems the code is not used...... Thus, no effect to result.

**Comment by hbwx24** [comment]
@WHCer thank you
