### ISSUE TITLE
AttributeError error when resume a pretrained model. 

### ISSUE THREAD

**Issue by maozezhong** [jwyang/faster-rcnn.pytorch#227]
I am new pytorcher. First, I have the same problem as #222, and my cuda version is 9.1, pytorch version was 0.4.0. Then, I changed my pytorch version to 0.3.1 as #222 commented. However when I run `CUDA_VISIBLE_DEVICES=0 python trainval_net.py \
                   --dataset pascal_voc --net res101 \
                   --bs 4 --nw 2 \
                   --lr 0.0001 \
                   --r True --checksession 1 --checkepoch 8 --checkpoint 13499 \
                   --cuda | tee logs/1_resume.log`   another problem occured when loading checkpoint: 
`AttributeError: 'module' object has no attribute '_rebuild_tensor_v2'`
can anyone help?

**Comment by maozezhong** [comment]
@jwyang

**Comment by maozezhong** [comment]
as https://github.com/pytorch/pytorch/issues/6801 said. `loading model is backward compatible but not forward compatible.` I changed pytorch version to a lower version , So it should be work. right? however it does not work in my case...

**Comment by maozezhong** [comment]
Never mind, I found the solution in https://discuss.pytorch.org/t/question-about-rebuild-tensor-v2/14560
just add these after  `import torch` : 
`# Monkey-patch because I trained with a newer version.
# This can be removed once PyTorch 0.4.x is out.
# See https://discuss.pytorch.org/t/question-about-rebuild-tensor-v2/14560
import torch._utils
try:
    torch._utils._rebuild_tensor_v2
except AttributeError:
    def _rebuild_tensor_v2(storage, storage_offset, size, stride, requires_grad, backward_hooks):
        tensor = torch._utils._rebuild_tensor(storage, storage_offset, size, stride)
        tensor.requires_grad = requires_grad
        tensor._backward_hooks = backward_hooks
        return tensor
    torch._utils._rebuild_tensor_v2 = _rebuild_tensor_v2`

**Comment by MrWanter** [comment]
not work for me, 0.4.0 cuda 9.0

**Comment by maozezhong** [comment]
strange, then you can try install pytorch 0.3.0
