### ISSUE TITLE
sh make.sh cffi version mismatch 

### ISSUE THREAD

**Issue by irislin1006** [jwyang/faster-rcnn.pytorch#228]
when I tried `sh make.sh`,
it showed that there is a version mismatch of cffi
However, as I tried to `pip install cffi==1.5.2`
it is not supported anymore.
Is the real reason for the error really because the version of `cffi==1.11.5` isn't suitable for this implementation,
or maybe there are other problems that i forget

> this is my error log

[
[error.txt](https://github.com/jwyang/faster-rcnn.pytorch/files/2162032/error.txt)
](url)

**Comment by Peratham** [comment]
pip install cffi==1.6 works for me.

**Comment by Peratham** [comment]
wait...by looking at your error.txt...
It seems you have two cffi in your system and it causes this problem.

**Comment by irislin1006** [comment]
Yes, I used a virtualenv to create a cleaner environment
But I did activate it
Could it be the problem of virtualenv?

**Comment by FrankYoungchen** [comment]
Do you faced with the problem?
cffi.ffiplatform.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by Peratham** [comment]
@irislin1006 One quick fix should be upgrading your system cffi to match with some pip's cffi. For example, apt-get python-cffi to 1.7 and pip again should work.

**Comment by Peratham** [comment]
@FrankYoungchen Is that python3?
