### ISSUE TITLE
I got very bad model with out using pretrained resnet101, how could I solve this problem?

### ISSUE THREAD

**Issue by jingyonghou** [jwyang/faster-rcnn.pytorch#231]
What if I don't use any pretrained model and train a new model from scratch, I have done that by setting the pretrained parameter to False and get very  bad results (mAP is about 0.001). How do I solve this problem?

**Comment by Worulz** [comment]
@jingyonghou 
- what's your data size?
- what type of data?
- What do your learning curves look like?
- How many epochs?
- Augmentation methods?
- Training methods? - there's different ways to do this. I would recommend reading up on kaggle of top competitions to find the neat trick they use to optimise predictions.
- weight initialisation?

**Comment by jingyonghou** [comment]
@Worulz 
Thanks for your comments.
I just use the VOC 2007 dataset and I'd like to know whether you have any experience on training a faster RCNN from scratch on VOC2007 and how does it behave?
