### ISSUE TITLE
RuntimeError: While copying the parameter named RCNN_rpn.RPN_cls_score.weight, whose dimensions in the model are torch.Size([18, 512, 1, 1]) and whose dimensions in the checkpoint are torch.Size([24, 512, 1, 1])

### ISSUE THREAD

**Issue by 978749951** [jwyang/faster-rcnn.pytorch#254]
@jwyang @manoja328 I try to follow the #26 to solve the problem but an other  error occur. Could you give me some advice?
The error is as follows:
load checkpoint data/vgg16/vg/faster_rcnn_1_19_48611.pth
While copying the parameter named RCNN_cls_score.weight, whose dimensions in the model are torch.Size([21, 4096]) and whose dimensions in the checkpoint are torch.Size([2501, 4096]), 
Traceback (most recent call last):
  File "demo.py", line 194, in <module>
    fasterRCNN.load_state_dict(checkpoint['model'])
  File "/home/chenjinchang/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 360, in load_state_dict
    own_state[name].copy_(param)

Not that I only add a line "args.set_cfgs = ['ANCHOR_SCALES', '[4, 8, 16, 32]', 'ANCHOR_RATIOS', '[0.5,1,2]']" to the demo.py.
The previous error is：
RuntimeError: While copying the parameter named RCNN_rpn.RPN_cls_score.weight, whose dimensions in the model are torch.Size([18, 512, 1, 1]) and whose dimensions in the checkpoint are torch.Size([24, 512, 1, 1])

**Comment by Worulz** [comment]
@978749951 refer to this thread. 

https://github.com/jwyang/faster-rcnn.pytorch/issues/218#issuecomment-401600163

**Comment by 978749951** [comment]
Thanks @Worulz 
Solved by referring to both #218 and # 26
