### ISSUE TITLE
Pytorch 0.4.0

### ISSUE THREAD

**Issue by yudawen** [jwyang/faster-rcnn.pytorch#261]
Could you make your code run in pytorch ? It's difficult for me,Could you hlep me? @jwyang

**Comment by adityaarun1** [comment]
Hi,

I have a working fork which reproduces results on PyTorch 0.4.0 [[here](https://github.com/adityaarun1/faster-rcnn.pytorch)]

@jwyang can we have a separate 0.4.0 specific branch at this repo? I can submit a pull request.

**Comment by jwyang** [comment]
@adityaarun1 that's great! i will create another branch for PyTorch 0.4.0. Sorry to respond lately.

**Comment by jwyang** [comment]
@adityaarun1 i have created a 0.4.0 branch.

**Comment by jwyang** [comment]
now the master supports pytorch-0.4.0
