### ISSUE TITLE
Change from BGR to RGB or from RGB to BGR  when I using pretrained model?

### ISSUE THREAD

**Issue by Sucran** [jwyang/faster-rcnn.pytorch#263]

**Comment by Sucran** [comment]
In README, that describe as from BGR to RGB, but it is weird for ImageNet pretrained model.

**Comment by adamklec** [comment]
I could use some clarification on the RGB/BGR issue as well. Is the issue that the pre-trained models (resnet, vgg, etc.) were trained with the color channels ordered BGR, so in order to use these models we need to convert RGB images to BGR?

**Comment by adamklec** [comment]
Nevermind. I believe my question was answered in #10 .

**Comment by Sucran** [comment]
@adamklec Thank you for pointing the same issue #10 for me, I have read it and I think the author of this repo had answered the issue, so I close this issue.
