### ISSUE TITLE
What datasets were the Pretrained models trained on?

### ISSUE THREAD

**Issue by Chumbyte** [jwyang/faster-rcnn.pytorch#269]
Hi, I am using the ResNet 101 pretrained model given in [this repository](https://github.com/jwyang/faster-rcnn.pytorch#pretrained-model). I was wondering what datasets that model were trained on, so that I do not do any testing on those datasets.

Thanks!

**Comment by ChangyouGUO** [comment]
@Chumbyte Hi, I think this pretrained model is trained by the classification dataset. After you donwload it, you need to train faster-rcnn model on detection datasets.  
If you want to test faster-rcnn right now, you can download the models in benchmarking table.
