### ISSUE TITLE
Use nms_gpu without sort at first

### ISSUE THREAD

**Issue by WHCer** [jwyang/faster-rcnn.pytorch#272]
https://github.com/jwyang/faster-rcnn.pytorch/blob/28db6d0b313220d200b739f4e22410fbe35529f4/lib/model/nms/nms_gpu.py#L7-L12

Note nms_cuda() function needs sorted boxes by scores. The implementation here lost it. Please refer to nms_gpu.pyx in faster-rcnn-py.

**Comment by Worulz** [comment]
@WHCer during execution of the demo.py script. it does include the ordering.
