### ISSUE TITLE
BBOX size in demo.py

### ISSUE THREAD

**Issue by siminchai** [jwyang/faster-rcnn.pytorch#273]
Hi,

I set the anchor size in traincal_net.py to be small, like 8X8, 16X16, but when I run the demo.py, the bounding box is still as large as 256*256. I couldn't find where to adjust this in the demo.py file. Does anyone know? 

Thanksssss!

**Comment by jwyang** [comment]
@siminchai anchor size is not setting the size of object bounding box.
