### ISSUE TITLE
when I run make.sh, I got this problem?

### ISSUE THREAD

**Issue by RobotIntelligence** [jwyang/faster-rcnn.pytorch#275]
/lib/model/roi_crop/src/roi_crop.c:10:30: error: dereferencing pointer to incomplete type ‘THFloatTensor {aka struct THFloatTensor}’

Thanks

**Comment by DerekDLP** [comment]
@RobotIntelligence  I am facing the same issue. Have you solved this issue?
/code/lib/model/nms/src/nms_cuda.c: In function 'nms_cuda':
/code/lib/model/nms/src/nms_cuda.c:14:22: error: dereferencing pointer to incomplete type 'THTensor {aka struct THTensor}'
            boxes_host->size[0],

**Comment by jwyang** [comment]
@RobotIntelligence are you using pytorch-0.4.0. Unfortunately, now this repo does not support 0.4.0, but others and me have been trying to transfer it to pytorch-0.4.0. I have created another branch, and please stay tunned.
