### ISSUE TITLE
cannot import name 'lib' and 'ffi'

### ISSUE THREAD

**Issue by yurynamgung** [jwyang/faster-rcnn.pytorch#280]
running faster_rcnn.py, I faced this error. 

Traceback (most recent call last):
  File "/Users/yurynamgung/Dropbox/programs/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 13, in <module>
    from lib.model.rpn.rpn import _RPN
  File "/Users/yurynamgung/Dropbox/programs/faster-rcnn.pytorch/lib/model/rpn/rpn.py", line 10, in <module>
    from lib.model.utils.net_utils import _smooth_l1_loss
  File "/Users/yurynamgung/Dropbox/programs/faster-rcnn.pytorch/lib/model/utils/net_utils.py", line 8, in <module>
    from lib.model.roi_crop.functions.roi_crop import RoICropFunction
  File "/Users/yurynamgung/Dropbox/programs/faster-rcnn.pytorch/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/Users/yurynamgung/Dropbox/programs/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from lib.model.roi_crop import lib as _lib, ffi as _ffi
ImportError: cannot import name 'lib'

it cannot import ffi either (it cannot find the reference to lib or ffi in __init__.py)

i had to change the import line "from _roi_crop import lib as _lib, ffi as _ffi" to "from lib.model.roi_crop ..." because I would get a ModuleNotFound error. 

any help would be greatly appreciated!

**Comment by yurynamgung** [comment]
for the moment, i changed the line to be
import lib as _lib
import cffi as _ffi

this got rid of the errors - i'm not sure if this code would do as it intended

**Comment by jwyang** [comment]
@yurynamgung did you run sh make.sh in lib to compile roi_crop?

**Comment by yurynamgung** [comment]
I just tried this, but I got the following error:

-bash: cd: PycharmProjects/pytorch-faster-rcnn-master/lib/make.sh: Not a directory
Yurys-MacBook-Air:Dropbox yurynamgung$ cd PycharmProjects/pytorch-faster-rcnn-master/lib
Yurys-MacBook-Air:lib yurynamgung$ sh make.sh
Compiling roi_pooling kernels by nvcc...
make.sh: line 12: nvcc: command not found
/Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/layer_utils/roi_pooling
generating /var/folders/h_/zfsm4hzn4gvfpzmqq5knct040000gn/T/tmpb_2ggt9h/_roi_pooling.c
running build_ext
building '_roi_pooling' extension
creating Users
creating Users/yurynamgung
creating Users/yurynamgung/Dropbox
creating Users/yurynamgung/Dropbox/PycharmProjects
creating Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master
creating Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib
creating Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/layer_utils
creating Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/layer_utils/roi_pooling
creating Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/layer_utils/roi_pooling/src
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/yurynamgung/anaconda/include -arch x86_64 -I/Users/yurynamgung/anaconda/include -arch x86_64 -I/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/Users/yurynamgung/anaconda/include/python3.6m -c _roi_pooling.c -o ./_roi_pooling.o
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/yurynamgung/anaconda/include -arch x86_64 -I/Users/yurynamgung/anaconda/include -arch x86_64 -I/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/Users/yurynamgung/anaconda/include/python3.6m -c /Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/layer_utils/roi_pooling/src/roi_pooling.c -o ./Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/layer_utils/roi_pooling/src/roi_pooling.o
gcc -bundle -undefined dynamic_lookup -L/Users/yurynamgung/anaconda/lib -L/Users/yurynamgung/anaconda/lib -arch x86_64 ./_roi_pooling.o ./Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/layer_utils/roi_pooling/src/roi_pooling.o /Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/layer_utils/roi_pooling/src/cuda/roi_pooling_kernel.cu.o -L/Users/yurynamgung/anaconda/lib -o ./_roi_pooling.so
clang: error: no such file or directory: '/Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/layer_utils/roi_pooling/src/cuda/roi_pooling_kernel.cu.o'
Traceback (most recent call last):
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yurynamgung/anaconda/lib/python3.6/site-packages/cffi/ffiplatform.py", line 49, in _build
    dist.run_command('build_ext')
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 34, in <module>
    ffi.build()
  File "/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/Users/yurynamgung/anaconda/lib/python3.6/site-packages/cffi/api.py", line 684, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/Users/yurynamgung/anaconda/lib/python3.6/site-packages/cffi/recompiler.py", line 1484, in recompile
    compiler_verbose, debug)
  File "/Users/yurynamgung/anaconda/lib/python3.6/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/Users/yurynamgung/anaconda/lib/python3.6/site-packages/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1
Compiling crop_and_resize kernels by nvcc...
make.sh: line 20: nvcc: command not found
/Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/layer_utils/roi_align
generating /var/folders/h_/zfsm4hzn4gvfpzmqq5knct040000gn/T/tmpf_dizotn/_crop_and_resize.c
running build_ext
building '_crop_and_resize' extension
creating Users
creating Users/yurynamgung
creating Users/yurynamgung/Dropbox
creating Users/yurynamgung/Dropbox/PycharmProjects
creating Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master
creating Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib
creating Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/layer_utils
creating Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/layer_utils/roi_align
creating Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/layer_utils/roi_align/src
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/yurynamgung/anaconda/include -arch x86_64 -I/Users/yurynamgung/anaconda/include -arch x86_64 -I/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/Users/yurynamgung/anaconda/include/python3.6m -c _crop_and_resize.c -o ./_crop_and_resize.o -std=c99
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/yurynamgung/anaconda/include -arch x86_64 -I/Users/yurynamgung/anaconda/include -arch x86_64 -I/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/Users/yurynamgung/anaconda/include/python3.6m -c /Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/layer_utils/roi_align/src/crop_and_resize.c -o ./Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/layer_utils/roi_align/src/crop_and_resize.o -std=c99
gcc -bundle -undefined dynamic_lookup -L/Users/yurynamgung/anaconda/lib -L/Users/yurynamgung/anaconda/lib -arch x86_64 ./_crop_and_resize.o ./Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/layer_utils/roi_align/src/crop_and_resize.o -L/Users/yurynamgung/anaconda/lib -o ./_crop_and_resize.so
Compiling nms kernels by nvcc...
make.sh: line 28: nvcc: command not found
/Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/nms
generating /var/folders/h_/zfsm4hzn4gvfpzmqq5knct040000gn/T/tmpro2t8nrm/_nms.c
running build_ext
building '_nms' extension
creating Users
creating Users/yurynamgung
creating Users/yurynamgung/Dropbox
creating Users/yurynamgung/Dropbox/PycharmProjects
creating Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master
creating Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib
creating Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/nms
creating Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/nms/src
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/yurynamgung/anaconda/include -arch x86_64 -I/Users/yurynamgung/anaconda/include -arch x86_64 -I/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/Users/yurynamgung/anaconda/include/python3.6m -c _nms.c -o ./_nms.o
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/yurynamgung/anaconda/include -arch x86_64 -I/Users/yurynamgung/anaconda/include -arch x86_64 -I/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/Users/yurynamgung/anaconda/include/python3.6m -c /Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/nms/src/nms.c -o ./Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/nms/src/nms.o
/Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/nms/src/nms.c:7:42: warning: 
      incompatible pointer types passing 'THFloatTensor *' (aka
      'struct THFloatTensor *') to parameter of type 'const THLongTensor *' (aka
      'const struct THLongTensor *') [-Wincompatible-pointer-types]
    THArgCheck(THLongTensor_isContiguous(boxes), 2, "boxes must be contiguous");
                                         ^~~~~
/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGeneral.h:100:35: note: 
      expanded from macro 'THArgCheck'
  _THArgCheck(__FILE__, __LINE__, __VA_ARGS__);                       \
                                  ^~~~~~~~~~~
/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:114:52: note: 
      passing argument to parameter 'self' here
TH_API int THTensor_(isContiguous)(const THTensor *self);
                                                   ^
/Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/nms/src/nms.c:9:42: warning: 
      incompatible pointer types passing 'THFloatTensor *' (aka
      'struct THFloatTensor *') to parameter of type 'const THLongTensor *' (aka
      'const struct THLongTensor *') [-Wincompatible-pointer-types]
    THArgCheck(THLongTensor_isContiguous(areas), 4, "areas must be contiguous");
                                         ^~~~~
/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/THGeneral.h:100:35: note: 
      expanded from macro 'THArgCheck'
  _THArgCheck(__FILE__, __LINE__, __VA_ARGS__);                       \
                                  ^~~~~~~~~~~
/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH/generic/THTensor.h:114:52: note: 
      passing argument to parameter 'self' here
TH_API int THTensor_(isContiguous)(const THTensor *self);
                                                   ^
/Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/nms/src/nms.c:14:12: warning: 
      incompatible pointer types initializing 'long *' with an expression of
      type 'int64_t *' (aka 'long long *') [-Wincompatible-pointer-types]
    long * keep_out_flat = THLongTensor_data(keep_out);
           ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/nms/src/nms.c:16:12: warning: 
      incompatible pointer types initializing 'long *' with an expression of
      type 'int64_t *' (aka 'long long *') [-Wincompatible-pointer-types]
    long * order_flat = THLongTensor_data(order);
           ^            ~~~~~~~~~~~~~~~~~~~~~~~~
/Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/nms/src/nms.c:65:11: warning: 
      incompatible pointer types initializing 'long *' with an expression of
      type 'int64_t *' (aka 'long long *') [-Wincompatible-pointer-types]
    long *num_out_flat = THLongTensor_data(num_out);
          ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~
5 warnings generated.
gcc -bundle -undefined dynamic_lookup -L/Users/yurynamgung/anaconda/lib -L/Users/yurynamgung/anaconda/lib -arch x86_64 ./_nms.o ./Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/nms/src/nms.o /Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/nms/src/cuda/nms_kernel.cu.o -L/Users/yurynamgung/anaconda/lib -o ./_nms.so
clang: error: no such file or directory: '/Users/yurynamgung/Dropbox/PycharmProjects/pytorch-faster-rcnn-master/lib/nms/src/cuda/nms_kernel.cu.o'
Traceback (most recent call last):
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yurynamgung/anaconda/lib/python3.6/site-packages/cffi/ffiplatform.py", line 49, in _build
    dist.run_command('build_ext')
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/Users/yurynamgung/anaconda/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 34, in <module>
    ffi.build()
  File "/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/Users/yurynamgung/anaconda/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/Users/yurynamgung/anaconda/lib/python3.6/site-packages/cffi/api.py", line 684, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/Users/yurynamgung/anaconda/lib/python3.6/site-packages/cffi/recompiler.py", line 1484, in recompile
    compiler_verbose, debug)
  File "/Users/yurynamgung/anaconda/lib/python3.6/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/Users/yurynamgung/anaconda/lib/python3.6/site-packages/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1
Yurys-MacBook-Air:lib yurynamgung$

**Comment by yurynamgung** [comment]
i think one of the errors might stem from the fact that i can't run cuda on my device - is there a way to get around that?

**Comment by jwyang** [comment]
@yurynamgung now it can merely compile with cuda.
