### ISSUE TITLE
why demo.py and test_net.py make different results

### ISSUE THREAD

**Issue by Gr1tee** [jwyang/faster-rcnn.pytorch#282]
the same picture have different detect result using demo.py and test_net.py,why?

**Comment by Worulz** [comment]
@Gr1tee can you show us an example?

**Comment by jrcai** [comment]
Same here. Loaded the same model and the same video, but got different outputs. The test_net.py results seem more reasonable. I was wondering if the image loading is different?

**Comment by jrcai** [comment]
I solved this by **calling _get_image_blob before the rgb -> bgr conversion**.
https://github.com/jwyang/faster-rcnn.pytorch/blob/31ae20687b1b3486155809a57eeb376259a5f5d4/demo.py#L274

Hope this helps!!

**Comment by GSteinberg** [comment]
@jrcai thank you so much. I've been trying to figure out this problem for months.
