### ISSUE TITLE
Remove files generated by cython

### ISSUE THREAD

**Issue by ahmed-shariff** [jwyang/faster-rcnn.pytorch#285]
The following files are generated by cython, remove them?
lib/model/utils/bbox.c
lib/pycocotools/_mask.c

These files were causing problems when running the make.sh script in python 3.7

**Comment by jwyang** [comment]
@ahmed-shariff thanks for your pull request, but these two files are necessary in the current version. what's wrong with the compilation? I will try to compile them on python 3.6.

**Comment by jwyang** [comment]
@ahmed-shariff i think this already worked previously, but I just run sh make.sh with python-3.6, and the code worked fine. please let me know the exact error you got on your side.
