### ISSUE TITLE
what does the ''MAX_NUM_GT_BOXES = 20" mean？

### ISSUE THREAD

**Issue by Duankaiwwen** [jwyang/faster-rcnn.pytorch#291]
There are several lines of code in the roibatchLoader.py
...
self.max_num_box = cfg.**MAX_NUM_GT_BOXES**
...
if keep.numel() != 0:
            gt_boxes = gt_boxes[keep]
            num_boxes = min(gt_boxes.size(0), **self.max_num_box**)
            gt_boxes_padding[:num_boxes,:] = gt_boxes[:num_boxes]
....
Why do you limit the number of gt_boxes？ If there are 30 objects in an image, but the number of gt_boxes is only 20, so how to explain this?

@severian @jnhwkim @temerick @cclauss @jwyang

**Comment by jwyang** [comment]
@Duankaiwwen since we are training the model with batch, we do not want too much images have many zero-padding on the boxes to reduce the computation cost, so we set the maximal number of bounding boxes to 20 according to the statistics.

**Comment by Duankaiwwen** [comment]
Many thanks!
