### ISSUE TITLE
performace on coco2014

### ISSUE THREAD

**Issue by Ricardozzf** [jwyang/faster-rcnn.pytorch#295]
Thanks for you repo,  its very  useful to help me understand some details of faster rcnn.
I retrain resnet101 on COCO (Train/Test: coco_train+coco_val-minival/minival, scale=800, max_size=1200, ROI Align)
![image](https://user-images.githubusercontent.com/30193946/45149630-a0a76500-b1fc-11e8-8d87-02355feee8ec.png)
I use the hyper parameters u list in table (batch_size:16   lr:1e-2   decay_step:4   max_epoch:10), the only difference is that i use 4 TITAN X(PASCAL)
In testing, my model only reach 0.304(0.5:0.95), its much worse than your model 37.0
![image](https://user-images.githubusercontent.com/30193946/45149995-71452800-b1fd-11e8-8fee-cf6d5ccf04e6.png)
Im very confused about this, could u please offer some details that u train the mode?

**Comment by jwyang** [comment]
@Ricardozzf did you test our model on your side? you could get the right numbers, right? If that's true, I think it might because you did not use pre-trained res101 or the right pre-trained res101 model?

**Comment by WangTianYuan** [comment]
@Ricardozzf hi, I want to train the model on COCO too, but I don't know how to prepare the dataset, I've got the .zip file on http://cocodataset.org/#download, what should I do next? put the .zip file to the data/ ?
I'am confused by the instructions in https://github.com/rbgirshick/py-faster-rcnn#beyond-the-demo-installation-for-training-and-testing-models

**Comment by Ricardozzf** [comment]
@WangTianYuan If you want to use coco dataset, you should read rbgirshick/py-faster-rcnn/data/README.md which tell you how to prepare dataset.
