### ISSUE TITLE
I think you nms.py have something wrong

### ISSUE THREAD

**Issue by lingtengqiu** [jwyang/faster-rcnn.pytorch#298]
IN YOUR py you write
def nms_cpu(dets, thresh): 
    #keep_idx_i = nms(torch.cat((proposals_single, scores_single), 1), nms_thresh, force_cpu=not cfg.USE_GPU_NMS)
    # proposal_single 9*h*w,4 --->after regressor and crop , (x1,y1,x2,y2) , and then score map 
    dets = dets.numpy()
    x1 = dets[:, 0]
    y1 = dets[:, 1]
    x2 = dets[:, 2]
    y2 = dets[:, 3]
    scores = dets[:, 4]

    areas = (x2 - x1 + 1) * (y2 - y1 + 1)
    #descending order
    order = scores.argsort()[::-1]

    keep = []
    while order.size > 0:
        i = order.item(0)
        keep.append(i)
        # here we get compare the max score anchor we get the bigger xx1,yy1,xx2,yy2 
        xx1 = np.maximum(x1[i], x1[order[1:]])
        yy1 = np.maximum(y1[i], y1[order[1:]])
        xx2 = np.maximum(x2[i], x2[order[1:]])
        yy2 = np.maximum(y2[i], y2[order[1:]])
        w = np.maximum(0.0, xx2 - xx1 + 1)
        h = np.maximum(0.0, yy2 - yy1 + 1)
        but I think xx2 = np.minimum(xx2[i], xx2[order[1:]])
        yy1 = np.minimum(yy2[i],yy2[order1[:]])
        right???

**Comment by jwyang** [comment]
@lingtengqiu yes, you are right, thanks for pointing out this, I have fixed this bug.
