### ISSUE TITLE
fasterRCNN.load_state_dict(checkpoint['model'])

### ISSUE THREAD

**Issue by sdhnshu** [jwyang/faster-rcnn.pytorch#30]
I used the vgg16_caffe.pth mentioned in the readme and tried to use demo.py and test.py. Both of them gave an issue as `KeyError: 'model'`. I printed the checkpoint file and it had weights. I couldn't find any model or pooling_mode keys
Am I using the right checkpoint file?

Printing `checkpoint.keys()` gives
`[u'features.0.weight', u'features.0.bias', u'features.2.weight', u'features.2.bias', u'features.5.weight', u'features.5.bias', u'features.7.weight', u'features.7.bias', u'features.10.weight', u'features.10.bias', u'features.12.weight', u'features.12.bias', u'features.14.weight', u'features.14.bias', u'features.17.weight', u'features.17.bias', u'features.19.weight', u'features.19.bias', u'features.21.weight', u'features.21.bias', u'features.24.weight', u'features.24.bias', u'features.26.weight', u'features.26.bias', u'features.28.weight', u'features.28.bias', u'classifier.6.weight', u'classifier.6.bias', 'classifier.0.weight', 'classifier.0.bias', 'classifier.3.weight', 'classifier.3.bias']`

**Comment by jwyang** [comment]
hi, @sdhnshu , which preprinted model did you use? I might provide a link to an earlier model. I will check that

**Comment by jwyang** [comment]
@sdhnshu , I already updated the models, you can download any from the links, several models missed will be available soon.

**Comment by pinkfloyd06** [comment]
Hi @jwyang , @sdhnshu 

I face the same problem 
https://github.com/jwyang/faster-rcnn.pytorch/blob/master/demo.py#L194
while loading resnet101 caffe pretrained model https://github.com/jwyang/faster-rcnn.pytorch#pretrained-model

l'm using python2.7 and  pytorch 0.4.0

l didn't change anything :  
python demo.py --net res101 \
               --checksession $SESSION --checkepoch $EPOCH --checkpoint $CHECKPOINT \
               --cuda --load_dir  /data/pretrained_model/

Thank you

**Comment by xwjBupt** [comment]
Hi @jwyang , @sdhnshu,
i meet the same problem,i download the vgg16 pretrained model from the link in the readme,but when i load the model,i found the model do not the 'model' key ,it has :

odict_keys(['features.0.weight', 'features.0.bias', 'features.2.weight', 'features.2.bias', 'features.5.weight', 'features.5.bias', 'features.7.weight', 'features.7.bias', 'features.10.weight', 'features.10.bias', 'features.12.weight', 'features.12.bias', 'features.14.weight', 'features.14.bias', 'features.17.weight', 'features.17.bias', 'features.19.weight', 'features.19.bias', 'features.21.weight', 'features.21.bias', 'features.24.weight', 'features.24.bias', 'features.26.weight', 'features.26.bias', 'features.28.weight', 'features.28.bias', 'classifier.6.weight', 'classifier.6.bias', 'classifier.0.weight', 'classifier.0.bias', 'classifier.3.weight', 'classifier.3.bias'])

where is the [model]? have i done something wrong?
Thank you!
