### ISSUE TITLE
sh make.sh error

### ISSUE THREAD

**Issue by HURB** [jwyang/faster-rcnn.pytorch#302]
when I compiler the make.sh----‘sh make.sh', I got the error:
Compiling nms kernels by nvcc...
cffi.error.CDFError: parse error <cdef source string>31:1: Illegal character '\r'
Compiling roi pooling kernels by nvcc..
cffi.error.CDefError: cannot parse "int roi_pooling_forward(int pooled_height, int pooled_width, float spatial_scale," <cdef source string>29:82 Illegal character '\r'
and "Compiling roi align kernels " has the same error

Thanks!

**Comment by HURB** [comment]
the error is like that

**Comment by WangTianYuan** [comment]
@HURB hey, I've got the same problem, have you solved it? How? thanks

**Comment by HURB** [comment]
@WangTianYuan not yet ,   I still have the problem 。。。

**Comment by jwyang** [comment]
@HURB which version of pytorch are you using?
