### ISSUE TITLE
Could it become a library?

### ISSUE THREAD

**Issue by fernandocamargoti** [jwyang/faster-rcnn.pytorch#304]
I mean, I wish I could install it (with pip or conda), create my own Dataset and use this Faster RCNN implementation with no need to fork it, build it and so on. Just like we have Modules in PyTorch, it would be nice to have this implementation as a library that I could use in my own Modules.

**Comment by jwyang** [comment]
@fernandocamargoti that's a good idea! do you have any more specific suggestions?

**Comment by fernandocamargoti** [comment]
Well, I don't know enough of this implementation, but I guess we could update the build to be able to upload to PyPi.

I noticed almost no implementation of object detection available in the Github can be installed and use as a library. The single one I've found is this: https://github.com/fizyr/keras-retinanet
It may be a good example to be followed, even though it targets Keras.
