### ISSUE TITLE
COCO训练出的结果提交问题

### ISSUE THREAD

**Issue by dongfengxijian** [jwyang/faster-rcnn.pytorch#306]
你好，我测试了COCO的结果，但是提交时一直Failed，文件名为detections_val2017_FCN_results.json，想请教一下原因

**Comment by jwyang** [comment]
@dongfengxijian 你对比一下提交格式有问题吗？

**Comment by dongfengxijian** [comment]
[{"image_id": 397133, "category_id": 1, "bbox": [380.20751953125, 69.31391906738281, 120.1015625, 283.29856872558594], "score": 0.9973235726356506}, {"image_id": 397133, "category_id": 1, "bbox": [398.22760009765625, 72.06139373779297, 106.099365234375, 125.36243438720703], "score": 0.14173923432826996}, {"image_id": 397133, "category_id": 1, "bbox": [2.649695873260498, 261.5930480957031, 58.776222705841064, 43.53643798828125], "score": 0.12416626513004303}, {"image_id": 397133, "category_id": 1, "bbox": [333.01031494140625, 107.14978790283203, 87.67144775390625, 250.3971176147461], "score": 0.11007023602724075}, {"image_id": 397133, "category_id": 1, "bbox": [423.62030029296875, 69.23391723632812, 75.49053955078125, 71.67503356933594], "score": 0.10776981711387634}, {"image_id": 397133, "category_id": 1, "bbox": [463.49554443359375, 78.10821533203125, 48.63604736328125, 95.64306640625], "score": 0.10547707229852676}, {"image_id": 397133, "category_id": 1, "bbox": [453.9451904296875, 76.86235809326172, 26.357940673828125, 34.772430419921875], "score": 0.08808989077806473}, {"image_id": 397133, "category_id": 1, "bbox": [433.9125061035156, 72.18251037597656, 40.36114501953125, 40.94434356689453], "score": 0.08647135645151138}, {"image_id": 397133, "category_id": 1, "bbox": [356.30499267578125, 91.51761627197266, 52.83538818359375, 125.84520721435547], "score": 0.07957068085670471}, {"image_id": 397133, "category_id": 1, "bbox": [-2.0514631271362305, 222.3922576904297, 66.8546781539917, 85.25697326660156], "score": 0.06695768982172012}, {"image_id": 397133, "category_id": 1, "bbox": [464.763427734375, 99.38301086425781, 16.042816162109375, 20.59552001953125], "score": 0.06415040791034698}, {"image_id": 252219, "category_id": 1, "bbox": [506.8896484375, 167.9635009765625, 129.01959228515625, 217.454833984375], "score": 0.9988328814506531}, {"image_id": 252219, "category_id": 1, "bbox": [9.757962226867676, 165.30003356933594, 127.59219646453857, 231.5192108154297], "score": 0.6997313499450684}]
@jwyang 我提交的json内容是这样的， 格式应该满足要求

**Comment by jwyang** [comment]
@dongfengxijian did you get any failure info when submitting the results?

**Comment by dongfengxijian** [comment]
@jwyang 有其他联系方式吗？这个传不了图片

**Comment by dongfengxijian** [comment]
@jwyang 
![image](https://user-images.githubusercontent.com/24863806/45522092-92a4a600-b7f3-11e8-9638-bc414059d856.png)

**Comment by dongfengxijian** [comment]
对了，我用的360浏览器不知道有没有关系

**Comment by jwyang** [comment]
@dongfengxijian 这应该不是格式的问题，你试试其他浏览器，或者以前能够提交的版本。

**Comment by dongfengxijian** [comment]
换了Chrome浏览器，还是报错

**Comment by dongfengxijian** [comment]
@jwyang 好像和传输文件的大小有关，你有没有试过

**Comment by jwyang** [comment]
@dongfengxijian 我没有试过额

**Comment by dongfengxijian** [comment]
@jwyang 好吧，还是谢谢了。我以为你上传过。
