### ISSUE TITLE
Alternating training

### ISSUE THREAD

**Issue by dragonfly90** [jwyang/faster-rcnn.pytorch#307]
Is it possible to alternating training on this repo?

**Comment by dragonfly90** [comment]
In the original paper,  we could first train RPN, and use the proposals to train Fast R-CNN. The network tuned by Fast R-CNN is then used to initialize RPN, and this process is iterated. I think your implementation is end-to-end training, could I try this alternating?

**Comment by jwyang** [comment]
@dragonfly90 yes, you can do that to alternate rpn loss and faster r-cnn loss during the training.
