### ISSUE TITLE
Wrong dataset path

### ISSUE THREAD

**Issue by kentsyx** [jwyang/faster-rcnn.pytorch#31]
A little confused about how to set a proper dataset path, say I want to use VOC 2012 in this case. 
This faster rcnn repopsitory is placed at
```bash
/home/yxshi/faster-rcnn.pytorch
```
and voc 2012 dataset is placed at 
```bash
/home/yxshi/VOCdevkit
```
and it has a structure like
```bash
VOCdevkit/
VOCdevkit/VOC2012
VOCdevkit/VOC2012/Annotations
VOCdevkit/VOC2012/...
```
I followed [this thread](https://github.com/rbgirshick/py-faster-rcnn#beyond-the-demo-installation-for-training-and-testing-models) to create symlinks from $faster-rcnn.pytorch/data
```bash
ln -s /home/yxshi/VOCdevkit VOCdevkit2012
```
and also I changed year '2007' to '2012' in pascal_voc.py, but when I run trainval_net.py it always throws 
```
AssertionError: Path does not exist: /home/shiyx/faster-rcnn.pytorch/data/VOCdevkit2007/VOC2007/ImageSets/Main/trainval.txt
```
I'm not sure what went wrong, any suggestions?

**Comment by jwyang** [comment]
Hi, @kentsyx , did you check the path "/home/shiyx/faster-rcnn.pytorch/data/VOCdevkit2007/VOC2007/ImageSets/Main/trainval.txt" exist or not?

**Comment by ArchieGu** [comment]
@kentsyx  Did you solve the issue? I have ran into the same problem and don't know how to solve it.
If you know the answer, please help me.
Thank you.

**Comment by YWMSAMA** [comment]
@ArchieGu I have solved the problem. You can get trainval.txt, test.txt, train.txt and val.txt through the codes as follow. 

import os
import random 
 
xmlfilepath=r'/root/code/faster-rcnn.pytorch/data/VOCdevkit2007/VOC2007/Annotations'
saveBasePath=r"/root/code/faster-rcnn.pytorch/data/VOCdevkit2007/VOC2007/ImageSets/Main/"
 
trainval_percent=0.5
train_percent=0.5
total_xml = os.listdir(xmlfilepath)
num=len(total_xml)  
list=range(num)  
tv=int(num*trainval_percent)  
tr=int(tv*train_percent)  
trainval= random.sample(list,tv)  
train=random.sample(trainval,tr)  
 
print("train and val size",tv)
print("traub suze",tr)
ftrainval = open(os.path.join(saveBasePath,'trainval.txt'), 'w')  
ftest = open(os.path.join(saveBasePath,'test.txt'), 'w')  
ftrain = open(os.path.join(saveBasePath,'train.txt'), 'w')  
fval = open(os.path.join(saveBasePath,'val.txt'), 'w')  
 
for i  in list:  
    name=total_xml[i][:-4]+'\n'  
    if i in trainval:  
        ftrainval.write(name)  
        if i in train:  
            ftrain.write(name)  
        else:  
            fval.write(name)  
    else:  
        ftest.write(name)  
  
ftrainval.close()  
ftrain.close()  
fval.close()  
ftest .close()
