### ISSUE TITLE
KeyError: 'model'

### ISSUE THREAD

**Issue by 21dmohan** [jwyang/faster-rcnn.pytorch#310]
I am having some troubles running the [demo](https://github.com/jwyang/faster-rcnn.pytorch#demo). I am currently using the command: 

`python demo.py --net vgg16 --checksession 1 --checkepoch 6 --checkpoint 416 --cuda --load_dir data/pretrained_model` 

I've renamed the [pre-trained model](https://github.com/jwyang/faster-rcnn.pytorch#pretrained-model) 'vgg16_caffe.pth' to 'faster_rcnn_1_6_416.pth' accordingly (and moved it to the appropriate folder), so the code is able to find the model. However, I get the following error: 

Traceback (most recent call last):
  File "demo.py", line 194, in <module>
    fasterRCNN.load_state_dict(checkpoint['model']) 
KeyError: 'model'

![screenshot from 2018-09-17 10-21-28](https://user-images.githubusercontent.com/35504030/45638927-79a22c00-ba63-11e8-9898-9b95961cc808.png)

Any help would be greatly appreciated! Thank you in advanced :)

**Comment by jwyang** [comment]
@21dmohan you are using the wrong model. vgg16_caffe.pth is the pretrained imagenet model, Please download the models using the links in the table.
