### ISSUE TITLE
test error on visual genome

### ISSUE THREAD

**Issue by JerryC123** [jwyang/faster-rcnn.pytorch#316]
I run test_net.py on pre-trained visual genome dataset and at last it break down.

python test_net.py --dataset vg --net vgg16 \
                   --checksession 1 --checkepoch 19 --checkpoint 48611 \
                   --cuda

VOC07 metric? No
vg_2500-1000-500_val gt roidb loaded from /data1/zyd/faster-rcnn.pytorch/data/cache/vg_2500-1000-500_val_gt_roidb.pkl
/data1/zyd/faster-rcnn.pytorch/lib/datasets/vg.py:362: RuntimeWarning: invalid value encountered in divide
  f = np.nan_to_num((prec*rec)/(prec+rec))
AP for water tank = 0.0000 (npos=4)
Traceback (most recent call last):
  File "test_net.py", line 324, in <module>
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/data1/zyd/faster-rcnn.pytorch/lib/datasets/vg.py", line 294, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/data1/zyd/faster-rcnn.pytorch/lib/datasets/vg.py", line 371, in _do_python_eval
    pickle.dump({'rec': rec, 'prec': prec, 'ap': ap,
AttributeError: 'bool' object has no attribute 'dump'

How can I fix this problem?
Thank you very much!

**Comment by yzhq97** [comment]
I encountered the same problem, could you please tell me how you solved this?

**Comment by CharlotteG95** [comment]
Sorry was a fix found for this error?

**Comment by HS-YN** [comment]
Little modification of `_do_python_eval` function in `/lib/datasets/vg.py` would resolve that error. It seems that `pickle` is assigned `True` by default.
(line 336) from
> def _do_python_eval(self, output_dir, pickle=True, eval_attributes = False):

to
>def _do_python_eval(self, output_dir, use_pickle=True, eval_attributes = False):

and (line 369) from
> if pickle:

to
> if use_pickle:
