### ISSUE TITLE
Two undefined names

### ISSUE THREAD

**Issue by cclauss** [jwyang/faster-rcnn.pytorch#32]
flake8 testing of https://github.com/jwyang/faster-rcnn.pytorch on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./lib/setup.py:92:48: F821 undefined name 'CUDA'
            self.set_executable('compiler_so', CUDA['nvcc'])
                                               ^
./lib/model/roi_crop/modules/gridgen.py:39:18: F821 undefined name 'CylinderGridGenFunction'
        self.f = CylinderGridGenFunction(self.height, self.width, lr=lr)
                 ^
2     F821 undefined name 'CUDA'
```

**Comment by jwyang** [comment]
@cclauss , appreciate much for your work! I will address this issues.

**Comment by cclauss** [comment]
https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/setup.py#L27-L60 is all commented out but would seem to define __CUDA__ as a dict with a 'nvcc' key.

__CylinderGridGenFunction()__ seems to be defined in other repos but not in this one.
* https://github.com/search?p=1&q=CylinderGridGenFunction&type=Code&utf8=%E2%9C%93
