### ISSUE TITLE
No module named 'model.roi_crop._ext.roi_crop._roi_crop'

### ISSUE THREAD

**Issue by DebasmitaGhose** [jwyang/faster-rcnn.pytorch#324]
I am getting this error. 
```
(C:\Users\User\Anaconda3) C:\Users\User\Documents\UMass Amherst\Semester 3\Independent Study\Code\Multimodal_Influenza_Detection\faster-rcnn.pytorch>python trainval_net.py --dataset='kaist'
Traceback (most recent call last):
  File "trainval_net.py", line 30, in <module>
    from model.utils.net_utils import weights_normal_init, save_net, load_net, adjust_learning_rate, save_checkpoint, clip_gradient
  File "C:\Users\User\Documents\UMass Amherst\Semester 3\Independent Study\Code\Multimodal_Influenza_Detection\faster-rcnn.pytorch\lib\model\utils\net_utils.py", line 8, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "C:\Users\User\Documents\UMass Amherst\Semester 3\Independent Study\Code\Multimodal_Influenza_Detection\faster-rcnn.pytorch\lib\model\roi_crop\functions\roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "C:\Users\User\Documents\UMass Amherst\Semester 3\Independent Study\Code\Multimodal_Influenza_Detection\faster-rcnn.pytorch\lib\model\roi_crop\_ext\roi_crop\__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'model.roi_crop._ext.roi_crop._roi_crop'
```

**Comment by DebasmitaGhose** [comment]
I am not able to compile roi_crop. 
When I run `sh make.sh`, I get import errors with the following traceback

```
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
make.sh: 25: make.sh: nvcc: not found
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch
  File "/home/debasmita/anaconda2/envs/stan/lib/python2.7/site-packages/torch/__init__.py", line 78, in <module>
    from torch._C import *
ImportError: /home/debasmita/anaconda2/envs/stan/lib/python2.7/site-packages/torch/lib/../../../../libgomp.so.1: version `GOMP_4.0' not found (required by /home/debasmita/anaconda2/envs/stan/lib/python2.7/site-packages/torch/lib/libATen.so)
Compiling roi pooling kernels by nvcc...
make.sh: 35: make.sh: nvcc: not found
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch
  File "/home/debasmita/anaconda2/envs/stan/lib/python2.7/site-packages/torch/__init__.py", line 78, in <module>
    from torch._C import *
ImportError: /home/debasmita/anaconda2/envs/stan/lib/python2.7/site-packages/torch/lib/../../../../libgomp.so.1: version `GOMP_4.0' not found (required by /home/debasmita/anaconda2/envs/stan/lib/python2.7/site-packages/torch/lib/libATen.so)
Compiling roi align kernels by nvcc...
make.sh: 44: make.sh: nvcc: not found
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch
  File "/home/debasmita/anaconda2/envs/stan/lib/python2.7/site-packages/torch/__init__.py", line 78, in <module>
    from torch._C import *
ImportError: /home/debasmita/anaconda2/envs/stan/lib/python2.7/site-packages/torch/lib/../../../../libgomp.so.1: version `GOMP_4.0' not found (required by /home/debasmita/anaconda2/envs/stan/lib/python2.7/site-packages/torch/lib/libATen.so)
Compiling roi crop kernels by nvcc...
make.sh: 53: make.sh: nvcc: not found
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch
  File "/home/debasmita/anaconda2/envs/stan/lib/python2.7/site-packages/torch/__init__.py", line 78, in <module>
    from torch._C import *
ImportError: /home/debasmita/anaconda2/envs/stan/lib/python2.7/site-packages/torch/lib/../../../../libgomp.so.1: version `GOMP_4.0' not found (required by /home/debasmita/anaconda2/envs/stan/lib/python2.7/site-packages/torch/lib/libATen.so)
```
I am using Python 2.7 and PyTorch 0.4.0

**Comment by jwyang** [comment]
@DebasmitaGhose it is because NVCC is not found. Have you installed CUDA?

**Comment by banxia1994** [comment]
> @DebasmitaGhose have you successfully compiled roi_crop? Did you find the roi_crop.so?
Hi，i get the same problem, but i compile successfully,:
`
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
Compiling roi pooling kernels by nvcc...
Compiling roi align kernels by nvcc...
Compiling roi crop kernels by nvcc...
`
but  don't find the roi_crop.so,while find _roi_align.so. can you get me some suggestions

**Comment by DebasmitaGhose** [comment]
Yes, the issue was I had not installed the correct version of cuda. After installing cuda 8.0, i deleted the .so files that were created during compiling make.sh and ran make.sh again, and it worked

**Comment by lilongpu** [comment]
hi,I get the same problem,too.I have installed python2.7,pytorch0.4.1(there is no cuda for this version)and I have only cpu inside my computer ,what should I do?
any suggestion would be grated!  thanks!

**Comment by jiajunhua** [comment]
hi,I get the same problem,too.I have installed python3.6,pytorch0.4.0(there is no cuda for this version)and I have only cpu inside my computer ,what should I do?

**Comment by HwaiHo-0552** [comment]
try sh make.sh, then it may work.       
(gcc5/5.5.0 could build on my PC--Pytorch 0.4, CUDA 90, CUDNN 7.0, GPU Tesla P100)

**Comment by terryleung00** [comment]
I try to do this on google colab but face the same problem. CUDA8.0, Pytorch1.0.0,python3.7.
I could run the setup.py successfully.
![image](https://user-images.githubusercontent.com/90096118/138722525-a353e374-6022-4804-a954-cc46c18709a7.png)
But when I start training, this happens:
![image](https://user-images.githubusercontent.com/90096118/138722629-465b20d6-cbb3-43c1-8e09-456672bef50a.png)
My CUDA:
![image](https://user-images.githubusercontent.com/90096118/138722660-b4ae23d3-1241-448e-af38-d714fd640329.png)

Update:
Seems like the setup.py didn't run properly, but I didn't know how to fix it.

**Comment by yuuuuk0** [comment]
> I try to do this on google colab but face the same problem. CUDA8.0, Pytorch1.0.0,python3.7. I could run the setup.py successfully. ![image](https://user-images.githubusercontent.com/90096118/138722525-a353e374-6022-4804-a954-cc46c18709a7.png) But when I start training, this happens: ![image](https://user-images.githubusercontent.com/90096118/138722629-465b20d6-cbb3-43c1-8e09-456672bef50a.png) My CUDA: ![image](https://user-images.githubusercontent.com/90096118/138722660-b4ae23d3-1241-448e-af38-d714fd640329.png)
> 
> Update: Seems like the setup.py didn't run properly, but I didn't know how to fix it.

have you solved the problem?
