### ISSUE TITLE
torch 0.4.0

### ISSUE THREAD

**Issue by ssli23** [jwyang/faster-rcnn.pytorch#329]
I put these [two lines](https://github.com/jwyang/faster-rcnn.pytorch/blob/master/trainval_net.py#L289) before `if args.resume:`, and it works well.

_Originally posted by @ChengpengChen in https://github.com/jwyang/faster-rcnn.pytorch/issues/222#issuecomment-423958134_

**Comment by jwyang** [comment]
@ssli23 thanks! I have accepted the push request.
