### ISSUE TITLE
Supported versions of pytorch

### ISSUE THREAD

**Issue by drcege** [jwyang/faster-rcnn.pytorch#33]
Which version of pytorch this project is compatible with?

Part of the code  only runs with pytorch v0.1. For example, in these lines
https://github.com/jwyang/faster-rcnn.pytorch/blob/c12d2151baf5cba241f9aafc554da0d6fe363549/lib/model/roi_pooling/modules/roi_pool_py.py#L44-L45
the outer max function takes max value of dim 2, however, in pytorch 0.2 and above, the default value of argument `keepdim` is  `False`. This means after the inner max function, dim 2 doesn't exist !  This will cause an error.

I really appreciate your work!  But hope you can check the existing code more carefully, especially the changed APIs.

**Comment by jwyang** [comment]
Hi, @drcege ,  appreciate for pointing out this. The code actually does not use roi_pool_py.py. We missed it and will remove it from the repo.

**Comment by jwyang** [comment]
@drcege removed it.

**Comment by drcege** [comment]
Yes, I know. I used to debug my own code in cpu mode.
