### ISSUE TITLE
KeyError:'model'

### ISSUE THREAD

**Issue by buptwxl** [jwyang/faster-rcnn.pytorch#332]
when i run demo.py ,i met a problem:
```
File "demo.py", line 194, in <module>
    fasterRCNN.load_state_dict(checkpoint['model'])
KeyError: 'model'

```
i wanna to know how to solve this question. Thanks

**Comment by jwyang** [comment]
@buptwxl I think you are loading the wrong pertrained model. Please download the models linked in the first column of the table.
