### ISSUE TITLE
How to execute this program w/o GPU

### ISSUE THREAD

**Issue by jihwan1008** [jwyang/faster-rcnn.pytorch#334]
Hello, thanks for your nice and neat repo.
I'm trying to get the region proposals from faster-RCNN using my local laptop which is Macbook.
As far as I know, only extracting proposals might not need that much of computation power(still it would take more time than GPU), so I tried to execute this code w/o GPU. 

But, when I typed shell command, 'sh make.sh', it spits out a 'cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1', which I never heard of. I'd searched for it, and it says the error is due to wrong CUDA_ARCH, but the thing is that I do not have GPU in my computer. I'm not sure how to handle this issue. Any help would be appreciated.

**Comment by jwyang** [comment]
@jihwan1008 it might not because of the CUDA error. Please check your gcc version and the pytorch version. I compiled it on my MacBook successfully, which does not have a Nvidia gpu as well.

**Comment by jihwan1008** [comment]
Thx, I'll check it out!
