### ISSUE TITLE
Segmentation fault while running on GPU

### ISSUE THREAD

**Issue by snehabhattacharya** [jwyang/faster-rcnn.pytorch#337]
Hello,

I am getting a segmentation fault when I use the --cuda option while running the trainval_net.py . I am using Cuda 8.0 and pytorch 0.4.0.

Sneha

**Comment by quanghainguyen1512** [comment]
Did you run demo file successfully? Because I'm getting same error as yours when trying to run demo

**Comment by jwyang** [comment]
@snehabhattacharya what is the exact command you used to run the training?

**Comment by snehabhattacharya** [comment]
@jwyang  I am just running the trainval_net.py --cuda=True

**Comment by jwyang** [comment]
@snehabhattacharya please follow the readme to run the code. your command is wrong...

**Comment by snehabhattacharya** [comment]
@jwyang  That was a typo, I am using python trainval_net.py --dataset="my dataset" --cuda
