### ISSUE TITLE
RoIAlign implementation

### ISSUE THREAD

**Issue by drcege** [jwyang/faster-rcnn.pytorch#34]
In the implementationof RoIAlign, I can't figure out why minus one here. 
https://github.com/jwyang/faster-rcnn.pytorch/blob/c12d2151baf5cba241f9aafc554da0d6fe363549/lib/model/roi_align/src/roi_align_kernel.cu#L42-L43
Isn't it just divided by aligned_height? Could you please explain it briefly, thank you!

**Comment by AceCoooool** [comment]
You can stand on the "point view". For example, the `aligned_height=3`，the correspond of roi is `(0, 0), (0, 1), (0, 2)` you can see only two gap between 0~3.
