### ISSUE TITLE
test error： raise EOFError

### ISSUE THREAD

**Issue by buptwxl** [jwyang/faster-rcnn.pytorch#342]
When i try to test the network, i met this problem:
![image](https://user-images.githubusercontent.com/18524936/47067665-b86f0180-d21c-11e8-8858-1221b141d880.png)
  my traning parameters:
                   --dataset pascal_voc --net vgg16 --bs 1 --lr 0.001--lr_decay_step 5
                   --cuda
And  i set max_epoch=6
 test command：
python test_net.py --dataset pascal_voc --net vgg16 --checksession 1 --checkepoch 6 --checkpoint 10021 --cuda

Thanks very much.

**Comment by jwyang** [comment]
@buptwxl I think it is because the python you use has different version to the pickle file.

**Comment by buptwxl** [comment]
Thank you. I solved this problem with python 3.6.
