### ISSUE TITLE
load pretrained model failed?

### ISSUE THREAD

**Issue by mlinxiang** [jwyang/faster-rcnn.pytorch#345]
download from report res101 link, and command as follow:
python demo.py --net res101  --dataset coco --checksession 1 --checkepoch 10 --checkpoint 9771 --cuda --load_dir data/pretrained_model

![image](https://user-images.githubusercontent.com/6283983/47284150-de2f4880-d618-11e8-95d6-69efc77d7969.png)

**Comment by yufengm** [comment]
Yeah. I had the exact the same error. It seems that in the pretrained model, the RPN has 12 anchor boxes, which result in 24 scores and 48 coordinates, while in current model definition there were only 9 (3x3) anchor boxes.
Any ideas on how to redefine the anchor boxes (ratios and scales) @jwyang 
Thanks so much.

**Comment by yufengm** [comment]
Sorry. I found this in the test_net.py file. You may just replace [8,16,32] with [4,8,16,32] by args.set_cfgs = ['ANCHOR_SCALES', '[4, 8, 16, 32]', 'ANCHOR_RATIOS', '[0.5,1,2]']
