### ISSUE TITLE
Training from scratch 

### ISSUE THREAD

**Issue by xiao1228** [jwyang/faster-rcnn.pytorch#358]
Hi Thank you for the repo.
I am just wondering if you have tried to train the model (Resnet101 backbone) from scratch without using the pretrained caffe model?
How many epochs does it required to converge?

**Comment by kentaroy47** [comment]
From readme.md, jwyang provides COCO trained models of epoch 8 and 10.
It took me about 3 days to train with a single TitanXp.

![image](https://user-images.githubusercontent.com/39611941/48037717-8a495700-e122-11e8-842b-7ae062ce60a2.png)
