### ISSUE TITLE
Python3 please

### ISSUE THREAD

**Issue by achaiah** [jwyang/faster-rcnn.pytorch#36]
Yes, I know you've mentioned that you will work on it in the README but a lot of times people never get to it. So here's an "issue" to put on the backlog ;)

**Comment by jwyang** [comment]
@achaiah , thanks for reminding, yesterday, @cclauss  has submitted a pull request of python 3 supporting. I will check with that.

**Comment by Rizhiy** [comment]
+1

**Comment by Cadene** [comment]
https://docs.python.org/2/library/2to3.html

You could try this magical stuff, it works

**Comment by cclauss** [comment]
@Rizhiy and @Cadene please review the changes proposed in #35

**Comment by jwyang** [comment]
Hi, all,

Thanks to @cclauss 's great work, I have merged the pull request to modernize the code. I am testing it on my local machine for both python2 and python3. Will let you know once it is finished.

**Comment by cclauss** [comment]
On Python 2, you might check the files that have `from __future__ import absolute_import` added to them.  I have found that sometimes the fixes like https://github.com/jwyang/faster-rcnn.pytorch/pull/35/files#diff-efb4ed79deff927409f05a9d2a8d00e3R26 or https://github.com/jwyang/faster-rcnn.pytorch/pull/35/files#diff-313099e030e342d2f4dd855e99772543R20 are not right in Python 2.

**Comment by jwyang** [comment]
@cclauss , thanks!

I have tried on my side, made some changes and it should work on both python2 and python3 now.
One more thing to note is that the pycocotool now merely support python2.

**Comment by achaiah** [comment]
Awesome, glad you tackled it so soon!

**Comment by jwyang** [comment]
@achaiah ,  sure, let me know if you encounter problems.

**Comment by cclauss** [comment]
On __pycocotool__ see https://github.com/cocodataset/cocoapi/pull/108

**Comment by jwyang** [comment]
@cclauss ,thanks!
