### ISSUE TITLE
Can u help me solve my question？

### ISSUE THREAD

**Issue by Bingyang0410** [jwyang/faster-rcnn.pytorch#361]
I have successfully run train_net.py and test_net.py, but some fault comes when I am trying to run the code of demo.py,
There is no input directory for loading network from faster-rcnn.pytorch/models/vgg16/pascal_voc/vgg16/pascal_voc
I got the train models by train_net.py and put them into faster-rcnn.pytorch/models/vgg16/pascal_voc/vgg16/pascal_voc, I don't know where I am wrong

**Comment by kentaroy47** [comment]
models should be under
faster-rcnn.pytorch/models/vgg16/pascal_voc/


not
faster-rcnn.pytorch/models/vgg16/pascal_voc/vgg16/pascal_voc/
