### ISSUE TITLE
(pytorch v'1.0.0.dev20181113') torch.utils.ffi is deprecated. Please use cpp extensions instead

### ISSUE THREAD

**Issue by ahmed-shariff** [jwyang/faster-rcnn.pytorch#363]
torch.utils.ffi is deprecated in pytorch version 1.0+

**Comment by jwyang** [comment]
@ahmed-shariff thanks for reminding! Not this repo now can only support pytorch up to 0.4.0. Will work on the upgrading later.

**Comment by ahmed-shariff** [comment]
I will see if I can make any changes. The cpp_extention's JIT loader seems like a nice option. Also #289 should help support later versions.

**Comment by Forgetmyfairy** [comment]
Does this program work in pytorch1.0, how to fix the error or replace the error reporting module????

**Comment by ahmed-shariff** [comment]
Have you looked at https://github.com/pytorch/vision/blob/master/torchvision/models/detection/faster_rcnn.py ?

**Comment by Forgetmyfairy** [comment]
Thank you for your reply . Sorry, I haven't read this yet. Let me have a look. I want to make sure that this problem can still be solved.

**Comment by Forgetmyfairy** [comment]
emmm, @ahmed-shariff  could you tell me how to fix it directly. I've only found one way to lower the torch version so far, but that doesn't fit my current situation.

**Comment by ahmed-shariff** [comment]
I am not sure what is it you are struggling with? If you can give more detail I might be able to help in some way.

**Comment by Forgetmyfairy** [comment]
emmm, the problem I encountered was that "torch.utils.ffi is deprecated. Please use cpp extensions instead" in pytorch1.0.0 ,now I have two choices, one is reducing  the torch's version to 0.4, another is address this problem . however, I need to run this program in NVIDIA Jetson xavier , and  in Jetson xavier,I can only install torch 1.0.0 , So I need to address the problem that happened in pytorch1.0.0 , do you have some ideas to help me ? Thank you .
