### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by duwangzhe** [jwyang/faster-rcnn.pytorch#365]
I wonder which database does this pre-trained model based on, coco voc or something else?

**Comment by jwyang** [comment]
yes, mscoco

**Comment by duwangzhe** [comment]
@jwyang ,I watched the pretrained model that you prepared, I found that it only contains the backbone's parameter. I wonder that how do you only save the backbone's model when you trained the model in Ms coco dataset

**Comment by duwangzhe** [comment]
>>> import torch
>>> the_model = torch.load('data/pretrained_model/resnet101_caffe.pth')
>>> for k,v in the_model.items():
...   print(k)
...
conv1.weight
bn1.weight
bn1.bias
bn1.running_mean
bn1.running_var
layer1.0.conv1.weight
layer1.0.bn1.weight
layer1.0.bn1.bias
layer1.0.bn1.running_mean
layer1.0.bn1.running_var
layer1.0.conv2.weight
layer1.0.bn2.weight
layer1.0.bn2.bias
layer1.0.bn2.running_mean
layer1.0.bn2.running_var
layer1.0.conv3.weight
layer1.0.bn3.weight
layer1.0.bn3.bias
layer1.0.bn3.running_mean
layer1.0.bn3.running_var
layer1.0.downsample.0.weight
layer1.0.downsample.1.weight
layer1.0.downsample.1.bias
layer1.0.downsample.1.running_mean
layer1.0.downsample.1.running_var
layer1.1.conv1.weight
layer1.1.bn1.weight
layer1.1.bn1.bias
layer1.1.bn1.running_mean
layer1.1.bn1.running_var
layer1.1.conv2.weight
layer1.1.bn2.weight
layer1.1.bn2.bias
layer1.1.bn2.running_mean
layer1.1.bn2.running_var
layer1.1.conv3.weight
layer1.1.bn3.weight
layer1.1.bn3.bias
layer1.1.bn3.running_mean
layer1.1.bn3.running_var
layer1.2.conv1.weight
layer1.2.bn1.weight
layer1.2.bn1.bias
layer1.2.bn1.running_mean
layer1.2.bn1.running_var
layer1.2.conv2.weight
layer1.2.bn2.weight
layer1.2.bn2.bias
layer1.2.bn2.running_mean
layer1.2.bn2.running_var
.......

**Comment by jinggew** [comment]
hi, have you solved your problem?
