### ISSUE TITLE
cuda out of memory when I run test_net.py and demo.py

### ISSUE THREAD

**Issue by zqdeepbluesky** [jwyang/faster-rcnn.pytorch#366]
I trained 10 epoch on the voc dataset, the network used is resnet101, but when I test, it shows cuda out of memory. This is also the case when I run demo.py. I don't know how to solve it.my GPU is 1050ti 4G, Can anyone help me?

**Comment by kentaroy47** [comment]
You need >4G memory to run res101 model..
Try running on smaller models :)

**Comment by zqdeepbluesky** [comment]
@kentaroy47 Thanks for your reply, but Is there a way to fix it without changing the model?

**Comment by ahmed-shariff** [comment]
try reducing the `RPN_PRE_NMS_TOP_N` and `RPN_POST_NMS_TOP_N` values in [config.py](https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/model/utils/config.py)?

**Comment by zqdeepbluesky** [comment]
ok,I will try it.thanks for your reply.

**Comment by jin1ming** [comment]
Adding "with torch.no_grad()" before "rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)" can solve it perfectly. 
I have successfully tested it on 1650 4g.

**Comment by Lyhour-Chhay** [comment]
@jin1ming I did it base on your comment but I get the this error: RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn. How can I solve it ?
