### ISSUE TITLE
BBox output coordinates

### ISSUE THREAD

**Issue by Hartland-3** [jwyang/faster-rcnn.pytorch#380]
Not really an issue, I'm using your project to feed annotated images into an RNN. Is there anywhere that I can grab the coordinates of the bounding boxes drawn in each image?

**Comment by jwyang** [comment]
@Hartland-3 You can take a look at this line: https://github.com/jwyang/faster-rcnn.pytorch/blob/c01a86e9139280804a1b5ddc89e9b2aea0e7e73f/lib/model/faster_rcnn/faster_rcnn.py#L50

**Comment by darshitj15** [comment]
> Not really an issue, I'm using your project to feed annotated images into an RNN. Is there anywhere that I can grab the coordinates of the bounding boxes drawn in each image?

Hey, 
Were you able to find the solution for this? Did you get the coordinates by any means?
