### ISSUE TITLE
logger file does not exist in lib/model/utils?

### ISSUE THREAD

**Issue by zhixinwang** [jwyang/faster-rcnn.pytorch#4]
I find the logger file doesn't exiti in lib/model/utils, but it is used in https://github.com/jwyang/faster-rcnn.pytorch/blob/9b1ca882168ea3ecaf482eabd6ac2e8731639fb8/trainval_net.py#L150
could you commit this file?

**Comment by jwyang** [comment]
thanks for reminding, will commit this.

**Comment by zhixinwang** [comment]
Thanks for your job.

**Comment by jwyang** [comment]
already added
