### ISSUE TITLE
error of "sh make.sh"

### ISSUE THREAD

**Issue by 114153** [jwyang/faster-rcnn.pytorch#400]
/home/CAD409/teng/faster_rcnn/lib/model/roi_pooling
Including CUDA code.
generating /tmp/tmpCfGCy3/_roi_pooling.c
setting the current directory to '/tmp/tmpCfGCy3'
running build_ext
building '_roi_pooling' extension
creating home
creating home/CAD409
creating home/CAD409/teng
creating home/CAD409/teng/faster_rcnn
creating home/CAD409/teng/faster_rcnn/lib
creating home/CAD409/teng/faster_rcnn/lib/model
creating home/CAD409/teng/faster_rcnn/lib/model/roi_pooling
creating home/CAD409/teng/faster_rcnn/lib/model/roi_pooling/src
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c99 -fPIC -DWITH_CUDA -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python2.7 -c _roi_pooling.c -o ./_roi_pooling.o -std=c99
In file included from /usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _roi_pooling.c:493:
/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
 #include "cuda.h"
                  ^
compilation terminated.
Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/lib64/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
Compiling roi align kernels by nvcc...
In file included from <command-line>:0:0:
/usr/local/cuda-8.0/bin/../targets/x86_64-linux/include/cuda_runtime.h:78:25: fatal error: host_config.h: No such file or directory
 #include "host_config.h"
                         ^
compilation terminated.
/home/CAD409/teng/faster_rcnn/lib/model/roi_align
Including CUDA code.
generating /tmp/tmpW_ee0T/_roi_align.c
setting the current directory to '/tmp/tmpW_ee0T'
running build_ext
building '_roi_align' extension
creating home
creating home/CAD409
creating home/CAD409/teng
creating home/CAD409/teng/faster_rcnn
creating home/CAD409/teng/faster_rcnn/lib
creating home/CAD409/teng/faster_rcnn/lib/model
creating home/CAD409/teng/faster_rcnn/lib/model/roi_align
creating home/CAD409/teng/faster_rcnn/lib/model/roi_align/src
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c99 -fPIC -DWITH_CUDA -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python2.7 -c _roi_align.c -o ./_roi_align.o -std=c99
In file included from /usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _roi_align.c:493:
/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
 #include "cuda.h"
                  ^
compilation terminated.
Traceback (most recent call last):
  File "build.py", line 38, in <module>
    ffi.build()
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/lib64/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
Compiling roi crop kernels by nvcc...
In file included from <command-line>:0:0:
/usr/local/cuda-8.0/bin/../targets/x86_64-linux/include/cuda_runtime.h:78:25: fatal error: host_config.h: No such file or directory
 #include "host_config.h"
                         ^
compilation terminated.
Including CUDA code.
/home/CAD409/teng/faster_rcnn/lib/model/roi_crop
generating /tmp/tmpvEk43o/_roi_crop.c
setting the current directory to '/tmp/tmpvEk43o'
running build_ext
building '_roi_crop' extension
creating home
creating home/CAD409
creating home/CAD409/teng
creating home/CAD409/teng/faster_rcnn
creating home/CAD409/teng/faster_rcnn/lib
creating home/CAD409/teng/faster_rcnn/lib/model
creating home/CAD409/teng/faster_rcnn/lib/model/roi_crop
creating home/CAD409/teng/faster_rcnn/lib/model/roi_crop/src
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c99 -fPIC -DWITH_CUDA -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python2.7 -c _roi_crop.c -o ./_roi_crop.o -std=c99
In file included from /usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _roi_crop.c:493:
/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
 #include "cuda.h"
                  ^
compilation terminated.
Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/lib64/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
[CAD409@cu03 lib]$ export PATH=$PATH:/usr/local/cuda/bin
[CAD409@cu03 lib]$ sh make.sh
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
In file included from <command-line>:0:0:
/usr/local/cuda-8.0/bin/../targets/x86_64-linux/include/cuda_runtime.h:78:25: fatal error: host_config.h: No such file or directory
 #include "host_config.h"
                         ^
compilation terminated.
Including CUDA code.
/home/CAD409/teng/faster_rcnn/lib/model/nms
['/home/CAD409/teng/faster_rcnn/lib/model/nms/src/nms_cuda_kernel.cu.o']
generating /tmp/tmpgryUN3/_nms.c
setting the current directory to '/tmp/tmpgryUN3'
running build_ext
building '_nms' extension
creating home
creating home/CAD409
creating home/CAD409/teng
creating home/CAD409/teng/faster_rcnn
creating home/CAD409/teng/faster_rcnn/lib
creating home/CAD409/teng/faster_rcnn/lib/model
creating home/CAD409/teng/faster_rcnn/lib/model/nms
creating home/CAD409/teng/faster_rcnn/lib/model/nms/src
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c99 -fPIC -DWITH_CUDA -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python2.7 -c _nms.c -o ./_nms.o -std=c99
In file included from /usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _nms.c:493:
/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
 #include "cuda.h"
                  ^
compilation terminated.
Traceback (most recent call last):
  File "build.py", line 37, in <module>
    ffi.build()
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/lib64/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
Compiling roi pooling kernels by nvcc...
In file included from <command-line>:0:0:
/usr/local/cuda-8.0/bin/../targets/x86_64-linux/include/cuda_runtime.h:78:25: fatal error: host_config.h: No such file or directory
 #include "host_config.h"
                         ^
compilation terminated.
/home/CAD409/teng/faster_rcnn/lib/model/roi_pooling
Including CUDA code.
generating /tmp/tmp7WyIQK/_roi_pooling.c
setting the current directory to '/tmp/tmp7WyIQK'
running build_ext
building '_roi_pooling' extension
creating home
creating home/CAD409
creating home/CAD409/teng
creating home/CAD409/teng/faster_rcnn
creating home/CAD409/teng/faster_rcnn/lib
creating home/CAD409/teng/faster_rcnn/lib/model
creating home/CAD409/teng/faster_rcnn/lib/model/roi_pooling
creating home/CAD409/teng/faster_rcnn/lib/model/roi_pooling/src
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c99 -fPIC -DWITH_CUDA -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python2.7 -c _roi_pooling.c -o ./_roi_pooling.o -std=c99
In file included from /usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _roi_pooling.c:493:
/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
 #include "cuda.h"
                  ^
compilation terminated.
Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/lib64/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
Compiling roi align kernels by nvcc...
In file included from <command-line>:0:0:
/usr/local/cuda-8.0/bin/../targets/x86_64-linux/include/cuda_runtime.h:78:25: fatal error: host_config.h: No such file or directory
 #include "host_config.h"
                         ^
compilation terminated.
/home/CAD409/teng/faster_rcnn/lib/model/roi_align
Including CUDA code.
generating /tmp/tmpsssQkW/_roi_align.c
setting the current directory to '/tmp/tmpsssQkW'
running build_ext
building '_roi_align' extension
creating home
creating home/CAD409
creating home/CAD409/teng
creating home/CAD409/teng/faster_rcnn
creating home/CAD409/teng/faster_rcnn/lib
creating home/CAD409/teng/faster_rcnn/lib/model
creating home/CAD409/teng/faster_rcnn/lib/model/roi_align
creating home/CAD409/teng/faster_rcnn/lib/model/roi_align/src
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c99 -fPIC -DWITH_CUDA -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python2.7 -c _roi_align.c -o ./_roi_align.o -std=c99
In file included from /usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _roi_align.c:493:
/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
 #include "cuda.h"
                  ^
compilation terminated.
Traceback (most recent call last):
  File "build.py", line 38, in <module>
    ffi.build()
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/lib64/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
Compiling roi crop kernels by nvcc...
In file included from <command-line>:0:0:
/usr/local/cuda-8.0/bin/../targets/x86_64-linux/include/cuda_runtime.h:78:25: fatal error: host_config.h: No such file or directory
 #include "host_config.h"
                         ^
compilation terminated.
Including CUDA code.
/home/CAD409/teng/faster_rcnn/lib/model/roi_crop
generating /tmp/tmpN0c8GN/_roi_crop.c
setting the current directory to '/tmp/tmpN0c8GN'
running build_ext
building '_roi_crop' extension
creating home
creating home/CAD409
creating home/CAD409/teng
creating home/CAD409/teng/faster_rcnn
creating home/CAD409/teng/faster_rcnn/lib
creating home/CAD409/teng/faster_rcnn/lib/model
creating home/CAD409/teng/faster_rcnn/lib/model/roi_crop
creating home/CAD409/teng/faster_rcnn/lib/model/roi_crop/src
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c99 -fPIC -DWITH_CUDA -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python2.7 -c _roi_crop.c -o ./_roi_crop.o -std=c99
In file included from /usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _roi_crop.c:493:
/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
 #include "cuda.h"
                  ^
compilation terminated.
Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/lib64/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/lib64/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
[CAD409@cu03 lib]$ export PATH=$PATH:/usr/local/cuda/bin
[CAD409@cu03 lib]$ sh make.sh
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
In file included from <command-line>:0:0:
/usr/local/cuda-8.0/bin/../targets/x86_64-linux/include/cuda_runtime.h:78:25: fatal error: host_config.h: No such file or directory
 #include "host_config.h"
                         ^
compilation terminated.
Including CUDA code.
/home/CAD409/teng/faster_rcnn/lib/model/nms
['/home/CAD409/teng/faster_rcnn/lib/model/nms/src/nms_cuda_kernel.cu.o']
generating /tmp/tmpIG2BnD/_nms.c
setting the current directory to '/tmp/tmpIG2BnD'
running build_ext
building '_nms' extension
creating home
creating home/CAD409
creating home/CAD409/teng
creating home/CAD409/teng/faster_rcnn
creating home/CAD409/teng/faster_rcnn/lib
creating home/CAD409/teng/faster_rcnn/lib/model
creating home/CAD409/teng/faster_rcnn/lib/model/nms
creating home/CAD409/teng/faster_rcnn/lib/model/nms/src
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c99 -fPIC -DWITH_CUDA -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python2.7 -c _nms.c -o ./_nms.o -std=c99
In file included from /usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _nms.c:493:
/usr/lib64/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
 #include "cuda.h"

**Comment by 114153** [comment]
oh,great!
I add some code into make.sh and then all work right~
`export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}
export CPATH=/usr/local/cuda-8.0/include${CPATH:+:${CPATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}`

**Comment by fhong-jpg** [comment]
i did not work for me.
