### ISSUE TITLE
untimeError: cuda runtime error (30) : unknown error at /home/leon/workdir/GitRepo/faster-rcnn.pytorch/lib/model/csrc/cuda/nms.cu:103 is killing me!Please help!

### ISSUE THREAD

**Issue by xbutterflyx** [jwyang/faster-rcnn.pytorch#422]
**This is my env:**
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176
OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
CMake version: version 3.10.2
Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 390.87
cuDNN version: Probably one of the following:
/usr/local/cuda-9.0/lib64/libcudnn.so
/usr/local/cuda-9.0/lib64/libcudnn.so.7
/usr/local/cuda-9.0/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.0/lib64/libcudnn_static.a
/usr/local/lib/libcudnn.so
/usr/local/lib/libcudnn.so.7
--------------------------------------------------------------------------------------------------------------------------
**I run the codes like this:**
CUDA_VISIBLE_DEVICES=$GPU_ID python trainval_net.py \
                   --dataset pascal_voc --net vgg16 \
                   --bs 24 --nw 2 \
                   --lr 0.01 --lr_decay_step 100 \
                   --cuda
--------------------------------------------------------------------------------------------------------------------------
**And it returns like this:**
......
......
**THCudaCheck FAIL file=/home/leon/workdir/GitRepo/faster-rcnn.pytorch/lib/model/csrc/cuda/nms.cu line=103 error=30 : unknown error
Traceback (most recent call last):
  File "trainval_net.py", line 320, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/leon/workdir/GitRepo/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 54, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/leon/workdir/GitRepo/faster-rcnn.pytorch/lib/model/rpn/rpn.py", line 78, in forward
    im_info, cfg_key))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/leon/workdir/GitRepo/faster-rcnn.pytorch/lib/model/rpn/proposal_layer.py", line 147, in forward
    keep_idx_i = nms(proposals_single, scores_single.squeeze(1), nms_thresh)
RuntimeError: cuda runtime error (30) : unknown error at /home/leon/workdir/GitRepo/faster-rcnn.pytorch/lib/model/csrc/cuda/nms.cu:103**

the unknown error it raises kills me a lot of times...
please help...

**Comment by Jordi-Gene-Mola** [comment]
how did you fix that?
