### ISSUE TITLE
Problem when using roipooling module

### ISSUE THREAD

**Issue by JoyHuYY1412** [jwyang/faster-rcnn.pytorch#431]
Thank you for your wok. 
My env is CUDA7.5, pytorch 0.4.1
Since I wnat to use the roi_pooling module, I go to roipooling/src dir, and run
`nvcc -c -o roi_pooling.cu.o roi_pooling_kernel.cu -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -gencode arch=compute_50,code=sm_50
`
then I get *.o files, and I run build.py. I can't see any error.

When I test:

> from lib.model.roi_pooling.modules.roi_pool import _RoIPooling 
roipool = _RoIPooling(2,2,1)
e=torch.arange(1,10).view(1,1,3,3).float()
roi = torch.tensor([[0,0.0,0.0,2,2]])
f = roipool(e,roi)
print(f)

The result is right.
However, when I use 

> from lib.model.roi_pooling.modules.roi_pool import _RoIPooling 
roipool = _RoIPooling(2,2,1)
e=torch.arange(1,10).view(1,1,3,3).float().cuda()
roi = torch.tensor([[0,0.0,0.0,2,2]]).cuda()
f = roipool(e,roi)
print(f)

It says 

> cudaCheckError() failed : no kernel image is available for execution on the device

I don't know how to solve this. BTW, can I use this module when I run my code with multi-gpus?

**Comment by jwyang** [comment]
@JoyHuYY1412 you need also convert roipool layer from cpu to coda type by adding .cuda() at its end.

**Comment by JoyHuYY1412** [comment]
Actually I have written `roipool = _RoIPooling(2,2,1)` but still 

> cudaCheckError() failed : no kernel image is available for execution on the device

**Comment by JoyHuYY1412** [comment]
> @JoyHuYY1412 you need also convert roipool layer from cpu to coda type by adding .cuda() at its end.

Actually I have written `roipool = _RoIPooling(2,2,1).cuda() `but still

> cudaCheckError() failed : no kernel image is available for execution on the device

**Comment by mynameischaos** [comment]
When using multi-gpu, I meet the same problem.
