### ISSUE TITLE
Is there any image augmentation used in this implementation?

### ISSUE THREAD

**Issue by KwanWaiChung** [jwyang/faster-rcnn.pytorch#432]
I have just started to use this implementation and I wondered whether we have to do the augmentation on our own.

**Comment by jwyang** [comment]
@JojoFisherman we did flip and slight random crop on the training dataset, other than these, you can do your own data augmentation, such as adding noises or rotate or so.

**Comment by RafaelMostert** [comment]
There is more then just flipping and cropping.

In trainval_net.py roibatchLoader calls get_minibatch from lib/roi_data_layer/minibatch.py
which calls prep_im_for_blob from lib/model/utils/blob.py
which subtracts PIXEL_MEANS from every image.
Afterwards, in the same function, the image is resized using cv2.resize. (As explained in the [blog](http://www.telesens.co/2018/03/11/object-detection-and-classification-using-r-cnns/))

The values for PIXEL_MEANS and the default resized dimensions can be found in /lib/model/utils/config.py:
```
# Scale to use during training (can list multiple scales)
# The scale is the pixel size of an image's shortest side
__C.TRAIN.SCALES = (600,)
# Max pixel size of the longest side of a scaled input image

__C.TRAIN.MAX_SIZE = 1000
```
Also mentioned there are the default sizes to which an image is then cropped:
```
# Trim size for input images to create minibatch
__C.TRAIN.TRIM_HEIGHT = 600
__C.TRAIN.TRIM_WIDTH = 600
```
 
@jwyang I wonder: where do the annotation bounding box positions get adjusted to fit these new scaled, cropped and/or flipped images?

**Comment by Saharkakavand** [comment]
@RafaelMostert Do you find where the bounding box is adjusted?

**Comment by Janezzliu** [comment]
> There is more then just flipping and cropping.
> 
> In trainval_net.py roibatchLoader calls get_minibatch from lib/roi_data_layer/minibatch.py
> which calls prep_im_for_blob from lib/model/utils/blob.py
> which subtracts PIXEL_MEANS from every image.
> Afterwards, in the same function, the image is resized using cv2.resize. (As explained in the [blog](http://www.telesens.co/2018/03/11/object-detection-and-classification-using-r-cnns/))
> 
> The values for PIXEL_MEANS and the default resized dimensions can be found in /lib/model/utils/config.py:
> 
> ```
> # Scale to use during training (can list multiple scales)
> # The scale is the pixel size of an image's shortest side
> __C.TRAIN.SCALES = (600,)
> # Max pixel size of the longest side of a scaled input image
> 
> __C.TRAIN.MAX_SIZE = 1000
> ```
> 
> Also mentioned there are the default sizes to which an image is then cropped:
> 
> ```
> # Trim size for input images to create minibatch
> __C.TRAIN.TRIM_HEIGHT = 600
> __C.TRAIN.TRIM_WIDTH = 600
> ```
> 
> @jwyang I wonder: where do the annotation bounding box positions get adjusted to fit these new scaled, cropped and/or flipped images?

Hi, would mind telling me where is the crop function in the codes? I only know how to set flip in the codes, but I haven't find crop.

**Comment by forever208** [comment]
> There is more then just flipping and cropping.
> 
> In trainval_net.py roibatchLoader calls get_minibatch from lib/roi_data_layer/minibatch.py
> which calls prep_im_for_blob from lib/model/utils/blob.py
> which subtracts PIXEL_MEANS from every image.
> Afterwards, in the same function, the image is resized using cv2.resize. (As explained in the [blog](http://www.telesens.co/2018/03/11/object-detection-and-classification-using-r-cnns/))
> 
> The values for PIXEL_MEANS and the default resized dimensions can be found in /lib/model/utils/config.py:
> 
> ```
> # Scale to use during training (can list multiple scales)
> # The scale is the pixel size of an image's shortest side
> __C.TRAIN.SCALES = (600,)
> # Max pixel size of the longest side of a scaled input image
> 
> __C.TRAIN.MAX_SIZE = 1000
> ```
> 
> Also mentioned there are the default sizes to which an image is then cropped:
> 
> ```
> # Trim size for input images to create minibatch
> __C.TRAIN.TRIM_HEIGHT = 600
> __C.TRAIN.TRIM_WIDTH = 600
> ```
> 
> @jwyang I wonder: where do the annotation bounding box positions get adjusted to fit these new scaled, cropped and/or flipped images?

> __C.TRAIN.TRIM_HEIGHT = 600
> __C.TRAIN.TRIM_WIDTH = 600
those 2 parameters are actually not used in image cropping

**Comment by forever208** [comment]
```
__C.TRAIN.TRIM_HEIGHT = 600
__C.TRAIN.TRIM_WIDTH = 600
```

those 2 parameters are actually not used in image cropping @RafaelMostert
