### ISSUE TITLE
    why we need  Fix the layers before conv3?

### ISSUE THREAD

**Issue by ycui123** [jwyang/faster-rcnn.pytorch#434]
Hi,

I was reading the code and I found in vgg16.py line 40:     # Fix the layers before conv3:

I don't understand why do we need to do this? Is it because we use pretrained model? Should I comment it out if I want to train the model from scratch ?

Thanks

**Comment by karanchawla** [comment]
This is done because the backbone is used as a feature generator which is then sent to the region proposal network.
