### ISSUE TITLE
How to use coco2017 dataset

### ISSUE THREAD

**Issue by muzammil360** [jwyang/faster-rcnn.pytorch#451]
Hi. 
I am trying to train faster rcnn using coco2017 dataset. 

However, I don't understand what symbolic links I need to make.

Can someone explain the directory structure expected by the code and related symbolic links?

**Comment by EMCP** [comment]
https://stackoverflow.com/questions/1951742/how-to-symlink-a-file-in-linux

Your answer is there

**Comment by muzammil360** [comment]
@EMCP thanks

**Comment by yuhua666** [comment]
Have you successfully trained coco2017? I don't know how to train without changing the directory structure of the original dataset.
