### ISSUE TITLE
Run test_net, get "ImportError: torch.utils.ffi is deprecated" error.

### ISSUE THREAD

**Issue by 13952522076** [jwyang/faster-rcnn.pytorch#462]
I have successfully installed the setup. However, when I tried the test_net, I still got the  "ImportError: torch.utils.ffi is deprecated" error. I am sure in the pytroch1.0 branch. So, what should I do now?

`[xm0036@t3-login2 faster-rcnn.pytorch]$ CUDA_VISIBLE_DEVICES=0,1,2,3 python test_net.py --dataset pascal_voc --net vgg16                    --checksession 1 --checkepoch 6 --checkpoint 416                    --cuda
Traceback (most recent call last):
  File "test_net.py", line 30, in <module>
    from model.utils.net_utils import save_net, load_net, vis_detections
  File "/home/xm0036/faster-rcnn.pytorch/lib/model/utils/net_utils.py", line 8, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/home/xm0036/faster-rcnn.pytorch/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/home/xm0036/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 2, in <module>
    from torch.utils.ffi import _wrap_function
  File "/home/xm0036/.local/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.`

**Comment by 13952522076** [comment]
Sorry for my carelessness. I just create the pytorch-1.0 branch by myself, and the code is the same as master branch. My bad.

**Comment by 13952522076** [comment]
Sorry for my carelessness. I just create the pytorch-1.0 branch by myself, and the code is the same as master branch. My bad.

**Comment by Forgetmyfairy** [comment]
Does this program work in pytorch1.0, how to fix the error or replace the error reporting module????
