### ISSUE TITLE
nan in test_net.py

### ISSUE THREAD

**Issue by h510166404** [jwyang/faster-rcnn.pytorch#463]
load checkpoint weights/res101/coco/faster_rcnn_1_31_1793.pth
load model successfully!
Evaluating detections5s 0.004s   
Collecting 1 results (1/5)
Collecting 2 results (2/5)
Collecting 3 results (3/5)
Collecting 4 results (4/5)
Collecting 5 results (5/5)
Writing results json to /home/hyc/faster-rcnn.new/output/res101/coco_2014_minival/faster_rcnn_10/detections_minival2014_results.json
Loading and preparing results...     
DONE (t=0.04s)
creating index...
index created!
Running per image evaluation...      
DONE (t=0.47s).
Accumulating evaluation results...   
DONE (t=0.06s).
/home/hyc/anaconda2/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/hyc/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
~~~~ Mean and per-category AP @ IoU=[0.50,0.95] ~~~~
nan
nan
nan
nan
nan
nan
~~~~ Summary metrics ~~~~
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
Wrote COCO eval results to: /home/hyc/faster-rcnn.new/output/res101/coco_2014_minival/faster_rcnn_10/detection_results.pkl
test time: 9.6591s

help~~~

**Comment by TomHeaven** [comment]
@h510166404 I met exactly the same problem. How do you solve it?

**Comment by h510166404** [comment]
> 
> 
> @h510166404 I met exactly the same problem. How do you solve it?

i computed the area of each bbox in 'annotations'

**Comment by TomHeaven** [comment]
@h510166404 Thank you very much!!! That saved my day!
