### ISSUE TITLE
problem loading Coco models

### ISSUE THREAD

**Issue by fguney** [jwyang/faster-rcnn.pytorch#47]
when I try to load a Res101 model trained on Coco, I get this error:

`RuntimeError: While copying the parameter named RCNN_rpn.RPN_cls_score.weight, whose dimensions in the model are torch.Size([18, 512, 1, 1]) and whose dimensions in the checkpoint are torch.Size([24, 512, 1, 1]).`

**Comment by fguney** [comment]
Never mind, I've figured it out. It's a config file thing. 
If someone else is having the same issue: 
Depending on the scale, in the args, use  `--cfg cfgs/res101_ls.yml` or `--cfg cfgs/res101.yml`
and update the demo.py:
`args.set_cfgs = ['ANCHOR_SCALES', '[4, 8, 16, 32]', 'ANCHOR_RATIOS', '[0.5,1,2]']`
before 
` if args.set_cfgs is not None:
   cfg_from_list(args.set_cfgs)`

**Comment by FiredFree** [comment]
I trianing  vgg16 on coco ,  but when I load the modle in test_net.py , I met the same error , and I tried your method, but it do not work.  could you help me？

**Comment by fguney** [comment]
well, there is no vgg16_ls.yml file in cfgs folder. you could create one by comparing res101.yml and res101_ls.yml or you could check test_net.py to see how it's done in case "--ls" command is specified for large scale.
