### ISSUE TITLE
How to deal with input size of Faster RCNN and VGG16 /(ㄒoㄒ)/~~?

### ISSUE THREAD

**Issue by yiran7324** [jwyang/faster-rcnn.pytorch#484]
Hi, I'm new here and not familiar with some preset of the object detection network.

Since I checked several repos and found that usually vgg16 model is imported as:

```py
import torchvision.models as models

```

They use [models.vgg16()](https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/model/faster_rcnn/vgg16.py#L29) for building this model, so as far as I'm concerned that the input should have sizes congruent with 224 * 224. But I wonder why FasterRCNN supports an input of arbitrary size of images (i.e 1000 * 600), which is not suitable for vgg.

Is there any transforming of the data that can feed an image of a size 1000 * 600 into fixed size 224 * 224 that vgg got?

**Comment by yiran7324** [comment]
Is there for example rescale the image with a certain rate and feed the image into 224 * 224 and rescale the bbox back according to the scale to get `1:1` result?

**Comment by yiran7324** [comment]
https://github.com/rbgirshick/py-faster-rcnn/issues/475

may solve this problem.

**Comment by leesing9** [comment]
that's good.
