### ISSUE TITLE
A confused error：段错误(吐核)

### ISSUE THREAD

**Issue by DiaoYuxian** [jwyang/faster-rcnn.pytorch#485]
Thank you for you codes firstly.

when I run：
CUDA_VISIBLE_DEVICES=0 python3 trainval_net.py --dataset pascal_voc --net vgg16 --bs 1 --nw 1 --lr 0.0001 --lr_decay_step 5 --cuda

I got this error：

Preparing training data...
done
before filtering, there are 10022 images...
after filtering, there are 10022 images...
10022 roidb entries
Loading pretrained weights from data/pretrained_model/vgg16_caffe.pth
段错误(吐核)

then it stopped ruuning.

 Why I got this error?

**Comment by heekhero** [comment]
I have the same problem with you!

**Comment by DiaoYuxian** [comment]
> I have the same problem with you!

Additionally， when I compiled the cuda dependencies using:
python setup.py build develop
I received a warning reminding me to update GCC to 4.9 or higher.(My GCC is 4.8)
So I think this error may be caused by compiling incorrectly.
Finally , I run pytorch 0.4 branch.

**Comment by heekhero** [comment]
does it work properly?

**Comment by heekhero** [comment]
Because pytorch version 1.0 is much more changed than version 0.4, I think it's necessary to solve this problem in version 1.0. I'll let you know when I solve this problem.

**Comment by DiaoYuxian** [comment]
> Because pytorch version 1.0 is much more changed than version 0.4, I think it's necessary to solve this problem in version 1.0. I'll let you know when I solve this problem.

Pytorch 0.4 works properly. 
Good luck！Looking forward to your good news

**Comment by DiaoYuxian** [comment]
solved by upadting GCC4.8 to GCC5.2 and install pytorch1.0.0. 
see:  #503
