### ISSUE TITLE
pytorch1.0 python3.6 Error 

### ISSUE THREAD

**Issue by moondaiy** [jwyang/faster-rcnn.pytorch#486]
Hi Thans to work , it well, i want to build this pro for pytorch 1.0 ,python3.6
ps: gcc version?  4.9 or later ?

**Comment by moondaiy** [comment]
系统的cuda版本要和conda 安装的cuda 版本一致....
 我的最终环境是 系统中安装的 cuda9.2  
conda pytorch1.0.0 cuda9.2
要确保一致,这样编译   以及 运行的时候 才不至于出错. 编译通过了 但是运行发现错误的话 考虑下 conda 中安装的 cuda 是否一致 这个比较坑....

**Comment by kentaroy47** [comment]
please state the error you get.
it should build fine with pytorch1.0+cuda9.2
