### ISSUE TITLE
After successfully training I got Demo Runtime error

### ISSUE THREAD

**Issue by EldorIbragimov** [jwyang/faster-rcnn.pytorch#49]
Traceback (most recent call last):
  File "/home/e/faster-rcnn.pytorch/demo.py", line 178, in <module>
    fasterRCNN.load_state_dict(checkpoint['model'])
  File "/home/e/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 487, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named RCNN_cls_score.weight, whose dimensions in the model are torch.Size([1, 4096]) and whose dimensions in the checkpoint are torch.Size([9, 4096]).

**Comment by jwyang** [comment]
Hi, @EldorIbragimov , please read the readme under the demo section, you need to change these [lines](https://github.com/jwyang/faster-rcnn.pytorch/blob/17e9b9608b00ff677caa83c9c2679b5d2b0883aa/demo.py#L162) to change the list of classes for your own model.

**Comment by EldorIbragimov** [comment]
Yes. I changed already but still getting this error. my class numbers are same in pascal_voc.py and demo.py

**Comment by jwyang** [comment]
it seems that the number of object classes in your trained model and the model in demo is different. one is 9 but one is 1?

**Comment by EldorIbragimov** [comment]
Yes. I just just changed classes in pascal_voc.py and demo.py with same numbers. I changed class numbers to one or random numbers in demo.py.  But still same error appearing.

**Comment by jwyang** [comment]
Can you run demo with our pretrained model?

**Comment by EldorIbragimov** [comment]
do you mean just test with pretrained model?. if so, I run and I got this error 
Traceback (most recent call last):
  File "/home/e/faster-rcnn.pytorch/demo.py", line 178, in <module>
    fasterRCNN.load_state_dict(checkpoint['model'])
KeyError: 'model'

**Comment by jwyang** [comment]
could you post the lines you changed in demo.py?

**Comment by EldorIbragimov** [comment]
I changed 57 and 157 lines

**Comment by EldorIbragimov** [comment]
It worked. I donwload demo.py again and replace it with old one. I think there are some changes are made with new demo.py. Thank you help!

**Comment by jwyang** [comment]
glad to know that! will close this issue.
