### ISSUE TITLE
low mAP on voc2007

### ISSUE THREAD

**Issue by DiaoYuxian** [jwyang/faster-rcnn.pytorch#497]
I run the master branch with ptyroch0.4.0， but got low mAP.  I used pretrained_model: vgg16_caffe.pth.
Could someone give me some advice on hyperparameters?

CUDA_VISIBLE_DEVICES=0 python trainval_net.py --dataset pascal_voc --net vgg16 --bs 1 --nw 1 --lr 0.0001 --lr_decay_step 5 --cuda

python test_net.py --dataset pascal_voc --net vgg16 --cuda

AP for aeroplane = 0.3451
AP for bicycle = 0.3566
AP for bird = 0.3209
AP for boat = 0.2109
AP for bottle = 0.1610
AP for bus = 0.3453
AP for car = 0.5734
AP for cat = 0.4840
AP for chair = 0.2318
AP for cow = 0.2903
AP for diningtable = 0.2457
AP for dog = 0.3679
AP for horse = 0.5015
AP for motorbike = 0.3815
AP for person = 0.5461
AP for pottedplant = 0.1773
AP for sheep = 0.3042
AP for sofa = 0.2995
AP for train = 0.4304
AP for tvmonitor = 0.3754
Mean AP = 0.3474

**Comment by DiaoYuxian** [comment]
I know how， just because I ignored to set checkepoch.
Run:
python test_net.py --dataset pascal_voc --net vgg16 --checksession 1 --checkepoch 20 --checkpoint 10021  --cuda
Then I got right mAP.

**Comment by kentaroy47** [comment]
can you close this issue?
