### ISSUE TITLE
Why does rois has 5 dimensions?

### ISSUE THREAD

**Issue by HaiminZhang** [jwyang/faster-rcnn.pytorch#498]
Could you please explain why rois has 5 dimensions?

**Comment by andrewjong** [comment]
https://medium.com/@andrewjong87/how-to-use-roi-pool-and-roi-align-in-your-neural-networks-pytorch-1-0-b43e3d22d073

**Comment by HaiminZhang** [comment]
Thanks a lot for your reply.  This tutorial is definitely helpful and has cleared my confusion.

**Comment by andrewjong** [comment]
You're welcome! Please close the issue if your question has been resolved.
