### ISSUE TITLE
multi scale training

### ISSUE THREAD

**Issue by liyangliu** [jwyang/faster-rcnn.pytorch#51]
@jwyang, I have fixed the code for multi scale training, but only support short side options, not long side option. I just move the random scale index sampling process from minibatch.py to roibatchLoader.py.

By the way, I read your code and found that when cropping the unusual sized images, https://github.com/jwyang/faster-rcnn.pytorch/blob/17e9b9608b00ff677caa83c9c2679b5d2b0883aa/lib/roi_data_layer/roibatchLoader.py#L111, I wonder why y_s is between [min_y, min_y+y_s_add], but not [min_y, max_y-trim_size]? Because I think the latter is more symmetric regarding min_y and max_y. Thanks.

**Comment by Rizhiy** [comment]
To support long side, you need to check the longest size of the image after you rescale and if it is greater downsize it.

**Comment by maozezhong** [comment]
@liyangliu Hello, Can you share your code for multi-scale training?
