### ISSUE TITLE
jpg to png

### ISSUE THREAD

**Issue by jiangwu1** [jwyang/faster-rcnn.pytorch#510]
when i converted jpg to png ,the error said that File "/home/c101/faster_rcnn/faster-rcnn.pytorch-master/lib/roi_data_layer/roidb.py", line 69, in rank_roidb_ratio
    width = roidb[i]['width']
KeyError: 'width'

How can i to solve this problem ?

**Comment by IVY-bug** [comment]
Try to remove the cache file: data/cache/voc_2007_trainval_gt_roidb.pkl
