### ISSUE TITLE
get stuck at data loading

### ISSUE THREAD

**Issue by liyangliu** [jwyang/faster-rcnn.pytorch#52]
@jwyang, have you ever encountered dead lock when loading batches? I want to replace cv2 with scipy.misc functions, but there seems to be some problem of inconsistent shapes.

**Comment by jwyang** [comment]
yes, that might happen, since the scaling sizes are different between cv2 and scipy,misc, as far as I remember,

**Comment by Cadene** [comment]
@liyangliu Did you change de number of workers of the Dataloader? If so, this pull request could fix your issue: https://github.com/jwyang/faster-rcnn.pytorch/pull/50
