### ISSUE TITLE
pytorch 1.0 version - error on custom COCO dataset

### ISSUE THREAD

**Issue by EMCP** [jwyang/faster-rcnn.pytorch#527]
running a custom dataset, seeing the following

```
Appending horizontally-flipped training examples...
coco_try_20190419_train gt roidb loaded from /media/latest_mount/Dev/git/EMCP/faster-rcnn.pytorch/data/cache/coco_try_20190419_train_gt_roidb.pkl
done
Preparing training data...
Backend TkAgg is interactive backend. Turning interactive mode on.
done
loading annotations into memory.../media/latest_mount/Dev/git/EMCP/faster-rcnn.pytorch/data/coco_try_20190419/annotations/instances_train_20190419.json at 1556370591.791137
Done (t=0.00s)
creating index...
index created!
before filtering, there are 254 images...
after filtering, there are 254 images...
254 roidb entries
Loading pretrained weights from data/pretrained_model/resnet101_caffe.pth
Traceback (most recent call last):
  File "/home/emcp/Tools/pycharm-community-2018.2.4/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/emcp/Tools/pycharm-community-2018.2.4/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/emcp/Tools/pycharm-community-2018.2.4/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/emcp/Tools/pycharm-community-2018.2.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/latest_mount/Dev/git/EMCP/faster-rcnn.pytorch/trainval_net.py", line 322, in <module>
    data = next(data_iter)
  File "/home/emcp/anaconda3/envs/pytorch1_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/emcp/anaconda3/envs/pytorch1_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/media/latest_mount/Dev/git/EMCP/faster-rcnn.pytorch/lib/roi_data_layer/roibatchLoader.py", line 67, in __getitem__
    blobs = get_minibatch(minibatch_db, self._num_classes)
  File "/media/latest_mount/Dev/git/EMCP/faster-rcnn.pytorch/lib/roi_data_layer/minibatch.py", line 30, in get_minibatch
    im_blob, im_scales = _get_image_blob(roidb, random_scale_inds)
  File "/media/latest_mount/Dev/git/EMCP/faster-rcnn.pytorch/lib/roi_data_layer/minibatch.py", line 79, in _get_image_blob
    cfg.TRAIN.MAX_SIZE)
  File "/media/latest_mount/Dev/git/EMCP/faster-rcnn.pytorch/lib/model/utils/blob.py", line 39, in prep_im_for_blob
    im -= pixel_means
ValueError: operands could not be broadcast together with shapes (1880,2880,4) (1,1,3) (1880,2880,4) 
```

**Comment by EMCP** [comment]
looks related to `faster-rcnn.pytorch/lib/roi_data_layer/minibatch.py`

https://github.com/jwyang/faster-rcnn.pytorch/blob/pytorch-1.0/lib/roi_data_layer/minibatch.py#L77-L86

is this code area kind of processing the input so it can be fed into the algorithm?

**Comment by EMCP** [comment]
this was fixed by dropping my input images alpha channel

**Comment by lyx190** [comment]
@EMCP hello, I have a question about the number of images. I got 889 images on my training set, but when training it says that "before filtering there are 444 images, after filtering there are 444 images", do you know how the number of images is not similar with my training set?
Thanks

**Comment by AtriSaxena** [comment]
> this was fixed by dropping my input images alpha channel

@EMCP How you dropped alpha channel and where? 
Thanks in Advance.

**Comment by EMCP** [comment]
you have to change it in two places.. once in the training python file, and one in the demo...

if you detect 4 channels, and you're sure that the alpha channel is unused, go ahead and transform the image using python.. to only 3 channels

https://github.com/jwyang/faster-rcnn.pytorch/blob/master/demo.py#L115-L118

```
  im_orig = im.astype(np.float32, copy=True)
  if im_orig.shape[2] == 4:
      # in the event you have an image with alpha channels, drop it for now
      im_orig = im_orig[:, :, :3]
  im_orig -= cfg.PIXEL_MEANS	  im_orig -= cfg.PIXEL_MEANS


```

**Comment by EMCP** [comment]
@lyx190 , you should check on if you have enabled or disabled horizontal flipping.. if the paths in your coco dataset are valid.. and your dataloader is working

**Comment by lyx190** [comment]
> @lyx190 , you should check on if you have enabled or disabled horizontal flipping.. if the paths in your coco dataset are valid.. and your dataloader is working

thanks for your reply!! I have found out where my problem at.

**Comment by shulisiyuan** [comment]
> you have to change it in two places.. once in the training python file, and one in the demo...
> 
> if you detect 4 channels, and you're sure that the alpha channel is unused, go ahead and transform the image using python.. to only 3 channels
> 
> https://github.com/jwyang/faster-rcnn.pytorch/blob/master/demo.py#L115-L118
> 
> ```
>   im_orig = im.astype(np.float32, copy=True)
>   if im_orig.shape[2] == 4:
>       # in the event you have an image with alpha channels, drop it for now
>       im_orig = im_orig[:, :, :3]
>   im_orig -= cfg.PIXEL_MEANS	  im_orig -= cfg.PIXEL_MEANS
> ```

Hello, 
Take your advice, I have modified the demo.py, but the problem still exists, I don't know how to change training python file, would you plz give me some advice

**Comment by zychen2016** [comment]
could you share you script？

**Comment by zychen2016** [comment]
Using custom coco dataset, errors happend

**Comment by devendraswamy** [comment]
> > @lyx190 , you should check on if you have enabled or disabled horizontal flipping.. if the paths in your coco dataset are valid.. and your dataloader is working
> 
> thanks for your reply!! I have found out where my problem at.

hi..
i am also facing that problem , could you please tell me how you solve that error ??

thanking you ??

**Comment by devendraswamy** [comment]
> Using custom coco dataset, errors happend
> 
> ```
> after filtering, there are 0 images...
> 0 roidb entries
> Loading pretrained weights from data/pretrained_model/resnet101_caffe.pth
> Traceback (most recent call last):
>   File "trainval_net.py", line 373, in <module>
>     save_name = os.path.join(output_dir, 'faster_rcnn_{}_{}_{}.pth'.format(args.session, epoch, step))
> NameError: name 'step' is not defined
> ```

could you drop your custom data here code because you have to modify

**Comment by miaozhang0525** [comment]
> > Using custom coco dataset, errors happend
> > ```
> > after filtering, there are 0 images...
> > 0 roidb entries
> > Loading pretrained weights from data/pretrained_model/resnet101_caffe.pth
> > Traceback (most recent call last):
> >   File "trainval_net.py", line 373, in <module>
> >     save_name = os.path.join(output_dir, 'faster_rcnn_{}_{}_{}.pth'.format(args.session, epoch, step))
> > NameError: name 'step' is not defined
> > ```
> 
> could you drop your custom data here code because you have to modify

Have you guys solved it??
