### ISSUE TITLE
Is pytorch1.0.1 supported?

### ISSUE THREAD

**Issue by Bobfan** [jwyang/faster-rcnn.pytorch#529]
I had error:lib/model/_C.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSsundefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
And I find an answer that downgrade pytorch version to 1.0.0. 
Is there any other solution to solve this problem?

**Comment by jwyang** [comment]
it does not yet support 1.0.1, will work on it, stay tuned.
