### ISSUE TITLE
Issue when compiling roi_crop

### ISSUE THREAD

**Issue by juefeix** [jwyang/faster-rcnn.pytorch#53]
The nms, roi_pooling, roi_align were all compiled fine. However, the roi_crop has the following issue when I tried to compile it. Please advise. Thanks a lot. 

=======
Compiling roi crop kernels by nvcc...
Including CUDA code.
/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop
generating /tmp/tmpVugB2u/_roi_crop.c
running build_ext
building '_roi_crop' extension
creating media
creating media/fx2
creating media/fx2/RESEARCH
creating media/fx2/RESEARCH/faster-rcnn.pytorch
creating media/fx2/RESEARCH/faster-rcnn.pytorch/lib
creating media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model
creating media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop
creating media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/fx2/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/fx2/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/fx2/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/fx2/anaconda2/include/python2.7 -c _roi_crop.c -o ./_roi_crop.o
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/fx2/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/fx2/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/fx2/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/fx2/anaconda2/include/python2.7 -c /media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.c -o ./media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.o
/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.c: In function ‘BilinearSamplerBHWD_updateGradInput’:
/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.c:190:14: warning: unused variable ‘inBottomRight’ [-Wunused-variable]
         real inBottomRight=0;
              ^
/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.c:189:14: warning: unused variable ‘inBottomLeft’ [-Wunused-variable]
         real inBottomLeft=0;
              ^
/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.c:188:14: warning: unused variable ‘inTopRight’ [-Wunused-variable]
         real inTopRight=0;
              ^
/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.c:187:14: warning: unused variable ‘inTopLeft’ [-Wunused-variable]
         real inTopLeft=0;
              ^
/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.c:186:14: warning: unused variable ‘v’ [-Wunused-variable]
         real v=0;
              ^
/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.c: In function ‘BilinearSamplerBCHW_updateGradInput’:
/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.c:441:14: warning: unused variable ‘inBottomRight’ [-Wunused-variable]
         real inBottomRight=0;
              ^
/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.c:440:14: warning: unused variable ‘inBottomLeft’ [-Wunused-variable]
         real inBottomLeft=0;
              ^
/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.c:439:14: warning: unused variable ‘inTopRight’ [-Wunused-variable]
         real inTopRight=0;
              ^
/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.c:438:14: warning: unused variable ‘inTopLeft’ [-Wunused-variable]
         real inTopLeft=0;
              ^
/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.c:437:14: warning: unused variable ‘v’ [-Wunused-variable]
         real v=0;
              ^
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/fx2/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/fx2/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/fx2/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/fx2/anaconda2/include/python2.7 -c /media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop_cuda.c -o ./media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop_cuda.o
gcc -pthread -shared -L/home/fx2/anaconda2/lib -Wl,-rpath=/home/fx2/anaconda2/lib,--no-as-needed ./_roi_crop.o ./media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop.o ./media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop_cuda.o /media/fx2/RESEARCH/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop_cuda_kernel.cu.o -L/home/fx2/anaconda2/lib -lpython2.7 -o ./_roi_crop.so

**Comment by jwyang** [comment]
@juefeix , as far as I can see, it is not an error actually. It is a bunch of warnings of unused variables. I will clean the source code.

**Comment by juefeix** [comment]
Ok I see. Thanks a lot.
