### ISSUE TITLE
large scale explanation?

### ISSUE THREAD

**Issue by EMCP** [jwyang/faster-rcnn.pytorch#532]
I am starting to notice the LS version of Res101, config

https://github.com/jwyang/faster-rcnn.pytorch/blob/master/cfgs/res101_ls.yml

Is there an explanation when to use this?  I have images that are quite high in pixel count 1880x1400 ish .. seems when I try using this config, it runs VERY slow and gives a different status printout (starts citing foreground vs background numbers/ratios.. )

thank you!

**Comment by AlexanderHustinx** [comment]
The --ls tag means that you'll be using a larger scale image.

So lets say you have an input image of 1880x1400

Case 1: In the normal case (when not using --ls) your image will be rescaled to use 600 as dim for the shortest axis and max. 1000 for the longest axis.
That would mean you scale the image to dims: ~806x600 in the example image.

Case 2: In case you do use the larger scale (--ls) your image will be rescaled to use 800 as dim for the shortest axis and max. 1200 for the longest axis.
That would mean you scale the image to dims: ~1075x800 in the example image.

When solely looking at the amount of pixels you input into the model
Case 1: ~806x600   = 483.600 pixels
Case 2: ~1075x800 = 860.000 pixels
So in the --ls case you input ~77.8% more pixels.
This will lead to more computation time.

A reason to use the --ls is that as you have bigger input images, you also have more details/patterns the model can find in the image. This can result in a better mAP in many cases.
Do note that it can sometimes also negatively influence the performance when you hope to find different certain scales of an object (e.g. either very big or small in relation to the image size)

**Comment by EMCP** [comment]
big thanks @AlexanderHustinx .. sounds like I may even need to crank up the resolution further for my usecase.
