### ISSUE TITLE
undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by juefeix** [jwyang/faster-rcnn.pytorch#54]
Hi Jianwei, I ran into this issue of **undefined symbol: PyFPE_jbuf** when I run the training code. I have tried to reinstall, recompile, and stick to the same version as you suggested, but still cannot figure out how to solve this issue. Can you provide some suggestions? 

Thanks a lot!
Best,
Felix

=====
fx2@fx2:/media/fx2/RESEARCH/faster-rcnn.pytorch$ CUDA_VISIBLE_DEVICES=0 python trainval_net.py --dataset pascal_voc --net vgg16 --bs 1 --nw 4 --lr $LEARNING_RATE --lr_decay_step $DECAY_STEP --cuda
Traceback (most recent call last):
  File "trainval_net.py", line 27, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 9, in <module>
    from datasets.factory import get_imdb
  File "/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/datasets/factory.py", line 15, in <module>
    from datasets.coco import coco
  File "/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/datasets/coco.py", line 23, in <module>
    from pycocotools.coco import COCO
  File "/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/pycocotools/coco.py", line 58, in <module>
    import mask
  File "/media/fx2/RESEARCH/faster-rcnn.pytorch/lib/pycocotools/mask.py", line 3, in <module>
    from . import _mask
ImportError: /media/fx2/RESEARCH/faster-rcnn.pytorch/lib/pycocotools/_mask.so: **undefined symbol: PyFPE_jbuf**

**Comment by jwyang** [comment]
It seems that it is caused by wrong _mask.so.  Which version of python are you using? Could you please delete it and recompile them again?

**Comment by juefeix** [comment]
Python 2.7 as suggested. I did recompile it but still no luck. Any particular requirement for the compiler? Or anything else you suggest that I check? Thanks.

**Comment by jwyang** [comment]
@juefeix I guess it is because you are using a non-supported numpy. Maybe you need to uninstall your numpy, and then install a new version.

**Comment by liyangliu** [comment]
Maybe you can try to use pycocotools from https://github.com/cocodataset/cocoapi/tree/master/PythonAPI.

**Comment by ssdyue** [comment]
Hello, do you solve it? I also meet this problem.
