### ISSUE TITLE
QUESTION about number of training images

### ISSUE THREAD

**Issue by lyx190** [jwyang/faster-rcnn.pytorch#549]
Hello everyone,
I have successfully trained with my own dataset. My dataset has been modified as the PASCAL_VOC format. And there are totally 889 images in my "trainval.txt", but when I begin the training process. It shows:
"before filtering, there are 444 images,
after filtering, there are 444 images,
444 roidbs entries"

Can anyone tell me how are there 444 images? THANKS A LOT!

I have figured out the reason, thank @jwyang your repository, you can close this issue.

**Comment by mama110** [comment]
@lyx190  Can you please tell me the solution about this issue? My dataset has 1544 images, but it shows that there are 3088 images, I'm confused.
