### ISSUE TITLE
how to use vgg16_caffe to run demo.py

### ISSUE THREAD

**Issue by Dylanbron** [jwyang/faster-rcnn.pytorch#563]
when i use vgg16_caffe .  report show me that there isn't key called 'model'. i find that the dict structure of vgg16_caffe is not the same as  the dict structure of model we trained.  How can i use  vgg16_caffe to run the demo.py

![image](https://user-images.githubusercontent.com/39022774/58488640-4b512080-819c-11e9-9292-b563d16f7507.png)

**Comment by jwyang** [comment]
you cannot use vgg16_caffe model for demo, since it is just a pretrained vgg16 on imagenet, which is not compatible for faster r-cnn.
