### ISSUE TITLE
gcc versions later than 6 are not supported!

### ISSUE THREAD

**Issue by ouening** [jwyang/faster-rcnn.pytorch#568]
OS:Ubuntu18.04
python:3.6.8
pytorch:1.1.0
cuda:9.0
cudnn:7.4.2
gcc:7.4

When I excuted the commands below:
```
cd lib
python setup.py build develop
```
I got errors:
`In file included from /usr/local/cuda/include/host_config.h:50:0,
                 from /usr/local/cuda/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/local/cuda/include/crt/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1`

Can someone solve it?

**Comment by AlexanderHustinx** [comment]
Your CUDA version is not compatible with your GCC version.

I suggest you have a look here:  https://stackoverflow.com/questions/6622454/cuda-incompatible-with-my-gcc-version

The first solution mentions a fix and the second shows which GCC versions are compatible with which CUDA versions

**Comment by ouening** [comment]
Yeah, I solved it by installing `gcc-5`:
```
sudo apt install gcc-5 g++-5 gcc-5-multilib g++-5-multilib

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50

sudo update-alternatives --install /usr/bin/g++ g++/usr/bin/g++-7 70 

sudo update-alternatives --install /usr/bin/g++ g++/usr/bin/g++-5 50

sudo update-alternatives --config gcc
```
and choose `gcc-5`
