### ISSUE TITLE
 ModuleNotFoundError No module named 'model.utils.cython_bbox'

### ISSUE THREAD

**Issue by dadadadashan** [jwyang/faster-rcnn.pytorch#570]
I got an error: faster-rcnn-root/lib/datasets/imdb.py, line 14, in <module> ModuleNotFoundError No module named 'model.utils.cython_bbox' , when i test the model use 'python test_net.py --dataset pascal_voc --net vgg16 '

**Comment by jwyang** [comment]
Hi, did you compile the module before using it for testing?

**Comment by dadadadashan** [comment]
Hi, it workable  now. I compiled the module again. Thanks!

**Comment by wwyi1828** [comment]
> 
> 
> Hi, did you compile the module before using it for testing?

Hi, could you share me a link about how to compile the module? Thank you so much.

**Comment by shuang1204** [comment]
请问是怎么解决的，我训练的时候也遇到了同样的问题@达达达山@jwyang
