### ISSUE TITLE
Could not find roi_crop_cuda_kernel.cu.o

### ISSUE THREAD

**Issue by Kenneth-Wong** [jwyang/faster-rcnn.pytorch#59]
When compiling lib, I get the error, ".......roi_crop_cuda_kernel.cu.o: no such file or directory."

**Comment by jwyang** [comment]
@Kenneth-Wong , did you compile other source files successfully?

**Comment by Kenneth-Wong** [comment]
OK. I am sorry that I was not in the lab during the last three days and could not reply you in time. I can compile it successfully now after reading your README.md and reset the "CUDA_ARCH". Thanks!

**Comment by Kenneth-Wong** [comment]
@jwyang, I am sorry that I was not in the lab during the last three days and could not reply you in time. I can compile it successfully now after reading your README.md and reset the "CUDA_ARCH". Thanks!

**Comment by jwyang** [comment]
great! I am closing this issue

**Comment by yokosyun** [comment]
I had same problem. I used anaconda3,python3.6,ubuntu18.04,cuda 10.1,gcc 5. The problem was I didn't  pass the environment PATH of CUDA. 
So I could not use
`nvcc -V`

I solved by
`export PATH=/usr/local/cuda-10.1/bin:$PATH`
`export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64:$LD_LIBRARY_PATH`
