### ISSUE TITLE
How can I  support pytorch=1.0.1?

### ISSUE THREAD

**Issue by herrickli** [jwyang/faster-rcnn.pytorch#591]
Cause I can't directly install pytorch=1.0.0 from Anaconda.

**Comment by AlexanderHustinx** [comment]
You can install pytorch-1.0.0 using Anaconda using the command:
`conda install pytorch=1.0.0 <cuda version> -c pytorch`
Where `<cuda version>` is e.g. `cuda90`

Regarding how to support pytorch-1.0.1, you will have to update the code in many many places..
Haven't looked into where specifically, but you could always try.
