### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_nms)

### ISSUE THREAD

**Issue by Zakiyi** [jwyang/faster-rcnn.pytorch#6]
Hello, thx for sharing, I'd like to run the script on my own data, but there is a Importerror when import _nms.so file. i.e. `from ._nms import lib as _lib, ffi as _ffi`, the specific error like this:

> importerror dynamic module does not define module export function(PyInit_nms)

I wonder whether the python version account for this (since I use python3.5), so i try to rebuild the _nms.so, but there seems no related file that used for generating _nms.so file.

**Comment by jwyang** [comment]
yes, i did not commit nms source files. I will add them as well.

**Comment by jwyang** [comment]
@Zakiyi ,

I have added them. you just need to run make.sh in lib folder to compile all the dependencies with python 3.5.

**Comment by Zakiyi** [comment]
Great thanks!!!

**Comment by jwyang** [comment]
no problem. let me know if there are any issues on compiling.
