### ISSUE TITLE
No module named _nms after trying to run the trainival_net.py

### ISSUE THREAD

**Issue by amlandas78** [jwyang/faster-rcnn.pytorch#603]
I did compile the lib using "sh make.sh". I have "nms_cuda_kernel.cu.o" in my nms/src folder. I still have the same error. It shows "ImportError: No module named _nms". From "faster-rcnn.pytorch/lib/model/nms/_ext/nms/init.py", line 3, in
from ._nms import lib as _lib, ffi as _ffi"

**Comment by jwyang** [comment]
it seems that you are compiling pytorch 0.4.0 version with pytorch 1.0. Please make sure you are using the right branch.
