### ISSUE TITLE
how to choose cuda for compiling in pytorch-1.0 branch?

### ISSUE THREAD

**Issue by XuYunqiu** [jwyang/faster-rcnn.pytorch#605]
Hi, thanks for your work.

Would you please tell me how to change my CUDA_PATH for compiling in pytorch-1.0

I have two CUDA (9.0 and 9.2). But the one that I want to use is not saved in /usr/local/cuda/.

What should be modified in setup.py to change the CUDA_PATH. It always uses the CUDA in /usr/local/cuda/ by default.

**Comment by junqiangwu** [comment]
`export LD_LIBRARY_PATH=/path/cuda/cuda-10.0/cuda/lib64:/path/cuda/cuda-10.0/cudnn/v7.5.0/lib64:$LD_LIBRARY_PATH
    
export CUDA_HOME=/path/cuda/cuda-10.0/cuda
export CUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME`

**Comment by XuYunqiu** [comment]
> `export LD_LIBRARY_PATH=/path/cuda/cuda-10.0/cuda/lib64:/path/cuda/cuda-10.0/cudnn/v7.5.0/lib64:$LD_LIBRARY_PATH`
> 
> `export CUDA_HOME=/path/cuda/cuda-10.0/cuda`
> `export CUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME`

thanks

**Comment by Songtingt** [comment]
> `export LD_LIBRARY_PATH=/path/cuda/cuda-10.0/cuda/lib64:/path/cuda/cuda-10.0/cudnn/v7.5.0/lib64:$LD_LIBRARY_PATH`
> 
> `export CUDA_HOME=/path/cuda/cuda-10.0/cuda`
> `export CUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME`

could you please tell me where to set these words?

**Comment by XuYunqiu** [comment]
> > `export LD_LIBRARY_PATH=/path/cuda/cuda-10.0/cuda/lib64:/path/cuda/cuda-10.0/cudnn/v7.5.0/lib64:$LD_LIBRARY_PATH`
> > `export CUDA_HOME=/path/cuda/cuda-10.0/cuda`
> > `export CUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME`
> 
> could you please tell me where to set these words?

in faster-rcnn.pytorch/lib/make.sh

**Comment by Songtingt** [comment]
thanku but i run&nbsp;pytorch1.0
There is no&nbsp;make.sh file here&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "YunqiuXu"<notifications@github.com&gt;; 
发送时间: 2019年12月10日(星期二) 晚上7:12
收件人: "jwyang/faster-rcnn.pytorch"<faster-rcnn.pytorch@noreply.github.com&gt;; 
抄送: "jimmyfa"<1123701799@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [jwyang/faster-rcnn.pytorch] how to choose cuda for compiling in pytorch-1.0 branch? (#605)



  
export LD_LIBRARY_PATH=/path/cuda/cuda-10.0/cuda/lib64:/path/cuda/cuda-10.0/cudnn/v7.5.0/lib64:$LD_LIBRARY_PATH
 export CUDA_HOME=/path/cuda/cuda-10.0/cuda
 export CUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME
  
could you please tell me where to set these words?
  
in faster-rcnn.pytorch/lib/make.sh

**Comment by Songtingt** [comment]
> > > `export LD_LIBRARY_PATH=/path/cuda/cuda-10.0/cuda/lib64:/path/cuda/cuda-10.0/cudnn/v7.5.0/lib64:$LD_LIBRARY_PATH`
> > > `export CUDA_HOME=/path/cuda/cuda-10.0/cuda`
> > > `export CUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME`
> > 
> > 
> > could you please tell me where to set these words?
> 
> in faster-rcnn.pytorch/lib/make.sh

i run with pytorch1.0,there is no make.sh here  >-<

**Comment by XuYunqiu** [comment]
Maybe you can write and run a shell script by yourself like this:
export XXXX
python setup.py build develop

or just try to export these things using command line, before run `python setup.py build develop`

**Comment by Songtingt** [comment]
> Maybe you can write and run a shell script by yourself like this:
> export XXXX
> python setup.py build develop
> 
> or just try to export these things using command line, before run `python setup.py build develop`

emmm其实我不太会
