### ISSUE TITLE
number of images

### ISSUE THREAD

**Issue by mama110** [jwyang/faster-rcnn.pytorch#606]
I have total 1544 images in my dataset, but when I run trainval_net.py, the logs tell me that there are 3088 images. 

before filtering, there are 3088 images...
after filtering, there are 3088 images...
3088 roidb entries

**Comment by xiaoyangGL** [comment]
Did you solve this problem?

**Comment by Jackbrocp** [comment]
did you solve this ?

**Comment by Jackbrocp** [comment]
maybe double the num of training data

**Comment by xiaoyangGL** [comment]
You can see the 'config.py' line 90. The code uses horizontally-flipped images during training, so double the number of training data. You can set False in '__C.TRAIN.USE_FLIPPED'.

At 2019-12-15 19:37:33, "Jackbrocp" <notifications@github.com> wrote:


maybe double the num of training data

**Comment by Swaggyyoung03** [comment]
def get_training_roidb(imdb):
    """Returns a roidb (Region of Interest database) for use in training."""
    if False:
    #if cfg.TRAIN.USE_FLIPPED:
      print('Appending horizontally-flipped training examples...')
      imdb.append_flipped_images()
      print('done')

    print('Preparing training data...')

    prepare_roidb(imdb)
    #ratio_index = rank_roidb_ratio(imdb)
    print('done')

    return imdb.roidb

Just disable the function of horizontally-flipped training examples and you will solve the problem.
