### ISSUE TITLE
AttributeError: 'int' object has no attribute 'astype'

### ISSUE THREAD

**Issue by zhengxinvip** [jwyang/faster-rcnn.pytorch#613]
Traceback (most recent call last):
  File "trainval_net.py", line 209, in <module>
    imdb.num_classes, training=True)
  File "/home/wuwenfu/faster-rcnn.pytorch-master/lib/roi_data_layer/roibatchLoader.py", line 54, in __init__
    self.ratio_list_batch[left_idx:(right_idx+1)] = torch.tensor(target_ratio.astype(np.float64)) # trainset ratio list ,each batch is same number
AttributeError: 'int' object has no attribute 'astype'

why got a error? how can I do after?

**Comment by TerenceChen95** [comment]
this may help:
target_ratio = np.float64(target_ratio)

**Comment by zhengxinvip** [comment]
> this may help:
> target_ratio = np.float64(target_ratio)

thanks I fix this questions

**Comment by charulatalodha** [comment]
it worked.

now i am getting : 
File "/content/drive/My Drive/fasterrcnn18nov/faster-rcnn.pytorch/lib/model/rpn/proposal_target_layer_cascade.py", line 133, in _sample_rois_pytorch
    labels = gt_boxes[:,:,4].contiguous().view(-1).index((offset.view(-1),)).view(batch_size, -1)
AttributeError: 'Tensor' object has no attribute 'index'

**Comment by anwari-alt** [comment]
def cluster_acc(y_true, y_pred):
    """
    Calculate clustering accuracy. Require scikit-learn installed.
    (Taken from https://github.com/XifengGuo/IDEC-toy/blob/master/DEC.py)
    # Arguments
        y: true labels, numpy.array with shape `(n_samples,)`
        y_pred: predicted labels, numpy.array with shape `(n_samples,)`
    # Return
        accuracy, in [0,1]
    """
    y_true = y_true.astype(np.float)
    assert y_pred.size == y_true.size
    D = max(y_pred.max(), y_true.max()) + 1
    w = np.zeros((D, D), dtype=np.float)
    for i in range(y_pred.size):
        w[y_pred[i], y_true[i]] += 1
    ind = linear_assignment(w.max() - w) # Optimal label mapping based on the Hungarian algorithm

    return sum([w[i, j] for i, j in ind]) * 1.0 / y_pred.size 

give error in int object has no atribute astype.i change it on float bhut not resolve.how solve this?

**Comment by FlashlightET** [comment]
didnt work

```self.transformer.n_samples_seen_.astype(np.float64(np.int64))```
