### ISSUE TITLE
Issues using pretrained vg model

### ISSUE THREAD

**Issue by CharlotteG95** [jwyang/faster-rcnn.pytorch#625]
Trying to use your code and the visual genome faster r-cnn pretrained model (http://data.lip6.fr/cadene/faster-rcnn.pytorch/faster_rcnn_1_19_48611.pth) for transfer learning and I'm getting a size issue when I assign the parameters (re-using the code from the vgg16 model `vgg.load_state_dict({k:v for k,v in state_dict.items() if k in vgg.state_dict()})` but once the faster r-cnn model has been created):

	size mismatch for RCNN_cls_score.weight: copying a param with shape torch.Size([2501, 4096]) from checkpoint, the shape in current model is torch.Size([1601, 4096]).
	size mismatch for RCNN_cls_score.bias: copying a param with shape torch.Size([2501]) from checkpoint, the shape in current model is torch.Size([1601]).
	size mismatch for RCNN_bbox_pred.weight: copying a param with shape torch.Size([10004, 4096]) from checkpoint, the shape in current model is torch.Size([6404, 4096]).
	size mismatch for RCNN_bbox_pred.bias: copying a param with shape torch.Size([10004]) from checkpoint, the shape in current model is torch.Size([6404])

EDIT: Is this due to the vg reduction to 1600 classes? How can this be resolved in the architecture?

**Comment by CharlotteG95** [comment]
does anyone have a 1600-400-20 trained Faster R-CNN with VGG backbone? Cant currently train the whole thing from scratch and this would solve my problem

**Comment by alibabadoufu** [comment]
> does anyone have a 1600-400-20 trained Faster R-CNN with VGG backbone? Cant currently train the whole thing from scratch and this would solve my problem

You have to use the 2500-1000-500 split dataset. 1600-400-20 will not work

**Comment by CharlotteG95** [comment]
@alibabadoufu I dont understand why? And the issue was it wasn't working _with_ the 2500-1000-500 and I am trying to figure out why.

**Comment by alibabadoufu** [comment]
@CharlotteG95 what was the error you got? I was able to run on 2500-1000-500 split but got the same error reported here [https://github.com/jwyang/faster-rcnn.pytorch/issues/283#issue-354971048]

**Comment by CharlotteG95** [comment]
the error is the size mismatch shown above. I am now working with the code differently so no longer an issue
