### ISSUE TITLE
Why AP and Mean AP result is weird after testing?

### ISSUE THREAD

**Issue by EldorIbragimov** [jwyang/faster-rcnn.pytorch#64]
Evaluating detections
Writing l VOC results file
Writing a VOC results file
Writing p VOC results file
VOC07 metric? Yes
/home/e/faster-rcnn.pytorch/lib/datasets/voc_eval.py:204: RuntimeWarning: invalid value encountered in true_divide
  rec = tp / float(npos)
/home/e/faster-rcnn.pytorch/lib/datasets/voc_eval.py:45: RuntimeWarning: invalid value encountered in greater_equal
  if np.sum(rec >= t) == 0:
AP for l  = 0.0000
AP for a = 0.0000
AP for p = 0.2000
Mean AP = 0.0667
~~~~~~~~
Results:
0.000
0.000
0.200
0.067
~~~~~~~~

**Comment by jwyang** [comment]
@EldorIbragimov it seems like you are testing on your own dataset, right? have you ever visualized the results?

**Comment by EldorIbragimov** [comment]
Yes I visualized results on Demo and the results are good. Actually my goal is to see accuracy for each class.

**Comment by EldorIbragimov** [comment]
Hello. I solved this issue. there was a problem with my dataset. so I fixed it. You can close it. Thanks!

**Comment by jwyang** [comment]
@EldorIbragimov great!

**Comment by wzli1214** [comment]
@EldorIbragimov 
I have the same problem. 
How to solve AP = 0 ?

**Comment by chj1933** [comment]
@EldorIbragimov  Why AP and Mean AP result is weird after testing?  can you tell me how to modify? I also have the same problem  AP = 0

**Comment by sjytker** [comment]
> Hello. I solved this issue. there was a problem with my dataset. so I fixed it. You can close it. Thanks!

Same problem, could you elaborate how to solve it?
