### ISSUE TITLE
ImportError: cannot import name '_mask'?Executed python setup.py build develop

### ISSUE THREAD

**Issue by Y132om** [jwyang/faster-rcnn.pytorch#656]
ERROR:
Traceback (most recent call last):
  File "F:/faster-rcnn.pytorch-pytorch-1.0/trainval_net.py", line 27, in <module>
    from lib.roi_data_layer.roidb import combined_roidb
  File "F:\faster-rcnn.pytorch-pytorch-1.0\lib\roi_data_layer\roidb.py", line 9, in <module>
    from datasets.factory import get_imdb
  File "F:\faster-rcnn.pytorch-pytorch-1.0\lib\datasets\factory.py", line 15, in <module>
    from datasets.coco import coco
  File "F:\faster-rcnn.pytorch-pytorch-1.0\lib\datasets\coco.py", line 23, in <module>
    from pycocotools.coco import COCO
  File "F:\faster-rcnn.pytorch-pytorch-1.0\lib\pycocotools\coco.py", line 60, in <module>
    from . import mask
  File "F:\faster-rcnn.pytorch-pytorch-1.0\lib\pycocotools\mask.py", line 3, in <module>
    from . import _mask
ImportError: cannot import name '_mask'

I executed python setup.py build develop

Print the following content：

running develop
running egg_info
writing faster_rcnn.egg-info\PKG-INFO
writing dependency_links to faster_rcnn.egg-info\dependency_links.txt
writing top-level names to faster_rcnn.egg-info\top_level.txt
reading manifest file 'faster_rcnn.egg-info\SOURCES.txt'
writing manifest file 'faster_rcnn.egg-info\SOURCES.txt'
running build_ext
copying build\lib.win-amd64-3.6\model\_C.cp36-win_amd64.pyd -> model
Creating e:\anaconda\anacoda\envs\py36\lib\site-packages\faster-rcnn.egg-link (link to .)
faster-rcnn 0.1 is already the active version in easy-install.pth

Installed f:\faster-rcnn.pytorch-pytorch-1.0\lib
Processing dependencies for faster-rcnn==0.1
Finished processing dependencies for faster-rcnn==0.1

VERSION：
python 3.6.8
pytorch 1.0.0
windows10

what should I do？？？

**Comment by Y132om** [comment]
> 错误：
> 回溯（最近一次调用最后一次）：
> 文件“F：/faster-rcnn.pytorch-pytorch-1.0/trainval_net.py”，第27行，
> 从lib.roi_data_layer.roidb导入combined_roidb
> 文件“F：\ faster-rcnn .tstorch-pytorch-1.0 \ lib \ roi_data_layer \ roidb.py“，第9行，
> 来自datasets.factory import get_imdb
> 文件”F：\ faster-rcnn.pytorch-pytorch-1.0 \ lib \ datasets \ factory.py“，第15行，
> 来自datasets.coco导入coco
> 文件“F：\ faster-rcnn.pytorch-pytorch-1.0 \ lib \ datasets \ coco.py”，第23行，
> 来自pycocotools.coco导入COCO
> 文件“F：\ faster” -rcnn.pytorch-pytorch-1.0 \ lib \ pycocotools \ coco.py“，第60行，
> 来自。导入掩码
> 文件“F：\ faster-rcnn.pytorch-pytorch-1。
> 来自。import _mask
> ImportError：无法导入名称'_mask'
> 
> 我执行了python setup.py build develop
> 
> 打印以下内容：
> 
> 运行开发
> 运行egg_info
> 写入faster_rcnn.egg-info \ PKG-INFO
> 将dependency_links写入faster_rcnn.egg-info \ dependency_links.txt
> 将顶级名称写入faster_rcnn.egg-info \ top_level.txt
> 读取清单文件'faster_rcnn.egg-info \ SOURCES.txt'
> 写清单文件'faster_rcnn.egg-info \ SOURCES.txt'
> 运行build_ext
> 复制build \ lib.win-amd64-3.6 \ model_C.cp36-win_amd64.pyd - >模型
> 创建e：\ anaconda \ anacoda \ envs \ py36 \ lib \ site-packages \ faster-rcnn.egg-link（link to。）
> faster-rcnn 0.1已经是easy-install.pth中的活动版本了
> 
> 已安装f：\ faster-rcnn.pytorch-pytorch-1.0 \ lib
> 处理依赖关系更快 - rcnn == 0.1已
> 完成处理依赖关系更快 - rcnn == 0.1
> 
> VERSION：
> 蟒蛇3.6.8
> pytorch 1.0.0
> windows10
> 
> 我该怎么办？？？
This part is used coco data，But I want to use my own data set, so delete  factory.py  
`from datasets.coco import coco`

**Comment by WUT-xiaoming** [comment]
作者编译用的python2.7,真无语

**Comment by S0soo** [comment]
i meet same issue, how do i solve it, please!

**Comment by Songtingt** [comment]
the same error too

**Comment by Alan-D-Chen** [comment]
解决的办法是  ：python 3.6  转化为 python2.7吗？？

**Comment by shirui-japina** [comment]
> 解决的办法是 ：python 3.6 转化为 python2.7吗？？

实际python2.7可运行吗？

**Comment by pzhren** [comment]
我也是，不知道咋办

**Comment by wulele2** [comment]
linux下安装pip install pycocotools应该可以

**Comment by wulele2** [comment]
或者将代码中pycocotools删掉，然后从pycocotools的GitHub上下载源码放到fasterrcnn文件夹下单独编译pycocotools
