### ISSUE TITLE
 Errors when running trainning and demos

### ISSUE THREAD

**Issue by hiroponnn** [jwyang/faster-rcnn.pytorch#658]
I use python2.7, pytorch 0.4.0, and CUDA9.0 (GeForce GTX 1080)

When demo.py was executed, the following error occurred.
`demo.py: error: argument --checksession: invalid int value: 'ubuntu'`

When trainval_net.py was executed, the following error occurred.
`trainval_net.py: error: argument --bs: expected one argument`

I know I have to set it up according to the environment, but I don't know how to fix it.
Sorry for the rudimentary question.
if you'd kindly teach me.

**Comment by yonglizhong** [comment]
Hi, was wondering if you have found the way to execute the demo.py command. If so, would it be possible of you to kindly share it? thanks
