### ISSUE TITLE
why cannot get linear speedup with multi-gpus?

### ISSUE THREAD

**Issue by lucas946** [jwyang/faster-rcnn.pytorch#66]
when i use 2 gpus(1080ti) to train this code(using resnet101), the time of per epoch is 0.35 hour(batch_size=2), and the time using 1 gpu is 0.41 hour(batch_size=1).
My question is, why cannot get linear speedup with multi-gpus? and which part of code is responsible for this result?

**Comment by jwyang** [comment]
@lucas946 the cross-cpu communication will take some time. Also, pytorch actually does not work very well on multi-cpu training cases. I guess the newest version should work better now.

**Comment by lucas946** [comment]
Thanks a lot, your answer helps me!

**Comment by jwyang** [comment]
sounds good!
