### ISSUE TITLE
`create_extension` was removed in pytorch-1.0

### ISSUE THREAD

**Issue by sermakarevich** [jwyang/faster-rcnn.pytorch#670]
`create_extension` was supported by pytorch v0.4.1 only
starting 1.0 pytorch the function was erased in favour of cpp extensions but it’s not a drop-in replacement

**Comment by EMCP** [comment]
are you saying `create_extension` is in use on the `pytorch-1.0` branch ? not following here

**Comment by cjxnew** [comment]
@sermakarevich I have encounted a same problem with you, "ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.", this github project said they have updated the code to pytorch 1.0, but this BUG still occur when compiling, it's really confused me. So, any progress? Or how do you solved this problem? Thinks!

**Comment by cjxnew** [comment]
My compiling problem has been solved, I just find the project Code Branch: "pytorch-1.0" version, and followed the compiling guideline “https://github.com/jwyang/faster-rcnn.pytorch/tree/pytorch-1.0”, then I compiled successfully based on pytorch version 1.01.0

**Comment by GreenTeaHua** [comment]
torchvision.ops.nms(boxes, scores, iou_threshold)
    Performs non-maximum suppression (NMS) on the boxes according
    to their intersection-over-union (IoU).

    NMS iteratively removes lower scoring boxes which have an
    IoU greater than iou_threshold with another (higher scoring)
    box.

    Parameters
    ----------
    boxes : Tensor[N, 4])  bounding boxes坐标. 格式：(x1, y1, x2, y2)
        boxes to perform NMS on. They
        are expected to be in (x1, y1, x2, y2) format
    scores : Tensor[N]   bounding boxes得分
        scores for each one of the boxes
    iou_threshold : float IoU过滤阈值
        discards all overlapping
        boxes with IoU < iou_threshold

    Returns
    -------
    keep : Tensor
        int64 tensor with the indices
        of the elements that have been kept
        by NMS, sorted in decreasing order of scores
        NMS过滤后的bouding boxes索引（降序排列）
    """

**Comment by sermakarevich** [comment]
Yes, I missed that code for pytorch 1.0 is not in master.
