### ISSUE TITLE
Test results are all zero

### ISSUE THREAD

**Issue by Saharkakavand** [jwyang/faster-rcnn.pytorch#671]
I could train and test with pascal_voc 2007 correctly. I changed my own dataset to Pascal_voc format I trained and got loss=0.06 but the testing result are all zero. I already saved the output images, the objects are detected and confidence is also good, would you help me to understand what is wrong? 
ps: I just dont have the pose in my annotation files so I also removed that line in the code.

python3 test_net_or.py --dataset pascal_voc --net res101 \--cuda --vis --ls

**Comment by rkruegs123** [comment]
Did you ever get a solution for this?

**Comment by Saharkakavand** [comment]
@rkruegs123 I solved the problem by this solution in pascal_voc.py
cls = self._class_to_ind[obj.find('name').text.lower().strip()]

**Comment by WUT-xiaoming** [comment]
> @rkruegs123 I solved the problem by this solution in pascal_voc.py
> cls = self._class_to_ind[obj.find('name').text.lower().strip()]

What does this mean and what do i need to do

**Comment by sjytker** [comment]
> @rkruegs123 I solved the problem by this solution in pascal_voc.py cls = self._class_to_ind[obj.find('name').text.lower().strip()]

Isn't it the same as the original code?
