### ISSUE TITLE
Plans for other architectures (RFCN)?

### ISSUE THREAD

**Issue by Rizhiy** [jwyang/faster-rcnn.pytorch#69]
Are you planning to implement other object detection architectures?

I'm particularly interested in `RFCN` or `Light-Head RCNN`, you would need to implement `PSRoIPooling` for that.

**Comment by jwyang** [comment]
Hi, @Rizhiy , I do not have a plan for that, but I might work on it casually. Are you working on it now?

**Comment by Rizhiy** [comment]
I wanted to, but I don't know how to add CUDA layers to PyTorch properly.

**Comment by jwyang** [comment]
HI, @Rizhiy , actually, it is not that difficult, you can take reference to the roi_pooling, roi_align or roi_crop_resize in this repository. Since they have implemented the caffe version, it should be easy to transfer it to pytorch. The problem might be how to make it support multi-gpu settings. And i guess it should be not difficult as well.

**Comment by zorrocai** [comment]
Hi, @Rizhiy, the PSRoIPooling may be easy to bind into pytorch, using the original c version https://github.com/daijifeng001/caffe-rfcn/blob/4bcfcd104bb0b9f0862e127c71bd845ddf036f14/src/caffe/layers/psroi_pooling_layer.cu.
I have binded psroi_pooling into  @jwyang's faster-rcnn like roi_pooling operation. But when traning the RFCN, it seems that there are some problems. Maybe you would have some insights into these problems~

**Comment by Rizhiy** [comment]
I suggest you run that version (forwards and backward) in caffe with random input and store inputs, outputs and grads. Then run the layer with the same inputs in PyTorch and make sure that outputs and grads match.

**Comment by zorrocai** [comment]
@Rizhiy Thanks for the reply. Yeah, they match each other. But I got "cuda runtime error(77)":
...
[session 1][epoch  1][iter 9500/10022] loss: 1.3894, lr: 1.00e-02
			fg/bg=(32/96), time cost: 47.936531
			rpn_cls: 0.1539, rpn_box: 0.0736, rcnn_cls: 0.5281, rcnn_box 0.4262
[session 1][epoch  1][iter 9600/10022] loss: 1.2679, lr: 1.00e-02
			fg/bg=(32/96), time cost: 46.028761
			rpn_cls: 0.1042, rpn_box: 0.0398, rcnn_cls: 1.0204, rcnn_box 0.4521
[session 1][epoch  1][iter 9700/10022] loss: 1.4756, lr: 1.00e-02
			fg/bg=(21/107), time cost: 44.804333
			rpn_cls: 0.0936, rpn_box: 0.0181, rcnn_cls: 0.3588, rcnn_box 0.2651
out of memory
invalid argument
CUDA Error: an illegal memory access was encountered, at line 147
CUDA Error: an illegal memory access was encountered, at line 154
an illegal memory access was encountered
an illegal memory access was encountered
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524577177097/work/aten/src/THC/generic/THCStorage.c line=36 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "trainval_net.py", line 322, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/huayue/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/huayue/pytorch/rfcn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 73, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
  File "/home/huayue/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/huayue/pytorch/rfcn.pytorch/lib/model/rpn/rpn.py", line 78, in forward
    im_info, cfg_key))
  File "/home/huayue/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/huayue/pytorch/rfcn.pytorch/lib/model/rpn/proposal_layer.py", line 148, in forward
    keep_idx_i = nms(torch.cat((proposals_single, scores_single), 1), nms_thresh, force_cpu=not cfg.USE_GPU_NMS)
  File "/home/huayue/pytorch/rfcn.pytorch/lib/model/nms/nms_wrapper.py", line 21, in nms
    return nms_gpu(dets, thresh) if force_cpu == False else nms_cpu(dets, thresh)
  File "/home/huayue/pytorch/rfcn.pytorch/lib/model/nms/nms_gpu.py", line 11, in nms_gpu
    keep = keep[:num_out[0]]
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1524577177097/work/aten/src/THC/generic/THCStorage.c:36
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f48ba19cd90>> ignored

it seems weird. I use VOCdevkit2007, not like #99. @jwyang , I cann't locate where is the problem.

**Comment by zorrocai** [comment]
@Rizhiy Thanks, I thought it was the code problem. But I found that the memory used was increased within  the training procedure, after some steps, memory used was out of my GPU memory. Batch size may be needed to set smaller.

**Comment by zorrocai** [comment]
@Rizhiy Sorry to disturb you again. Have you met the situation that GPU memory used during training reached nearly 20G? I set the BATCH_SIZE in cfgs/res101.yml to 1, after 3 epochs memory used is over 22G. I use Tesla P40 which has 22912MB memory.

**Comment by Rizhiy** [comment]
That should be the case, at what resolution are you training? For resnet101 with 1 img per GPU memory should be around 8-10 GB

**Comment by zorrocai** [comment]
Thanks for the quick reply ~~. I utilize the roginial data process in faster rcnn.and I use PASCAL VOC2007.
In that case, Tesla P40 could only support to train 3 images??....

**Comment by Rizhiy** [comment]
You need to test it out yourself. I suggest using resnet50, as it has almost the same performance but uses almost half as much memory.

**Comment by zorrocai** [comment]
Thanks for the suggestion.
