### ISSUE TITLE
Training my own dataset error

### ISSUE THREAD

**Issue by lifuyu** [jwyang/faster-rcnn.pytorch#690]
I set up the dataset in VOC2007 format.Then..

Preparing training data...
done
before filtering, there are 5240 images...
after filtering, there are 0 images...
0 roidb entries
Loading pretrained weights from data/pretrained_model/vgg16_caffe.pth
Traceback (most recent call last):
  File "trainval_net.py", line 373, in <module>
    save_name = os.path.join(output_dir, 'faster_rcnn_{}_{}_{}.pth'.format(args.session, epoch, step))
NameError: name 'step' is not defined
what is wrong with it ?thanks a lot!

**Comment by cjxnew** [comment]
Could you share your experience in training your own data? Like a reference blog or something else. 
THX a lot !

**Comment by lifuyu** [comment]
我可以给你发一份我自己的实验日志，需要的话发你邮箱吧 @cjxnew

**Comment by cjxnew** [comment]
非常感谢！我的邮箱15170799678@163.com，谢谢您！

发自我的 iPhone

**Comment by lifuyu** [comment]
The problem is that'Number of boxes must match number of ground-truth images'

**Comment by cjxnew** [comment]
您好，您在github上提的问题，也就是name 'step' is not defined这个问题，具体的解决办法是什么呢？困扰我好几天了。您提到的number of boxes must match number of gt指的是图片数量和.xml文件数据需要相等吗？
谢谢。

发自我的 iPhone

**Comment by liuge1008** [comment]
您好，能给我也发一份吗？我邮箱617196379@qq.com  谢谢！

**Comment by devendraswamy** [comment]
Actually I have my own dataset in format of ["filename" "boxes label values Like x-min y-min x-max y-max" "class-name"] and filename consist the path of the image, so how can given this dataset to model for testing and training , please anybody help me ..

**Comment by cjxnew** [comment]
You can search a annotation software named 'LabelImg'，install it and then labeling your data，it can generate .xml files with VOC format.

发自我的 iPhone

**Comment by devendraswamy** [comment]
Thank you so much your valuable reply and one more doubt, which parameters
i have to tune in faster rcnn model ?

**Comment by devendraswamy** [comment]
when i am training the model suddenly that will restarted , anybody give the solution for rectify those problem .. 

Thanking you !

**Comment by TengFeiHan0** [comment]
@cjxnew exo me, I got the same problems with you,  how to fix this problem? thank you in advance

**Comment by buaazsj** [comment]
> 我可以给你发一份我自己的实验日志，需要的话发你邮箱吧 @cjxnew

您好，可以也给我发一份训练自己数据集的实验日志吗？zzuzsj@163.com , 谢谢！

**Comment by 5RJ** [comment]
> 我可以给你发一份我自己的实验日志，需要的话发你邮箱吧 @cjxnew

你好，可以也发我一份吗？986570623@qq.com
非常感谢！
