### ISSUE TITLE
How can i find check point and session and checkepoch ?? 

### ISSUE THREAD

**Issue by devendraswamy** [jwyang/faster-rcnn.pytorch#695]
please help me to find out session, checkpoint, checksession from the model and i am completed my training , now i want to test the model, so please help me.

**Comment by VoIlAlex** [comment]
After training, you will have a file called similar to `faster_rcnn_1_19_10021.pth`. Here:
* `1` - session
* `19` - epoch
* `10021` - checkpoints

So the script for starting test session will look as following:
```bash
SESSION=1
EPOCH=19
CHECKPOINT=10021

python3 test_net.py --dataset pascal_voc --net vgg16 \
                   --checksession $SESSION --checkepoch $EPOCH --checkpoint $CHECKPOINT \
                   --cuda
```
if you trained your model on the `pascal_voc` dataset as shown in the  code snippet from README.md in the **Train** section.

**Comment by devendraswamy** [comment]
Thank so much for valuable information and here which parameters I have to
tune , how can I get the best accuracy and please tell me about the tuning
parameters .

**Comment by VoIlAlex** [comment]
You're welcome. Unfortunately, I'm still a beginner so I can't help with parameters' tuning. I faced the same problem related to the session, checkpoint, and checksession and I found a resolution for the issue only half an hour ago. You could search in other issues of the repo. Maybe there you will find something useful about it. Good luck!

**Comment by devendraswamy** [comment]
Thank you for your information 😊👍

**Comment by devendraswamy** [comment]
Hi Bro,
In the past Did you work on Object Detection by using Mask-Rcnn ??

**Comment by VoIlAlex** [comment]
Hey. No, I didn't. This repository is the first implementation of the RCNN family I worked with.

**Comment by devendraswamy** [comment]
could you suggest any documentation on faster rcnn model ??
