### ISSUE TITLE
Error doing the command sh make.sh in lib directory

### ISSUE THREAD

**Issue by pranerd** [jwyang/faster-rcnn.pytorch#7]
@jwyang  thanks for sharing, but I followed your command, doing the command sh make.sh, but it turn out to be an error? it said that: 
1. gcc: error: /home/xzj/workspace/faster-rcnn.pytorch/lib/model/nms/src/nms_cuda.c: No such file or directory
2./home/xzj/workspace/faster-rcnn.pytorch/lib/model/roi_pooling/src/roi_pooling_cuda.c:3:37: fatal error: cuda/roi_pooling_kernel.h: No such file or directory
my python version is 2.7, mvcc version isrelease 9.0, V9.0.176, pytorch version is 0.2.0_3

**Comment by jwyang** [comment]
Hi, @pranerd , thanks for posting these errors. I have addressed them. Have a try to compile again.

**Comment by pranerd** [comment]
thank you. the code run OK @jwyang .

**Comment by jwyang** [comment]
great!
