### ISSUE TITLE
own dataset training and testing

### ISSUE THREAD

**Issue by devendraswamy** [jwyang/faster-rcnn.pytorch#700]
Actually I have my own dataset in format of ["filename"    "boxes label values Like x-min y-min x-max y-max"    "class-name"] and filename consist the path of the image, so how can given this dataset to model for testing and training , please anybody help me ..

**Comment by CharlesPikachu** [comment]
maybe you could use my code: https://github.com/DetectionBLWX/FasterRCNN.pytorch
the code is clean enough so that easier to understand and modify
you could define a new dataset class in modules/utils/datasets to parse your own dataset

**Comment by devendraswamy** [comment]
Thank you so much for your valuable reply and one more doubt , do please
help me.

How can I change my faster rcnn model parameters and which parameters I
have to tuning ?

Thanking you!

**Comment by CharlesPikachu** [comment]
you could rewrite modules/fasterRCNN.py  line 308-323 to choose the parameters for tuning.

**Comment by devendraswamy** [comment]
Thank you very much for your reply and one more doubt please help me , in training expect that bounding boxes , shall i give segmentation to the training model , if is possible please help me.
