### ISSUE TITLE
The result is better than faster-rcnn mxnet official version.

### ISSUE THREAD

**Issue by hdjsjyl** [jwyang/faster-rcnn.pytorch#71]
Thanks for your code. It gets good results for face. However, faster-rcnn mxnet version is worse than your code. Do you use some other tricks or methods other than official faster-rcnn? Thank you very much.

**Comment by jwyang** [comment]
Hi, @hdjsjyl , actually, we did not use some specific tricks or methods compared with official one. How much is the gap?

**Comment by hdjsjyl** [comment]
@jwyang , For wider face dataset, easy part 0.885-0.901, medium part 0.797-0.845, hard part 0.421-0.552. I think the gap is big for medium and hard parts.

**Comment by jwyang** [comment]
@hdjsjyl , I see, I think it might because the difference on data loader. In our implementation, we did not resize images, but kept the aspect ratio of input images, as much as possible.

**Comment by hdjsjyl** [comment]
@jwyang , ok, I will check the code. thank you very much

**Comment by jwyang** [comment]
@hdjsjyl maybe another reason is the evaluation parameters are different. Also check that.

**Comment by hdjsjyl** [comment]
@jwyang , thanks for your advice. I have checked it and am trying to implement it on my code. Happy chinese new year!

**Comment by jwyang** [comment]
@hdjsjyl , thanks! I guess you are also a Chinese, right? Happy Chinese new year!

**Comment by hdjsjyl** [comment]
@jwyang yes, I am a chinese.

**Comment by jwyang** [comment]
Great, enyjoy the holiday!

**Comment by hdjsjyl** [comment]
You too
