### ISSUE TITLE
 error: command u'/usr/local/cuda/bin/nvcc' failed with exit status 1

### ISSUE THREAD

**Issue by Songtingt** [jwyang/faster-rcnn.pytorch#719]
when i run this step:
cd lib
python setup.py build develop

I meet this problem : error: command u'/usr/local/cuda/bin/nvcc' failed with exit status 1
how can i solve it?

**Comment by Songtingt** [comment]
By downgrading my gcc from 6.5 to 5.4 ,
it seems run successfully!!!!!

**Comment by DanZhang123** [comment]
你好，我的问题跟你一样，请问你怎么把gcc的版本从6.5降低到5.4的啊

**Comment by Songtingt** [comment]
> 你好，我的问题跟你一样，请问你怎么把gcc的版本从6.5降低到5.4的啊

你找找教程哇 我也忘了我在网上找的哪个教程了 sorry

**Comment by Songtingt** [comment]
> 你好，我的问题跟你一样，请问你怎么把gcc的版本从6.5降低到5.4的啊

你找找教程哇，我也忘记我看的哪个教程了 
我随便搜了一个 你可以试一试
https://blog.csdn.net/betty13006159467/article/details/78394974?utm_medium=distribute.pc_relevant_t0.none-task-blog-BlogCommendFromMachineLearnPai2-1.channel_param&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-BlogCommendFromMachineLearnPai2-1.channel_param
