### ISSUE TITLE
Error in loading pretrained weights

### ISSUE THREAD

**Issue by JavHaro** [jwyang/faster-rcnn.pytorch#72]
I'm quite new on pytorch and cnn in general so maybe my error is quite simple. I'm trying to train with vgg16 on pascal_voc as a previous step to train with my own dataset. The problem is that when i execute 
trainval_net the program don't finish. The last thing that i see in command line is 

> Loading weights from data/pretrained_model/vgg16_caffe.pth

I have 1 GPU (Titan k80) and i'm executing the code with python 3.5.2 (from Jupyter). The call is the next one:
`%run -i trainval_net_py3.py --dataset pascal_voc --net vgg16 \
--bs 4 --nw 1 \
--lr $LEARNING_RATE --lr_decay_step $DECAY_STEP \
--cuda `

LEARNING_RATE=0.001
DECAY_STEP=5

It seems like the loop never ends.
Thanks in advance for your support

**Comment by JavHaro** [comment]
Now i know what happends!
my disk is full because i'm storing all the generated models. I guess i can save only a few models to compare performance. Am I right?

**Comment by JavHaro** [comment]
I think you can close it. Thanks!!

**Comment by jwyang** [comment]
@JavHaro glad you solved it, closing now
