### ISSUE TITLE
sh make.sh error

### ISSUE THREAD

**Issue by adamlrza** [jwyang/faster-rcnn.pytorch#727]
Hi

I am new to object detection. I have a dataset in pascal voc format that I want to use to train an object detection model. I downloaded the repository. However when I do sh make.sh (bash make.sh since im on windows) i get the following errors. I downloaded the prequisites and tried to follow the instructions as close as possible. I am not sure why I get these errors when I do have numpy pytorch and etc installed.

Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import numpy as np
ImportError: No module named numpy
Compiling nms kernels by nvcc...
make.sh: line 26: nvcc: command not found
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch
ImportError: No module named torch
Compiling roi pooling kernels by nvcc...
make.sh: line 36: nvcc: command not found
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch
ImportError: No module named torch
Compiling roi align kernels by nvcc...
make.sh: line 45: nvcc: command not found
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch
ImportError: No module named torch
Compiling roi crop kernels by nvcc...
make.sh: line 54: nvcc: command not found
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch
ImportError: No module named torch

**Comment by Aurorayy** [comment]
i have the same problem..
have you ever fixed this problem?
