### ISSUE TITLE
ImportError: cannot import name 'imread'

### ISSUE THREAD

**Issue by Alan-D-Chen** [jwyang/faster-rcnn.pytorch#736]
Traceback (most recent call last):
  File "trainval_net.py", line 28, in <module>
    from roi_data_layer.roibatchLoader import roibatchLoader
  File "/home/alanchen/Desktop/faster-rcnn.pytorch/lib/roi_data_layer/roibatchLoader.py", line 14, in <module>
    from roi_data_layer.minibatch import get_minibatch, get_minibatch
  File "/home/alanchen/Desktop/faster-rcnn.pytorch/lib/roi_data_layer/minibatch.py", line 15, in <module>
    from scipy.misc import imread
ImportError: cannot import name 'imread'

**Comment by Alan-D-Chen** [comment]
To deal with that "ImportError: cannot import name 'imread'":
>>>
This bug is mainly because the versions of the "scipy" library and the "pillow" library do not match.
I got this bug, which is caused by too high version of "scipy" library. My version matches the following:

Point installation scipy == 1.2.1
Point mounting pillow == 6.1.0

>>>
step 1 input "pip list" to check out scipy version
step 2  turn scipy x.x.x into scipy 1.2.1
BOOM
Finshed.

**Comment by 520Chris** [comment]
Please close your now that it has been solved.
