### ISSUE TITLE
difference between ResNet implementation with TorchVision

### ISSUE THREAD

**Issue by EMCP** [jwyang/faster-rcnn.pytorch#750]
Noticed that in PyTorch 1.3 and TorchVision 0.4.x , we get a ResNet that is slightly different from the implementation here.. should it be safe to port to the new version ?

`torchvision.models.resnet` on the left  `model/faster_rcnn/resnet.py` on the right 

![Screen Shot 2020-01-13 at 10 49 06 PM](https://user-images.githubusercontent.com/3691722/72295185-4bccf780-3657-11ea-8fda-6a2796536297.png)

**Comment by loolzaaa** [comment]
May be too late, but i [implement this net](https://github.com/loolzaaa/faster-rcnn-pytorch) with torchvision backbones of VGG16 and ResNet networks.

Results (VOC 2007) are the same:
- VGG16 70,9%
- ResNet50 73,1%
- ResNet101 74,5%
