### ISSUE TITLE
assert all(max_classes[nonzero_inds] != 0)

### ISSUE THREAD

**Issue by Yuui-Asuka** [jwyang/faster-rcnn.pytorch#753]
When I tried to use my own dateset for training, an assert exception occurred: assert all(max_classes[nonzero_inds] != 0). 
I updated lib/datasets/pascal_voc/self._classes to my own classes, but the exception still occurred.
Then I tried to comment out this assertion, but when training started, another exception occurred: ValueError: bg_num_rois = 0 and fg_num_rois = 0, this should not happen!
How can I solve this problem?

**Comment by devendraswamy** [comment]
given classes must be had "background" in 0th index only , like ["background" , "cls1" ,cls2"]

**Comment by syed-javed** [comment]
How did you solve this issue? was it solved?

**Comment by skyandkibo** [comment]
After modifying the category (i.e. adding background), you need to delete the data/cache/xxx.pkl if it exists.
