### ISSUE TITLE
 error: invalid command 'develop'

### ISSUE THREAD

**Issue by chexqi** [jwyang/faster-rcnn.pytorch#754]

**Comment by DJever23** [comment]
hello，I have the same problem, how did you resolve this? Thanks

**Comment by RY321** [comment]
how did you resolve this?

**Comment by shuang1204** [comment]
我也遇到了同样的问题，请问您是怎么解决的@chexqi

**Comment by zyfone** [comment]
将setup.py中的
from distutils.core import setup
修改为
from setuptools import setup

**Comment by zyfone** [comment]
将setup.py中的
from distutils.core import setup
修改为
from setuptools import setup
