### ISSUE TITLE
RuntimeError: inconsistent tensor size

### ISSUE THREAD

**Issue by mikeliao97** [jwyang/faster-rcnn.pytorch#77]
Hi!
Thanks for making this implementation available! I'm having a bit of trouble making it work. I'm using Pytorch + Cudnn 8.0 + python2.7 testing on pascalvoc2007
_
![screen shot 2018-02-21 at 1 09 04 am](https://user-images.githubusercontent.com/10099855/36471655-10c7a452-16a4-11e8-9267-3e1a00bbde30.png)
_

I'm getting an inconsistent tensor size error that I can't seem to fix.

The command I ran was: sudo $(which python) trainval_net.py --dataset pascal_voc --net res101  --lr 0.001  --lr_decay_step 4 --cuda

**Comment by jwyang** [comment]
Hi, @mikeliao97 , have you addressed this issue?
