### ISSUE TITLE
Can an outputted model be used for further training? 

### ISSUE THREAD

**Issue by valeria-alex** [jwyang/faster-rcnn.pytorch#779]
How can I use the resulted model after training Vgg16 on my own dataset?

I would like to train the resulted model on a different dataset but I can't seem to figure out how to write the new model script. 
I get this error
`    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VGG:
	Missing key(s) in state_dict: "features.0.bias", "features.0.weight", "features.2.bias", "features.2.weight", "features.5.bias", "features.5.weight", "features.7.bias", "features.7.weight", "features.10.bias", "features.10.weight", "features.12.bias", "features.12.weight", "features.14.bias", "features.14.weight", "features.17.bias", "features.17.weight", "features.19.bias", "features.19.weight", "features.21.bias", "features.21.weight", "features.24.bias", "features.24.weight", "features.26.bias", "features.26.weight", "features.28.bias", "features.28.weight", "classifier.0.bias", "classifier.0.weight", "classifier.3.bias", "classifier.3.weight", "classifier.6.bias", "classifier.6.weight".`

which is very unexptected (?) I thought that since i'm training it using vgg16 it will keep the vgg16 structure and definitions.

I'm sorry to post this question as an issue, I don't know where else to post it.

I'm trying to say that the new model (after training) does not match the model before training (the one saved in torchvision.models)

**Comment by loolzaaa** [comment]
How are you try to continue learn after first training process?

**Comment by valeria-alex** [comment]
I'm trying to replace the Vgg16 network with my own, retrained network. I tried to make a new script and declare my new network but when trying to import the structure from torch it doesn't match

**Comment by loolzaaa** [comment]
While you train VGG16 on some dataset, network save **checkpoint** every epoch in output_dir with name `frcnn_<session>_<epoch>_<checkpoint>.pth`. After end of train process, you can:

- **RESUME** to training (see `--resume` flag in train script)
- change path to pretrain_model in train script, but after loading checkpoint, you need to get a model state dict.
```python
PATH_TO_PRETRAIN_MODEL = ......................
checkpoint = torch.load(PATH_TO_PRETRAIN_MODEL)
state_dict = checkpoint['model']
backbone.load_state_dict({k:v for k,v in state_dict.items() if k in backbone.state_dict()})
```
**NOTE:** Network save in checkpoint not only weights for a model, but also optimizer state parameters. Its need to resume train.

**Comment by valeria-alex** [comment]
Thank you, 
I will try that and report back in < 24h
if it works I will close the issue

**Comment by valeria-alex** [comment]
Sorry I don't actually understand :(

So, what I'm trying to do is: after i've trained a network and i"ve got a result: faster_rcnn_1_1_0.pth  I want to use this .pth for another session of training on another dataset. 
Note: that is not the actual name of the file, I've changed it to that because I would get this error: 
`IOError: [Errno 2] No such file or directory: 'models/vgg16/rgz/faster_rcnn_1_1_0.pth'
` 
even tho my input was: 
`--r 1_3_9377
`
The result of resume after is: 
`Loading pretrained weights from data/pretrained_model/vgg16_caffe.pth
loading checkpoint models/vgg16/rgz/faster_rcnn_1_1_0.pth
loaded checkpoint models/vgg16/rgz/faster_rcnn_1_1_0.pth
(pytorch-env) q@q:~/catkin_ws/src/faster-rcnn.pytorch$ 
`

So it just exits after loading the model (?)


Regarding your second bullet, I'm sorry I don't understand. I'm quite new to this. 
Do you mean that I should add those lines to [trainval_net](https://github.com/jwyang/faster-rcnn.pytorch/blob/master/trainval_net.py#L279)? 

Or to create a new file similar to the [vgg model](https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/model/faster_rcnn/vgg16.py#L32)?


The problem that I have when trying to create my own version of the vgg16.py is with loading this [model type](https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/model/faster_rcnn/vgg16.py#L29), because the model that I am adding here [model path](https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/model/faster_rcnn/vgg16.py#L21) is not recognized in line 29 as it not part of the torch models [imported here](https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/model/faster_rcnn/vgg16.py#L15).

It will just give me an error when the compiler reaches line 29.


Thank you so much for your time, I hope I explained it well enough.

**Comment by loolzaaa** [comment]
So... let's start from begin))

- You start `trainval_net.py` script and train VGG16 net for some epochs. Every epoch, network save a checkpoint as i said above
- Saved file has weights for network and optimizer state. In order to use only weight as pretrain you need only weights from file. So, i suggest two option:
1. Save next script in any python file:
```python
import os
import torch

model_path = os.path.join('directory', 'to', 'your', 'checkpoint.pth')
output_path = os.path.join('directory', 'to', 'data', 'pretrained_model')
assert os.path.exists(model_path), 'Path doesn't exist {}'.format(model_path)
assert os.path.exists(output_path), 'Path doesn't exist {}'.format(output_path)
checkpoint = torch.load(model_path)
torch.save(checkpoint['model'], os.path.join(output_path, 'vgg16_new.pth')
```
- Change `model_path` and `output_path` to yours
- run script
- Change [this](https://github.com/jwyang/faster-rcnn.pytorch/blob/6f0c63b64dde6dc4eb3e24f90650d789f96f4c75/lib/model/faster_rcnn/vgg16.py#L21) line to `self.model_path = 'data/pretrained_model/vgg16_new.pth'`
- start train on another dataset

2. Change sources for correct checkpoint loading:
- change [this](https://github.com/jwyang/faster-rcnn.pytorch/blob/6f0c63b64dde6dc4eb3e24f90650d789f96f4c75/lib/model/faster_rcnn/vgg16.py#L21) line to `self.model_path = 'path/to/your/checkpoint.pth'`
- change [this](https://github.com/jwyang/faster-rcnn.pytorch/blob/6f0c63b64dde6dc4eb3e24f90650d789f96f4c75/lib/model/faster_rcnn/vgg16.py#L32) line to `state_dict = torch.load(self.model_path)['model']`

**Comment by valeria-alex** [comment]
I tried option #2 
So now my vgg16.py looks like this: 
`class vgg16(_fasterRCNN):
  def __init__(self, classes, pretrained=False, class_agnostic=False):
    self.model_path = 'data/pretrained_model/faster_rcnn_1_3_9377.pth'#'vgg16_caffe.pth'
    self.dout_base_model = 512
    self.pretrained = pretrained
    self.class_agnostic = class_agnostic

    _fasterRCNN.__init__(self, classes, class_agnostic)

  def _init_modules(self):
    vgg = models.vgg16()
    if self.pretrained:
        print("Loading pretrained weights from %s" %(self.model_path))
        state_dict = torch.load(self.model_path)['model']
        vgg.load_state_dict({k:v for k,v in state_dict.items() if k in vgg.state_dict()})`


But I still get the same error: 
`Loading pretrained weights from data/pretrained_model/faster_rcnn_1_3_9377.pth
Traceback (most recent call last):
  File "trainval_net.py", line 257, in <module>
    fasterRCNN.create_architecture()
  File "/home/q/catkin_ws/src/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 135, in create_architecture
    self._init_modules()
  File "/home/q/catkin_ws/src/faster-rcnn.pytorch/lib/model/faster_rcnn/vgg16.py", line 33, in _init_modules
    vgg.load_state_dict({k:v for k,v in state_dict.items() if k in vgg.state_dict()})
  File "/home/q/environments/pytorch-env/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VGG:
	Missing key(s) in state_dict: "features.0.bias", "features.0.weight", "features.2.bias", "features.2.weight", "features.5.bias", "features.5.weight", "features.7.bias", "features.7.weight", "features.10.bias", "features.10.weight", "features.12.bias", "features.12.weight", "features.14.bias", "features.14.weight", "features.17.bias", "features.17.weight", "features.19.bias", "features.19.weight", "features.21.bias", "features.21.weight", "features.24.bias", "features.24.weight", "features.26.bias", "features.26.weight", "features.28.bias", "features.28.weight", "classifier.0.bias", "classifier.0.weight", "classifier.3.bias", "classifier.3.weight", "classifier.6.bias", "classifier.6.weight". 
`
and i've also tried the 1st option: i've saved a new network using:
`import os
import torch

model_path = os.path.join('/home/q/catkin_ws/src/faster-rcnn.pytorch/data/pretrained_model/faster_rcnn_1_3_9377.pth')
output_path = os.path.join('/home/q/catkin_ws/src/faster-rcnn.pytorch/output/vgg16')
assert os.path.exists(model_path), 'Path doesnt exist {}'.format(model_path)
assert os.path.exists(output_path), 'Path doesnt exist {}'.format(output_path)
checkpoint = torch.load(model_path)
torch.save(checkpoint['model'], os.path.join(output_path, 'vgg16_new.pth'))
`
copied the new network from the output folder to the pretrained_model
then I've replaced
  `self.model_path = 'data/pretrained_model/vgg16_new.pth'#'vgg16_caffe.pth'` 
but I got the same error

**Comment by loolzaaa** [comment]
> I should probably mention that I am using Pytorch 0.4.0. I will try to upgrade to 1.0 and see how that goes

Update python to 3.x version and PyTorch to 1.x version (PyTorch 1.x doesn't support python 2.x)

**Comment by valeria-alex** [comment]
That doesn't seem to work either

Silly question but have you ever tried to train on VGG then retrain the resulted network?

**Comment by loolzaaa** [comment]
Oh, sorry, that my mistake. After training, network save checkpoint **NOT** for backbone (VGG16 or ResNet). It save it for faster_rcnn net, so you need to load weights not for VGG16!

You need to use `resume` section of train_val.py script.

Another words, you need to run `load_state_dict()` not for VGG16 or another backbone and for faster_rcnn after creating it.

**Comment by loolzaaa** [comment]
In your situation, you can just add next code after [this](https://github.com/jwyang/faster-rcnn.pytorch/blob/6f0c63b64dde6dc4eb3e24f90650d789f96f4c75/trainval_net.py#L249) line:
```python
fasterRCNN.create_architecture() # <---- after this line
load_name = os.path.join(output_dir, 'your_checkpoint.pth')
checkpoint = torch.load(load_name)
fasterRCNN.load_state_dict(checkpoint['model'])
```

**Comment by valeria-alex** [comment]
Alright!

When I had this error 
`Loading pretrained weights from data/pretrained_model/vgg16_caffe.pth loading checkpoint models/vgg16/rgz/faster_rcnn_1_1_0.pth loaded checkpoint models/vgg16/rgz/faster_rcnn_1_1_0.pth (pytorch-env) q@q:~/catkin_ws/src/faster-rcnn.pytorch$`

it was because I did not change the epoch number in the beginning of the code,
`  parser.add_argument('--epochs', dest='max_epochs',
                      help='number of epochs to train',
                      default=1, type=int)`

 so it stopped because it had already done 1 epoch. 

All I had to change now was [this line](https://github.com/jwyang/faster-rcnn.pytorch/blob/6f0c63b64dde6dc4eb3e24f90650d789f96f4c75/trainval_net.py#L276) to 
`load_name = os.path.join(output_dir, 'your_checkpoint.pth')`

For some reason it was not loading it properly (or i don't know how to input the proper args)

Thank you so much for babysitting me, it seems to work now :)

One question: if during the first round of training I set [the gradient](https://github.com/jwyang/faster-rcnn.pytorch/blob/6f0c63b64dde6dc4eb3e24f90650d789f96f4c75/lib/model/faster_rcnn/vgg16.py#L42) to True such that I train the whole network and then I set it to False such that the second time I train I only do it for the RCNN it will give me 

`    raise ValueError("loaded state dict has a different number of "
ValueError: loaded state dict has a different number of parameter groups`

Any idea how I could avoid this?

I want to train the whole network on a dataset (with simulated data) and then only train the RCNN layers on a new dataset (with real life data, which I have very little of).

**Comment by loolzaaa** [comment]
> it was because I did not change the epoch number in the beginning of the code,

You don't need to change this code, this is parameter parser. Just set `--checksession`, `--checkepoch`, `--checkpoint` in start command. Example:
```
/dir/python trainval_net.py --checksession 1 --checkepoch 6 --checkpoint 11022
```
> All I had to change now was this line to

If you add piece of code as i said above, you don't need to change `resume` section of script.
And of course, don't forget to change `your_checkpoint` to your checkpoint filename 😃 

> if during the first round of training I set the gradient to True

**Not** set this to True even for "first round" of training. This part of code freeze first 10 layers, because **they don't affect on network performance, but without them, training is faster**.

If you want train **only classifier**, then you can change [this](https://github.com/jwyang/faster-rcnn.pytorch/blob/6f0c63b64dde6dc4eb3e24f90650d789f96f4c75/lib/model/faster_rcnn/vgg16.py#L41-L42) lines to:
```python
for layer in self.RCNN_base:
    for p in layer.parameters(): p.requires_grad = False
```
> I've commented out this line and it works

As i said above. You don't need to turn *resume* flag on if add load checkpoint code after `create_architecture()` method.

**Comment by valeria-alex** [comment]
Oh, I see
I didn't know how to parse the arguments properly. 

Thank you. Everything seems ok now :)
