### ISSUE TITLE
Inconsistant tensor size

### ISSUE THREAD

**Issue by hazirbas** [jwyang/faster-rcnn.pytorch#78]
Hi,
I tested demo.py in cuda 9.1 with pytorch 0.3.1 and the following line raised an error.
https://github.com/jwyang/faster-rcnn.pytorch/blob/2f7b53c9313cdb73325cf0ff35cc6a3efb4601a5/demo.py#L311

Quick fix is as follows:
`torch.cat((cls_boxes, cls_scores.unsqueeze(1)), 1)`

This error also occurs at
https://github.com/jwyang/faster-rcnn.pytorch/blob/2f7b53c9313cdb73325cf0ff35cc6a3efb4601a5/test_net.py#L288

**Comment by jwyang** [comment]
thanks a lot, @hazirbas , will fix that.

**Comment by jwyang** [comment]
done, closing this issue, thanks again!
