### ISSUE TITLE
Computation of l1 loss

### ISSUE THREAD

**Issue by chinmay5** [jwyang/faster-rcnn.pytorch#780]
According to the paper, smooth l1 loss is calculated only in cases where there is label of 1 (ie foreground object). However, looking at the code, I saw only a check for `label != -1` and then loss is computed directly [here](https://github.com/jwyang/faster-rcnn.pytorch/blob/358cecacf876717ff13988dc6396de10e265279c/lib/model/rpn/rpn.py#L107).

Can you please tell me where this check is done or if there is some mistake in my understanding of the paper.

**Comment by loolzaaa** [comment]
As you can see [here](https://github.com/jwyang/faster-rcnn.pytorch/blob/358cecacf876717ff13988dc6396de10e265279c/lib/model/utils/net_utils.py#L76) different between prediction and ground truth multiply by `bbox_inside_weights`. 
This weights was created in *Anchor target layer* [here](https://github.com/jwyang/faster-rcnn.pytorch/blob/358cecacf876717ff13988dc6396de10e265279c/lib/model/rpn/anchor_target_layer.py#L95), all weight =0 at start. 
After that, we [apply](https://github.com/jwyang/faster-rcnn.pytorch/blob/358cecacf876717ff13988dc6396de10e265279c/lib/model/rpn/anchor_target_layer.py#L153) weights =1 only for `labels==1`.

**Comment by chinmay5** [comment]
@loolzaaa thank you so much for the explanation
