### ISSUE TITLE
FileNotFoundError: [Errno 2] when test own dataset

### ISSUE THREAD

**Issue by kiosy** [jwyang/faster-rcnn.pytorch#782]
python test_net.py --dataset pascal_voc --net vgg16 \--checksession 1 --checkepoch 100 --checkpoint 75 
Called with args:
Namespace(cfg_file='cfgs/vgg16.yml', checkepoch=100, checkpoint=75, checksession=1, class_agnostic=False, cuda=False, dataset='pascal_voc', large_scale=False, load_dir='models', mGPUs=False, net='vgg16', parallel_type=0, set_cfgs=None, vis=False)
WARNING: You have a CUDA device, so you should probably run with --cuda
Using config:
{'ANCHOR_RATIOS': [0.5, 1, 2],
 'ANCHOR_SCALES': [8, 16, 32],
 'CROP_RESIZE_WITH_MAX_POOL': False,
 'CUDA': False,
 'DATA_DIR': '/home/uestc/airport_FOD/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'vgg16',
 'FEAT_STRIDE': [16],
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MAX_NUM_GT_BOXES': 20,
 'MOBILENET': {'DEPTH_MULTIPLIER': 1.0,
               'FIXED_LAYERS': 5,
               'REGU_DEPTH': False,
               'WEIGHT_DECAY': 4e-05},
 'PIXEL_MEANS': array([[[102.9801, 115.9465, 122.7717]]]),
 'POOLING_MODE': 'align',
 'POOLING_SIZE': 7,
 'RESNET': {'FIXED_BLOCKS': 1, 'MAX_POOL': False},
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/uestc/airport_FOD',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'MODE': 'nms',
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'gt',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'RPN_TOP_N': 5000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': False,
           'BATCH_SIZE': 256,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'BIAS_DECAY': False,
           'BN_TRAIN': False,
           'DISPLAY': 10,
           'DOUBLE_BIAS': True,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'LEARNING_RATE': 0.01,
           'MAX_SIZE': 1000,
           'MOMENTUM': 0.9,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 8,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_ITERS': 5000,
           'SNAPSHOT_KEPT': 3,
           'SNAPSHOT_PREFIX': 'res101_faster_rcnn',
           'STEPSIZE': [30000],
           'SUMMARY_INTERVAL': 180,
           'TRIM_HEIGHT': 600,
           'TRIM_WIDTH': 600,
           'TRUNCATED': False,
           'USE_ALL_GT': True,
           'USE_FLIPPED': True,
           'USE_GT': False,
           'WEIGHT_DECAY': 0.0005},
 'USE_GPU_NMS': True}
Loaded dataset `voc_2007_test` for training
Set proposal method: gt
Preparing training data...
Traceback (most recent call last):
  File "test_net.py", line 140, in <module>
    imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdbval_name, False)
  File "/home/faster-rcnn/lib/roi_data_layer/roidb.py", line 116, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/faster-rcnn/lib/roi_data_layer/roidb.py", line 116, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/faster-rcnn/lib/roi_data_layer/roidb.py", line 113, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/faster-rcnn/lib/roi_data_layer/roidb.py", line 102, in get_training_roidb
    prepare_roidb(imdb)
  File "/home/faster-rcnn/lib/roi_data_layer/roidb.py", line 21, in prepare_roidb
    roidb = imdb.roidb
  File "/home/faster-rcnn/lib/datasets/imdb.py", line 76, in roidb
    self._roidb = self.roidb_handler()
  File "/home/faster-rcnn/lib/datasets/pascal_voc.py", line 129, in gt_roidb
    for index in self.image_index]
  File "/home/faster-rcnn/lib/datasets/pascal_voc.py", line 129, in <listcomp>
    for index in self.image_index]
  File "/home/faster-rcnn/lib/datasets/pascal_voc.py", line 208, in _load_pascal_annotation
    tree = ET.parse(filename)
  File "/home/anaconda3/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/home/anaconda3/lib/python3.6/xml/etree/ElementTree.py", line 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/faster-rcnn/data/VOCdevkit2007/VOC2007/Annotations/.xml'

the path is right and the xml files exist, I can run train and demo, only test is wrong

**Comment by loolzaaa** [comment]
> the xml files exist

In error  there is no file name. Looks like edited image set txt, because:
```python
filename = os.path.join(self._data_path, 'Annotations', index + '.xml')
```
I think index = ''.

Try to look in devkit path -> voc2007 -> imagesets -> main -> test.txt and remove last empty string.

**Comment by kiosy** [comment]
> > the xml files exist
> 
> In error there is no file name. Looks like edited image set txt, because:
> 
> ```python
> filename = os.path.join(self._data_path, 'Annotations', index + '.xml')
> ```
> 
> I think index = ''.
> 
> Try to look in devkit path -> voc2007 -> imagesets -> main -> test.txt and remove last empty string.

it works, THANK YOU SO MUCH!!!
