### ISSUE TITLE
how to infer one custom image with pre-trained model

### ISSUE THREAD

**Issue by ZhuYun97** [jwyang/faster-rcnn.pytorch#783]
If I want to test my own image, how to operate it? Do I need to create a tool to realize it?

**Comment by loolzaaa** [comment]
Do you need to test your image on classes of one of the already implemented datasets?

**Comment by ZhuYun97** [comment]
> Do you need to test your image on classes of one of the already implemented datasets?

yes

**Comment by loolzaaa** [comment]
So, just do what describe [here](https://github.com/jwyang/faster-rcnn.pytorch/tree/pytorch-1.0#demo).

**Comment by ZhuYun97** [comment]
Thanks a lot. But I make an essential mistake. I have should propose this issue in [another repo](https://github.com/jwyang/graph-rcnn.pytorch). Do you have any experience with [this project](https://github.com/jwyang/graph-rcnn.pytorch) and please give me a hand if you have any ideas.
