### ISSUE TITLE
torch.utils.ffi is deprecated， How to solve？

### ISSUE THREAD

**Issue by natureXD** [jwyang/faster-rcnn.pytorch#790]
When I run the training command，it throw error like this.
But I do not want to change my pytorch 1.1.0 to 0.4, how should I do to solve this problem?

> Traceback (most recent call last):
>   File "trainval_net.py", line 30, in <module>
>     from model.utils.net_utils import weights_normal_init, save_net, load_net, \
>   File "/home_disk1/yolo_test/detection_maskRCNN/faster_rcnn/faster-rcnn.pytorch/lib/model/utils/net_utils.py", line 8, in <module>
>     from model.roi_crop.functions.roi_crop import RoICropFunction
>   File "/home_disk1/yolo_test/detection_maskRCNN/faster_rcnn/faster-rcnn.pytorch/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
>     from .._ext import roi_crop
>   File "/home_disk1/yolo_test/detection_maskRCNN/faster_rcnn/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 2, in <module>
>     from torch.utils.ffi import _wrap_function
>   File "/root/anaconda3/lib/python3.5/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
>     raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
> ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
> root@00c951be80a1:/home_disk1/yolo_test/detection_maskRCNN/faster_rcnn/faster-rcnn.pytorch# vim lib/model/roi_crop/_ext/roi_crop/__init__.py

**Comment by loolzaaa** [comment]
Change branch of this repo to PyTorch-1.0 and follow readme

**Comment by natureXD** [comment]
> o

I am using the repo to PyTorch-1.0

But it throw error in ROOT/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 2, in <module>
    from torch.utils.ffi import _wrap_function

**Comment by loolzaaa** [comment]
You need to check branch.

Your error:
>File "/home_disk1/yolo_test/detection_maskRCNN/faster_rcnn/faster-rcnn.pytorch/**lib/model/utils/net_utils.py**", line 8, in
**from model.roi_crop.functions.roi_crop import RoICropFunction**

[Code](https://github.com/jwyang/faster-rcnn.pytorch/blob/31ae20687b1b3486155809a57eeb376259a5f5d4/lib/model/utils/net_utils.py#L8) from **net_utils** PyTorch 0.4 branch:
```python
from model.roi_crop.functions.roi_crop import RoICropFunction
```

[Part of imports](https://github.com/jwyang/faster-rcnn.pytorch/blob/6f0c63b64dde6dc4eb3e24f90650d789f96f4c75/lib/model/utils/net_utils.py#L1-L10) from **net_utils** PyTorch 1.0 branch:
```python
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
import numpy as np
import torchvision.models as models
from model.utils.config import cfg
import cv2
import pdb
import random
```
So, there is no **roi_crop** imports in Pytorch-1.0 branch.

**Comment by natureXD** [comment]
> You need to check branch.
> 
> Your error:
> 
> > File "/home_disk1/yolo_test/detection_maskRCNN/faster_rcnn/faster-rcnn.pytorch/**lib/model/utils/net_utils.py**", line 8, in
> > **from model.roi_crop.functions.roi_crop import RoICropFunction**
> 
> [Code](https://github.com/jwyang/faster-rcnn.pytorch/blob/31ae20687b1b3486155809a57eeb376259a5f5d4/lib/model/utils/net_utils.py#L8) from **net_utils** PyTorch 0.4 branch:
> 
> ```python
> from model.roi_crop.functions.roi_crop import RoICropFunction
> ```
> 
> [Part of imports](https://github.com/jwyang/faster-rcnn.pytorch/blob/6f0c63b64dde6dc4eb3e24f90650d789f96f4c75/lib/model/utils/net_utils.py#L1-L10) from **net_utils** PyTorch 1.0 branch:
> 
> ```python
> import torch
> import torch.nn as nn
> import torch.nn.functional as F
> from torch.autograd import Variable
> import numpy as np
> import torchvision.models as models
> from model.utils.config import cfg
> import cv2
> import pdb
> import random
> ```
> 
> So, there is no **roi_crop** imports in Pytorch-1.0 branch.

Thank you very much. My problem has been solved. I do make the wrong operation using branch pytorch-0.4 with no consciousness.

**Comment by loolzaaa** [comment]
> My problem has been solved.

Don't forget to close the issue. 👍

**Comment by dreamedrainbow** [comment]
> > You need to check branch.
> > Your error:
> > > File "/home_disk1/yolo_test/detection_maskRCNN/faster_rcnn/faster-rcnn.pytorch/**lib/model/utils/net_utils.py**", line 8, in
> > > **from model.roi_crop.functions.roi_crop import RoICropFunction**
> > 
> > 
> > [Code](https://github.com/jwyang/faster-rcnn.pytorch/blob/31ae20687b1b3486155809a57eeb376259a5f5d4/lib/model/utils/net_utils.py#L8) from **net_utils** PyTorch 0.4 branch:
> > ```python
> > from model.roi_crop.functions.roi_crop import RoICropFunction
> > ```
> > 
> > 
> > [Part of imports](https://github.com/jwyang/faster-rcnn.pytorch/blob/6f0c63b64dde6dc4eb3e24f90650d789f96f4c75/lib/model/utils/net_utils.py#L1-L10) from **net_utils** PyTorch 1.0 branch:
> > ```python
> > import torch
> > import torch.nn as nn
> > import torch.nn.functional as F
> > from torch.autograd import Variable
> > import numpy as np
> > import torchvision.models as models
> > from model.utils.config import cfg
> > import cv2
> > import pdb
> > import random
> > ```
> > 
> > 
> > So, there is no **roi_crop** imports in Pytorch-1.0 branch.
> 
> Thank you very much. My problem has been solved. I do make the wrong operation using branch pytorch-0.4 with no consciousness.

How did you solve the problem? Simply delete this sentence?
