### ISSUE TITLE
rpn_cls: nan, rpn_box: nan, rcnn_cls: nan, rcnn_box nan

### ISSUE THREAD

**Issue by JayAust** [jwyang/faster-rcnn.pytorch#797]
When I use pytorch-1.0 version train my own dataset I got upon results when epoch>=2 , No matter how I adjust lr, I can't get the correct result. The specific results are as follows：
[session 1][epoch  1][iter    0/  88] loss: 4.7430, lr: 1.00e-04
			fg/bg=(1/0), time cost: 0.255251
			rpn_cls: 0.7192, rpn_box: 0.1429, rcnn_cls: 0.7797, rcnn_box 3.1013
save model: models/res101/pascal_voc/faster_rcnn_1_1_87.pth
[session 1][epoch  2][iter    0/  88] loss: nan, lr: 1.00e-04
			fg/bg=(1/0), time cost: 0.244978
			rpn_cls: nan, rpn_box: nan, rcnn_cls: nan, rcnn_box nan
I wonder if you can point out the reason for such an error and the corresponding solution, thanks a lot

**Comment by JayAust** [comment]
I found a label coordinate lower than 0 in the label of my data set. When I modified this coordinate, I got the correct running result. If you also encounter the same problem, and you still can't get the correct results after modifying pascal_voc, you can try to check whether your annotation of the data set is correct.

**Comment by abhiagwl4262** [comment]
@JayAust you modified pascal_voc.py, ryt ? I am not able to print x1, y1, x2, y2 in  **_load_pascal_annotation**. Am I looking for right file ?

**Comment by JayAust** [comment]
> @JayAust you modified pascal_voc.py, ryt ? I am not able to print x1, y1, x2, y2 in **_load_pascal_annotation**. Am I looking for right file ?

I modified pascal_voc.py make 1-base to 0-base. I don't know clearly whether you look for right file

**Comment by a-zhenzhen** [comment]
i have the same problem, by this link solved :https://blog.csdn.net/forest_world/article/details/106034880

**Comment by Jason-user** [comment]
If your bbox label have neagtive value it will be calculated as (65536 + value), for example, if your xmin is -1, in this code it will be changed into 65535, which means xmin will bigger than xmax, this is because in "lib/datasets/pascal_voc.py" line 229 author use dtype=np.uint16 to save the value of boxes, force the value being positive, one thing we can do is to replace np.uint16 into np.int32, if your bbox label is negative, it should work.
