### ISSUE TITLE
Stride setting in the last block with ResNet

### ISSUE THREAD

**Issue by clavichord93** [jwyang/faster-rcnn.pytorch#8]
I find that the stride in the last block in ResNet is set to 2 in this [implementation](https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/model/faster_rcnn/resnet.py#L117), but is set to 1 in [ruotianluo](https://github.com/ruotianluo/pytorch-faster-rcnn/blob/master/lib/nets/resnet_v1.py#L127).

However, because the output size from RoI pooling is 7 as set in [here](https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/model/utils/config.py#L286), I think a stride of 2 may lead to a too small feature map after `RCNN_top`.

So which is better, a stride of 1 or 2?

**Comment by jwyang** [comment]
thanks for pointing out this difference. I did not try stride=1. From what we got from stride=1 and ruotian's results, it seems that there is no difference, but I will compare two settings.

**Comment by jwyang** [comment]
Hi @clavichord93 , 

I tried to set stride=1 on PASCAL_VOC, and it obtained a slight better performance than stride=2 when using roi crop-resize (0.756 vs. 0.754 at epoch=6). However, the computational time cost is slightly longer for stride=1 than stride=2. Hence, it depends on what we care more when setting the stride.
