### ISSUE TITLE
clamp class label ?

### ISSUE THREAD

**Issue by liyangliu** [jwyang/faster-rcnn.pytorch#80]
Hi, @jwyang, I found in the code that you wrote:
https://github.com/jwyang/faster-rcnn.pytorch/blob/67086628162df1c865634f84864cd8b527570cd0/lib/roi_data_layer/roibatchLoader.py#L179
I noticed `gt_boxes` is composed of `[x1, y1, x2, y2, label]`:
https://github.com/jwyang/faster-rcnn.pytorch/blob/67086628162df1c865634f84864cd8b527570cd0/lib/roi_data_layer/minibatch.py#L45-L46
so this line would clamp all the above 5 variables **including class label** to `[0, trim_size]`, but I thought we should only clamp `[x1, y1, x2, y2]` to `trim_size`. Maybe this won't cause any side effect for dataset with small number of classes, i.e. `label` is always smaller than `trim_size`. But for dataset such as Visual Genome that has more than 7000 classes, this would clamp all classes whose `label` are larger than `trim_size` to `trim_size`. Should we change it to:

`gt_boxes[:, :4].clamp_(0, trim_size)`?

Thanks.

**Comment by jwyang** [comment]
Hi, @liyangliu , thanks for point out this! Yes, we should not clamp all 5 elements! I will make some modifications to the code. Again, thanks for pointing out this.
