### ISSUE TITLE
MAX_SIZE?

### ISSUE THREAD

**Issue by edouardoyallon** [jwyang/faster-rcnn.pytorch#81]
Hi!

First of all, thanks for this amazing implementation!!

I had a question about the following: the README mentions a MAX_SIZE at the testing time, for COCO, in the tables of https://github.com/jwyang/faster-rcnn.pytorch#benchmarking. After reading carefully the code, I observed that the MAX_SIZE is indeed implemented in demo.py but I am not sure to understand how it works when using the dataset reader, as the following lines are commented:

https://github.com/jwyang/faster-rcnn.pytorch/blob/1cc61212e833eefca555a0beb61ff0a4c4693e5b/lib/model/utils/blob.py#L46-L47

Thanks a lot for your help!!

Best,
Edouard

**Comment by jiasenlu** [comment]
Hi Edouard

Thanks for pointing this out. Usually, we resize the image based on the shortest edge. The MAX_SIZE is used to prevent the longer edge from being too lone. I think we should not comment this out. (Althought this migh have only a little effect on the performance. )

**Comment by edouardoyallon** [comment]
Hi, thank you very much for this precision! Indeed, it has a negligible effect on the final performance. Thanks again
