### ISSUE TITLE
How can I obtain entire confusion matrix - precision and recall?

### ISSUE THREAD

**Issue by GSteinberg** [jwyang/faster-rcnn.pytorch#810]
I want to be able to view the entire confusion matrix for my models (i.e. precision and recall for each class). 

I have been using this implementation for a while and I know I can obtain AP for each class and mean AP. The problem with that is I trained a model and obtained a 1.000 AP using test_net.py for one of my classes only to find, after looking at the demo, that I had a significant amount of false positives for that class.

I am also curious how exactly AP is calculated if it does not take false positives into account. I suppose I should examine the code more...

Thanks!

**Comment by changccanddd** [comment]
Have you solved the problem?

**Comment by GSteinberg** [comment]
Yes, I have.

**Comment by woshichunge12** [comment]
how to view the entire confusion matrix ?thanks
