### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by Johntan-G** [jwyang/faster-rcnn.pytorch#83]
Hi, I have met some problem in my running, help you help to see what is the problem is?
I execute your command 
    `python trainval_net.py  --dataset pascal_voc --net vgg16 --bs 1 --cuda `
Here are the output of the console:
Called with args:
Namespace(batch_size=1, checkepoch=1, checkpoint=0, checkpoint_interval=10000, checksession=1, class_agnostic=False, cuda=True, dataset='pascal_voc', disp_interval=100, large_scale=False, lr=0.001, lr_decay_gamma=0.1, lr_decay_step=5, mGPUs=False, max_epochs=20, net='vgg16', num_workers=0, optimizer='sgd', resume=False, save_dir='./data/pretrained_model', session=1, start_epoch=1, use_tfboard=False)
Using config:
{'ANCHOR_RATIOS': [0.5, 1, 2],
 'ANCHOR_SCALES': [8, 16, 32],
 'CROP_RESIZE_WITH_MAX_POOL': False,
 'CUDA': False,
 'DATA_DIR': '/hdd/PycharmProjects/faster-rcnn.pytorch-master_bak/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'vgg16',
 'FEAT_STRIDE': [16],
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MAX_NUM_GT_BOXES': 20,
 'MOBILENET': {'DEPTH_MULTIPLIER': 1.0,
               'FIXED_LAYERS': 5,
               'REGU_DEPTH': False,
               'WEIGHT_DECAY': 4e-05},
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'POOLING_MODE': 'align',
 'POOLING_SIZE': 7,
 'RESNET': {'FIXED_BLOCKS': 1, 'MAX_POOL': False},
 'RNG_SEED': 3,
 'ROOT_DIR': '/hdd/PycharmProjects/faster-rcnn.pytorch-master_bak',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'MODE': 'nms',
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'gt',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'RPN_TOP_N': 5000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': False,
           'BATCH_SIZE': 256,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'BIAS_DECAY': False,
           'BN_TRAIN': False,
           'DISPLAY': 10,
           'DOUBLE_BIAS': True,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'LEARNING_RATE': 0.01,
           'MAX_SIZE': 1000,
           'MOMENTUM': 0.9,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 8,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_ITERS': 5000,
           'SNAPSHOT_KEPT': 3,
           'SNAPSHOT_PREFIX': 'res101_faster_rcnn',
           'STEPSIZE': [30000],
           'SUMMARY_INTERVAL': 180,
           'TRIM_HEIGHT': 600,
           'TRIM_WIDTH': 600,
           'TRUNCATED': False,
           'USE_ALL_GT': True,
           'USE_FLIPPED': True,
           'USE_GT': False,
           'WEIGHT_DECAY': 0.0005},
 'USE_GPU_NMS': True}
Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
voc_2007_trainval gt roidb loaded from /hdd/PycharmProjects/faster-rcnn.pytorch-master_bak/data/cache/voc_2007_trainval_gt_roidb.pkl
done
Preparing training data...
done
before filtering, there are 10022 images...
after filtering, there are 10022 images...
10022 roidb entries
Loading pretrained weights from data/pretrained_model/vgg16_caffe.pth
[session 1][epoch  1][iter    0] loss: 4.9538, lr: 1.00e-03
                        fg/bg=(60/196), time cost: 27.562158
                        rpn_cls: 0.8240, rpn_box: 0.4568, rcnn_cls: 3.0558, rcnn_box 0.6171
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1511315759884/work/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "trainval_net.py", line 323, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/windows98/miniconda2/envs/torch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/hdd/PycharmProjects/faster-rcnn.pytorch-master_bak/lib/model/faster_rcnn/faster_rcnn.py", line 47, in forward
    base_feat = self.RCNN_base(im_data)
  File "/home/windows98/miniconda2/envs/torch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/windows98/miniconda2/envs/torch/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/windows98/miniconda2/envs/torch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/windows98/miniconda2/envs/torch/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 254, in forward
    self.padding, self.dilation, self.groups)
  File "/home/windows98/miniconda2/envs/torch/lib/python2.7/site-packages/torch/nn/functional.py", line 52, in conv2d
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1511315759884/work/torch/lib/THC/generic/THCStorage.cu:66

But besides, I monitor the GPU at the same time, here are the log of the GPU:
Wed Feb 28 14:58:33 2018       
+------------------------------------------------------------------------------------------------------------------------------------+
| NVIDIA-SMI 384.98                             Driver Version: 384.98                                                               |
|--------------------------------------------+--------------------------------+------------------------------------------------------+
| GPU  Name        Persistence-M             |         Bus-Id        Disp.A          |             Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap           |         Memory-Usage              |          GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off                    | 00000000:01:00.0  On          |                                        N/A |
| 27%   37C    P2    29W / 120W                |   1485MiB /  6071MiB            |                       0%      Default |
+------------------------------------------------------+--------------------------------------+--------------------------------------+
+-------------------------------------------------------------------------------------------------------------------------------------+
| Processes:                                                                                                                        GPU Memory |
|  GPU       PID   Type   Process name                                                                                      Usage      |
|=============================================================================|
|    0          986      G      /usr/lib/xorg/Xorg                                                                                    320MiB |
|    0        1725      G      compiz                                                                                                      98MiB |
|    0        2019      G      ...-token=2079968D827F520BAFB0C36EC8787C90                              70MiB |
|    0        2359      G      unity-control-center                                                                                     2MiB |
|    0        3254      G      share/jetbrains-toolbox/jetbrains-toolbox                                                  16MiB |
|    0     11347      C       python                                                                                                     973MiB |
+-------------------------------------------------------------------------------------------------------------------------------------+

Wed Feb 28 14:58:34 2018       
+------------------------------------------------------------------------------------------------------------------------------------+
| NVIDIA-SMI 384.98                             Driver Version: 384.98                                                               |
|--------------------------------------------+--------------------------------+------------------------------------------------------+
| GPU  Name        Persistence-M             |         Bus-Id        Disp.A          |             Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap           |         Memory-Usage              |          GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off                    | 00000000:01:00.0  On          |                                        N/A |
| 27%   40C    P2    111W / 120W              |   3841MiB /  6071MiB            |                     66%      Default |
+------------------------------------------------------+--------------------------------------+--------------------------------------+
+-------------------------------------------------------------------------------------------------------------------------------------+
| Processes:                                                                                                                        GPU Memory |
|  GPU       PID   Type   Process name                                                                                      Usage      |
|=============================================================================|
|    0          986      G      /usr/lib/xorg/Xorg                                                                                    320MiB |
|    0        1725      G      compiz                                                                                                      98MiB |
|    0        2019      G      ...-token=2079968D827F520BAFB0C36EC8787C90                              70MiB |
|    0        2359      G      unity-control-center                                                                                     2MiB |
|    0        3254      G      share/jetbrains-toolbox/jetbrains-toolbox                                                  16MiB |
|    0     11347      C       python                                                                                                    3329MiB |
+-------------------------------------------------------------------------------------------------------------------------------------+

Wed Feb 28 14:58:35 2018       
+------------------------------------------------------------------------------------------------------------------------------------+
| NVIDIA-SMI 384.98                             Driver Version: 384.98                                                               |
|--------------------------------------------+--------------------------------+------------------------------------------------------+
| GPU  Name        Persistence-M             |         Bus-Id        Disp.A          |             Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap           |         Memory-Usage              |          GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off                    | 00000000:01:00.0  On          |                                        N/A |
| 27%   40C    P0    42W / 120W                |    510MiB /  6071MiB            |                      50%      Default |
+------------------------------------------------------+--------------------------------------+--------------------------------------+
+-------------------------------------------------------------------------------------------------------------------------------------+
| Processes:                                                                                                                        GPU Memory |
|  GPU       PID   Type   Process name                                                                                      Usage      |
|=============================================================================|
|    0          986      G      /usr/lib/xorg/Xorg                                                                                    320MiB |
|    0        1725      G      compiz                                                                                                      98MiB |
|    0        2019      G      ...-token=2079968D827F520BAFB0C36EC8787C90                              70MiB |
|    0        2359      G      unity-control-center                                                                                     2MiB |
|    0        3254      G      share/jetbrains-toolbox/jetbrains-toolbox                                                  16MiB |
+-------------------------------------------------------------------------------------------------------------------------------------+

I doesn't what happen, I do set the batch size as 1, but still out of memory, is then anything I miss?

**Comment by jiasenlu** [comment]
Hi @Johntan-G Could you try ResNet101 as backend? we find that ResNet101 is actually consumed less memory compare to VGG16.

**Comment by Xinzhu-Fang** [comment]
I am running on 3 tesla k-80 and I set batch size to be 1. I am still getting this error? Is this expected?

**Comment by alexshaodong** [comment]
> Hi, I have met some problem in my running, help you help to see what is the problem is?
> I execute your command
> `python trainval_net.py --dataset pascal_voc --net vgg16 --bs 1 --cuda `
> Here are the output of the console:
> Called with args:
> Namespace(batch_size=1, checkepoch=1, checkpoint=0, checkpoint_interval=10000, checksession=1, class_agnostic=False, cuda=True, dataset='pascal_voc', disp_interval=100, large_scale=False, lr=0.001, lr_decay_gamma=0.1, lr_decay_step=5, mGPUs=False, max_epochs=20, net='vgg16', num_workers=0, optimizer='sgd', resume=False, save_dir='./data/pretrained_model', session=1, start_epoch=1, use_tfboard=False)
> Using config:
> {'ANCHOR_RATIOS': [0.5, 1, 2],
> 'ANCHOR_SCALES': [8, 16, 32],
> 'CROP_RESIZE_WITH_MAX_POOL': False,
> 'CUDA': False,
> 'DATA_DIR': '/hdd/PycharmProjects/faster-rcnn.pytorch-master_bak/data',
> 'DEDUP_BOXES': 0.0625,
> 'EPS': 1e-14,
> 'EXP_DIR': 'vgg16',
> 'FEAT_STRIDE': [16],
> 'GPU_ID': 0,
> 'MATLAB': 'matlab',
> 'MAX_NUM_GT_BOXES': 20,
> 'MOBILENET': {'DEPTH_MULTIPLIER': 1.0,
> 'FIXED_LAYERS': 5,
> 'REGU_DEPTH': False,
> 'WEIGHT_DECAY': 4e-05},
> 'PIXEL_MEANS': array([[[ 102.9801, 115.9465, 122.7717]]]),
> 'POOLING_MODE': 'align',
> 'POOLING_SIZE': 7,
> 'RESNET': {'FIXED_BLOCKS': 1, 'MAX_POOL': False},
> 'RNG_SEED': 3,
> 'ROOT_DIR': '/hdd/PycharmProjects/faster-rcnn.pytorch-master_bak',
> 'TEST': {'BBOX_REG': True,
> 'HAS_RPN': True,
> 'MAX_SIZE': 1000,
> 'MODE': 'nms',
> 'NMS': 0.3,
> 'PROPOSAL_METHOD': 'gt',
> 'RPN_MIN_SIZE': 16,
> 'RPN_NMS_THRESH': 0.7,
> 'RPN_POST_NMS_TOP_N': 300,
> 'RPN_PRE_NMS_TOP_N': 6000,
> 'RPN_TOP_N': 5000,
> 'SCALES': [600],
> 'SVM': False},
> 'TRAIN': {'ASPECT_GROUPING': False,
> 'BATCH_SIZE': 256,
> 'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
> 'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
> 'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
> 'BBOX_NORMALIZE_TARGETS': True,
> 'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
> 'BBOX_REG': True,
> 'BBOX_THRESH': 0.5,
> 'BG_THRESH_HI': 0.5,
> 'BG_THRESH_LO': 0.0,
> 'BIAS_DECAY': False,
> 'BN_TRAIN': False,
> 'DISPLAY': 10,
> 'DOUBLE_BIAS': True,
> 'FG_FRACTION': 0.25,
> 'FG_THRESH': 0.5,
> 'GAMMA': 0.1,
> 'HAS_RPN': True,
> 'IMS_PER_BATCH': 1,
> 'LEARNING_RATE': 0.01,
> 'MAX_SIZE': 1000,
> 'MOMENTUM': 0.9,
> 'PROPOSAL_METHOD': 'gt',
> 'RPN_BATCHSIZE': 256,
> 'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
> 'RPN_CLOBBER_POSITIVES': False,
> 'RPN_FG_FRACTION': 0.5,
> 'RPN_MIN_SIZE': 8,
> 'RPN_NEGATIVE_OVERLAP': 0.3,
> 'RPN_NMS_THRESH': 0.7,
> 'RPN_POSITIVE_OVERLAP': 0.7,
> 'RPN_POSITIVE_WEIGHT': -1.0,
> 'RPN_POST_NMS_TOP_N': 2000,
> 'RPN_PRE_NMS_TOP_N': 12000,
> 'SCALES': [600],
> 'SNAPSHOT_ITERS': 5000,
> 'SNAPSHOT_KEPT': 3,
> 'SNAPSHOT_PREFIX': 'res101_faster_rcnn',
> 'STEPSIZE': [30000],
> 'SUMMARY_INTERVAL': 180,
> 'TRIM_HEIGHT': 600,
> 'TRIM_WIDTH': 600,
> 'TRUNCATED': False,
> 'USE_ALL_GT': True,
> 'USE_FLIPPED': True,
> 'USE_GT': False,
> 'WEIGHT_DECAY': 0.0005},
> 'USE_GPU_NMS': True}
> Loaded dataset `voc_2007_trainval` for training
> Set proposal method: gt
> Appending horizontally-flipped training examples...
> voc_2007_trainval gt roidb loaded from /hdd/PycharmProjects/faster-rcnn.pytorch-master_bak/data/cache/voc_2007_trainval_gt_roidb.pkl
> done
> Preparing training data...
> done
> before filtering, there are 10022 images...
> after filtering, there are 10022 images...
> 10022 roidb entries
> Loading pretrained weights from data/pretrained_model/vgg16_caffe.pth
> [session 1][epoch 1][iter 0] loss: 4.9538, lr: 1.00e-03
> fg/bg=(60/196), time cost: 27.562158
> rpn_cls: 0.8240, rpn_box: 0.4568, rcnn_cls: 3.0558, rcnn_box 0.6171
> THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1511315759884/work/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
> Traceback (most recent call last):
> File "trainval_net.py", line 323, in 
> rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
> File "/home/windows98/miniconda2/envs/torch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in **call**
> result = self.forward(*input, **kwargs)
> File "/hdd/PycharmProjects/faster-rcnn.pytorch-master_bak/lib/model/faster_rcnn/faster_rcnn.py", line 47, in forward
> base_feat = self.RCNN_base(im_data)
> File "/home/windows98/miniconda2/envs/torch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/windows98/miniconda2/envs/torch/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
> input = module(input)
> File "/home/windows98/miniconda2/envs/torch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/windows98/miniconda2/envs/torch/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 254, in forward
> self.padding, self.dilation, self.groups)
> File "/home/windows98/miniconda2/envs/torch/lib/python2.7/site-packages/torch/nn/functional.py", line 52, in conv2d
> return f(input, weight, bias)
> RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1511315759884/work/torch/lib/THC/generic/THCStorage.cu:66
> 
> But besides, I monitor the GPU at the same time, here are the log of the GPU:
> Wed Feb 28 14:58:33 2018
> +------------------------------------------------------------------------------------------------------------------------------------+
> | NVIDIA-SMI 384.98 Driver Version: 384.98 |
> |--------------------------------------------+--------------------------------+------------------------------------------------------+
> | GPU Name Persistence-M | Bus-Id Disp.A | Volatile Uncorr. ECC |
> | Fan Temp Perf Pwr:Usage/Cap | Memory-Usage | GPU-Util Compute M. |
> |===============================+======================+======================|
> | 0 GeForce GTX 106... Off | 00000000:01:00.0 On | N/A |
> | 27% 37C P2 29W / 120W | 1485MiB / 6071MiB | 0% Default |
> +------------------------------------------------------+--------------------------------------+--------------------------------------+
> +-------------------------------------------------------------------------------------------------------------------------------------+
> | Processes: GPU Memory |
> | GPU PID Type Process name Usage |
> |=============================================================================|
> | 0 986 G /usr/lib/xorg/Xorg 320MiB |
> | 0 1725 G compiz 98MiB |
> | 0 2019 G ...-token=2079968D827F520BAFB0C36EC8787C90 70MiB |
> | 0 2359 G unity-control-center 2MiB |
> | 0 3254 G share/jetbrains-toolbox/jetbrains-toolbox 16MiB |
> | 0 11347 C python 973MiB |
> +-------------------------------------------------------------------------------------------------------------------------------------+
> 
> Wed Feb 28 14:58:34 2018
> +------------------------------------------------------------------------------------------------------------------------------------+
> | NVIDIA-SMI 384.98 Driver Version: 384.98 |
> |--------------------------------------------+--------------------------------+------------------------------------------------------+
> | GPU Name Persistence-M | Bus-Id Disp.A | Volatile Uncorr. ECC |
> | Fan Temp Perf Pwr:Usage/Cap | Memory-Usage | GPU-Util Compute M. |
> |===============================+======================+======================|
> | 0 GeForce GTX 106... Off | 00000000:01:00.0 On | N/A |
> | 27% 40C P2 111W / 120W | 3841MiB / 6071MiB | 66% Default |
> +------------------------------------------------------+--------------------------------------+--------------------------------------+
> +-------------------------------------------------------------------------------------------------------------------------------------+
> | Processes: GPU Memory |
> | GPU PID Type Process name Usage |
> |=============================================================================|
> | 0 986 G /usr/lib/xorg/Xorg 320MiB |
> | 0 1725 G compiz 98MiB |
> | 0 2019 G ...-token=2079968D827F520BAFB0C36EC8787C90 70MiB |
> | 0 2359 G unity-control-center 2MiB |
> | 0 3254 G share/jetbrains-toolbox/jetbrains-toolbox 16MiB |
> | 0 11347 C python 3329MiB |
> +-------------------------------------------------------------------------------------------------------------------------------------+
> 
> Wed Feb 28 14:58:35 2018
> +------------------------------------------------------------------------------------------------------------------------------------+
> | NVIDIA-SMI 384.98 Driver Version: 384.98 |
> |--------------------------------------------+--------------------------------+------------------------------------------------------+
> | GPU Name Persistence-M | Bus-Id Disp.A | Volatile Uncorr. ECC |
> | Fan Temp Perf Pwr:Usage/Cap | Memory-Usage | GPU-Util Compute M. |
> |===============================+======================+======================|
> | 0 GeForce GTX 106... Off | 00000000:01:00.0 On | N/A |
> | 27% 40C P0 42W / 120W | 510MiB / 6071MiB | 50% Default |
> +------------------------------------------------------+--------------------------------------+--------------------------------------+
> +-------------------------------------------------------------------------------------------------------------------------------------+
> | Processes: GPU Memory |
> | GPU PID Type Process name Usage |
> |=============================================================================|
> | 0 986 G /usr/lib/xorg/Xorg 320MiB |
> | 0 1725 G compiz 98MiB |
> | 0 2019 G ...-token=2079968D827F520BAFB0C36EC8787C90 70MiB |
> | 0 2359 G unity-control-center 2MiB |
> | 0 3254 G share/jetbrains-toolbox/jetbrains-toolbox 16MiB |
> +-------------------------------------------------------------------------------------------------------------------------------------+
> 
> I doesn't what happen, I do set the batch size as 1, but still out of memory, is then anything I miss?

Hello! I also encounter this situation, I would like to ask in which file to adjust the batch size? I can't find it. Thank you!
