### ISSUE TITLE
30X GPU cannot work for setup.py

### ISSUE THREAD

**Issue by ghost** [jwyang/faster-rcnn.pytorch#854]
Thanks for the work!

I'm currently using 3080 to compile the cuda code, but got "nvcc fatal   : Unsupported gpu architecture 'compute_86'".
Is there any plan to fix/update this?

**Comment by fosterr** [comment]
Have had the same problem.
If you use the master branch which needs pytorch 0.4.0 then you'll need cuda 8 or 9. The RTX30XX graphics cards don't support cuda 8 or 9. You must use an older graphics card.

A list of graphics cards and cuda versions is given at wikipedia.

https://en.wikipedia.org/wiki/CUDA
