### ISSUE TITLE
ImportError: /home/JXX/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: __cudaRegisterFatBinaryEnd

### ISSUE THREAD

**Issue by Jiaxin-lucky** [jwyang/faster-rcnn.pytorch#858]
CUDA_VISIBLE_DEVICES=$GPU_ID python trainval_net.py --dataset pascal_voc --net vgg16 --bs $BATCH_SIZE --nw $WORKER_NUMBER --lr $LEARNING_RATE --lr_decay_step $DECAY_STEP --cuda
Traceback (most recent call last):
  File "trainval_net.py", line 31, in <module>
    from model.utils.net_utils import weights_normal_init, save_net, load_net, \
  File "/home/JXX/faster-rcnn.pytorch/lib/model/utils/net_utils.py", line 8, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/home/JXX/faster-rcnn.pytorch/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/home/JXX/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ImportError: /home/JXX/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: __cudaRegisterFatBinaryEnd

I run this code with 30X GPU and have the problem showing above, is there anyone who has the same problem, either?
Looking forward the solution, thanks!

**Comment by ChriisYoung** [comment]
同样问题

**Comment by LuoXiang-LX** [comment]
同，未找到_roi_crop

**Comment by y72428026** [comment]
Using pytorch 0.4.0, and modifying the cuda and nvcc setting in each make.sh can fix the problem.
