### ISSUE TITLE
Speed of ROIPooling and ROIAlign

### ISSUE THREAD

**Issue by hdjsjyl** [jwyang/faster-rcnn.pytorch#87]
@jwyang , thanks for your code. I have a problem about speed of ROIPooling and ROIAlign. I test faster-rcnn with mxnet. I find that speed of roiAlign is double lower than roiPooling. Can you share your experience for speed of ROIPooling and ROIAlign？ Thank you very much.

**Comment by jwyang** [comment]
Yes, RoIAlign has more computations than roipooling since it involves bilinear interpolations.

**Comment by hdjsjyl** [comment]
@jwyang  thanks for your reply. I have another problem. When I output the feature maps of resnet, I found a problem that values of feature maps of res block2 and res block4 are normal, but values of res block3 include nan. So why values in res block3 are nan , and values in res block4 are still normal. Thank you very much!
