### ISSUE TITLE
KeyError for model

### ISSUE THREAD

**Issue by zeehasham** [jwyang/faster-rcnn.pytorch#88]
I am getting an error when I run demo.py. I am using resnet pretrained model caffe file for VOC

command is 

python demo.py --cfg cfgs/res101.yml --net res101 --cuda

Error is

fasterRCNN.load_state_dict(checkpoint['model'])
KeyError: 'model'

Any help would be really appreciated.

**Comment by jwyang** [comment]
Hi, @zeehasham , you should add the checkpoint by adding:

--checksession $SESSION --checkepoch $EPOCH --checkpoint $CHECKPOINT \

check the readme for details
