### ISSUE TITLE
Pretrained model not found

### ISSUE THREAD

**Issue by wihn2021** [jwyang/faster-rcnn.pytorch#885]
The model on the VT server is not available.

**Comment by wihn2021** [comment]
I can’t open Dropbox link either. Can you share another download link for pretrained models?

**Comment by wihn2021** [comment]
Fine. I have solved it.

**Comment by CHENZHI99** [comment]
> Fine. I have solved it.

could you tell me how you solved this problem?

**Comment by wihn2021** [comment]
> 

Later I realized the Dropbox link is available.
If you need, I can share by BaiduNetdisk or Google Drive.

**Comment by wihn2021** [comment]
> > Fine. I have solved it.
> 
> could you tell me how you solved this problem?

I'll share the model soon.
Could you please help me solve this problem? I just don't know how to load the pretrained model.
https://github.com/jwyang/faster-rcnn.pytorch/issues/886

**Comment by wihn2021** [comment]
> > Fine. I have solved it.
> 
> could you tell me how you solved this problem?

https://wx.mail.qq.com/ftn/download?func=3&key=cdcb5d6499c16f1dffb8176463636362565d9f6e61636362171b015d570656530356145d5553504f060c0b514c5a5a510b195d510755510150055c070300706240514a0a04175252036b5a050705064c424051705872c52ec4c911eca0d41a9518f2629c21ddbe73&code=249daccb&k=cdcb5d6499c16f1dffb8176463636362565d9f6e61636362171b015d570656530356145d5553504f060c0b514c5a5a510b195d510755510150055c070300706240514a0a04175252036b5a050705064c424051705872c52ec4c911eca0d41a9518f2629c21ddbe73&fweb=1&cl=1

**Comment by CHENZHI99** [comment]
> > > Fine. I have solved it.
> > 
> > 
> > could you tell me how you solved this problem?
> 
> https://wx.mail.qq.com/ftn/download?func=3&key=cdcb5d6499c16f1dffb8176463636362565d9f6e61636362171b015d570656530356145d5553504f060c0b514c5a5a510b195d510755510150055c070300706240514a0a04175252036b5a050705064c424051705872c52ec4c911eca0d41a9518f2629c21ddbe73&code=249daccb&k=cdcb5d6499c16f1dffb8176463636362565d9f6e61636362171b015d570656530356145d5553504f060c0b514c5a5a510b195d510755510150055c070300706240514a0a04175252036b5a050705064c424051705872c52ec4c911eca0d41a9518f2629c21ddbe73&fweb=1&cl=1

Thanks, I'll let you know if I've successfully loaded the pretrained model。

**Comment by djamil-ait** [comment]
Can someone please update the link, i cant find the pretrained model

**Comment by zhouwer** [comment]
> > 
> 
> Later I realized the Dropbox link is available. If you need, I can share by BaiduNetdisk or Google Drive.
can you send me this weight file ? thank!!!!!!!
