### ISSUE TITLE
question about epoch-counting

### ISSUE THREAD

**Issue by cyvius96** [jwyang/faster-rcnn.pytorch#92]
In trainval_net.py:

By default it only trained for (max_epoch - 1) epochs.

It seems that epoch should mean "the number of done epoch", thus start_epoch's default value should be 0, and some details should be modified in the training loop?

btw, is "epoch % (args.lr_decay_step + 1) = 0" a typo that "+1"?

**Comment by cyvius96** [comment]
OK, thanks for your great work.

**Comment by jwyang** [comment]
closing this issue
