### ISSUE TITLE
Blog about how R-CNNs work

### ISSUE THREAD

**Issue by ankur6ue** [jwyang/faster-rcnn.pytorch#95]
I have written a blog that explains in detail how R-CNNs work. It largely follows the implementation in this repo, so should be helpful to people trying to understand the inner workings of the code and making modifications:

http://www.telesens.co/2018/03/11/object-detection-and-classification-using-r-cnns/

**Comment by jwyang** [comment]
@ankur6ue , this blog is so cool! I would like to point it at the readme. 👍

**Comment by ankur6ue** [comment]
@jwyang 
Glad you found it useful, feel free to add a link to the blog on the readme. That's the best way for people to find it.
