### ISSUE TITLE
Detailed info about the Visual Genome-pretrained model

### ISSUE THREAD

**Issue by jnhwkim** [jwyang/faster-rcnn.pytorch#97]
Thanks for sharing your work!

[Bottom-up Attention](https://github.com/peteanderson80/bottom-up-attention) is trained on the annotated attributes for each region along with object classes. However, I guess the VG pretrained model in this README is just trained on object classes?

I will appreciate if you confirm my observation.

**Comment by jwyang** [comment]
@jnhwkim yes, you are right, I did not add the attribute as another supervision.

**Comment by jnhwkim** [comment]
good to know! i’ve tried faster rcnn features (coco) instead bottom-up attention features for vqa task but i got poor results. i suspect few #classes of coco or that attribute maybe critical... any comment?

**Comment by jwyang** [comment]
Hi, @jnhwkim, yes, you are right, we did some ablation studies on the VQA tasks, and found the number of object categories and the number of training data both affected the performance. The more categories and number of images, the better performance you can get. Bottom up features are trained on 1750 object categories, and 400 attributes, it should be much better.
